Feature/#10 회원가입페이지 생성
BCSDLab/KOIN_WEB_RECODE pull request #14
Opened 2022-09-12 13:43 UTC by SimYunSup

## #10  request

- 회원가입 페이지 생성
  - 컴포넌트 분리/`useLightweightForm`훅 분리 하지 않은 이유
    - 다른 곳에서 쓰이지 않음
    - 쓰여도 modify에서만 쓰임
    - 보기 힘들다면 분리하겠습니다.
  - modify에서 쓰인다면 useLightweightForm에서 defaultValue를 고려해서 수정해야 합니다.

## Please check if the PR fulfills these requirements

- [x] It's submitted to `develop` branch, __not__ the `main` branch
- [x] The commit message follows our guidelines
- [x] There are no warning message when you run `yarn lint`
- [x] Docs updated for breaking changes

### Screenshot

![image](https://user-images.githubusercontent.com/47362439/189668362-73a6c7e2-c6be-499a-b5c5-33dc0a0b8908.png)

2022-09-13 11:31 UTC, ChoiWonBeen requested changes
고생하셨습니다. 리뷰내용 확인해주세용 🚀

2022-09-13 11:31 UTC, ChoiWonBeen commented on src/pages/Auth/AuthPage/Auth.module.scss
> +@use "src/utils/scss/media" as media;
`@use`를 사용하면 변수명이 이미 파일명일텐데 as로 재정의한 이유가 있나요?

2022-09-13 11:31 UTC, ChoiWonBeen commented on src/pages/Auth/SignupPage/SignupPage.module.scss
> +
반응형에서 디자인이 전부 깨집니다.
속성이 추가로 들어가야 할 것 같네요.

```suggestion
.signup {
  display: flex;
  flex-wrap: wrap;
  @include media.media-breakpoint(mobile) {
    justify-content: center;
  }
```

2022-09-13 11:31 UTC, ChoiWonBeen commented on src/pages/Auth/SignupPage/SignupPage.module.scss
> +    font-family: NanumSquareB, sans-serif;
NanumSquareB가 폰트에 있나요?
기본폰트로 적용중인 NanumSquareR 의 bold버전으로 처리하는게 옳나 싶습니다.

2022-09-13 11:31 UTC, ChoiWonBeen commented on src/pages/Auth/SignupPage/SignupPage.module.scss
> +    &--large-font {
버튼마다 modifier로 재사용하는게 인상적이네요.
그런데 flex-end는 여러 block마다 추가되어있는데 차라리 .flex-end로 쉽게 추가할 수 있게 사용하는건 어떨까요?

2022-09-13 11:31 UTC, ChoiWonBeen commented on src/pages/Auth/SignupPage/hooks/useNicknameDuplicateCheck.ts
> +        }
현재 코인 서버는 올바르지 않은 닉네임 형식에 대한 response는 412 에러를 보냅니다. 그리고 조건이 겹치네요.

2022-09-13 11:31 UTC, ChoiWonBeen commented on src/pages/Auth/SignupPage/index.tsx
> +    ? (deptList as unknown as Array<IDept>)?.find(
오 책에서나 본 고급기술이다 ㄷㄷ

2022-09-13 11:52 UTC, SimYunSup commented on src/pages/Auth/SignupPage/SignupPage.module.scss
> +
[498b27c](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/14/commits/498b27c0504d09ac9309b1bfbcf3dc6d7b720506) 수정하였습니다.

2022-09-13 11:52 UTC, SimYunSup commented on src/pages/Auth/SignupPage/SignupPage.module.scss
> +    }
[0e759e4](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/14/commits/0e759e4c6a88691c9683a29c09891a377dbcc303) 수정하였습니다.

2022-09-13 11:53 UTC, SimYunSup commented on src/pages/Auth/SignupPage/SignupPage.module.scss
> +    font-family: NanumSquareB, sans-serif;
[e7b862d](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/14/commits/e7b862d21cf582cd7dbe34588ecba145960e12be) 수정하였습니다.

2022-09-13 11:53 UTC, SimYunSup commented on src/pages/Auth/SignupPage/hooks/useNicknameDuplicateCheck.ts
> +        }
[261e93a](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/14/commits/261e93a3ac2ea9a338f5ad124654810b696e28a9) 수정하였습니다.

2022-09-13 12:05 UTC, ChoiWonBeen requested changes
요거만 수정되면 저는 다 본 것 같습니다~

2022-09-13 12:05 UTC, ChoiWonBeen commented on src/pages/Auth/SignupPage/SignupPage.module.scss
> +
```suggestion
    appearance: none;
```
해당 속성이 추가되어야 기본 버튼을 벗어나서 디자인해둔 체크박스가 나올겁니다.

2022-09-14 11:20 UTC, daepan requested changes
@SimYunSup 
회원가입폼을 이정도로 재렌더링을 최적화하다니...
약간의 수정사항만 고쳐주시면 될 것 같습니다! 
고생하셨습니다.

2022-09-14 11:20 UTC, daepan commented on src/pages/Auth/SignupPage/index.tsx
> +
와! 올해 최고의 LGTM입니다.
onSubmit을 ref로 필요한 것만 연결해서 관리하다니...!
꼭 저도 자세히 한번 만들게 된 계기나 과정있으면 포스팅을 통해 알려주세요.

2022-09-14 13:23 UTC, pumpkiinbell commented on src/utils/ts/showToast.ts
> +
저는 이런 경우엔 가독성이나 응집성을 위해 method 형태로 구현하는 것 같아요 이런 방식도 있다는 점에서 넘어가도 좋을것 같습니다~

```tsx
export default Object.assign({}, { 
  open: (type: ToastType, message: string) => toast(message, { type: toast.TYPE[TOAST_TYPE[type]] });
  });
```

```tsx
import toaster from "~/utils/ts/toaster.ts";

toaster.open();
```

2022-09-14 13:23 UTC, pumpkiinbell commented on src/pages/Auth/SignupPage/hooks/useNicknameDuplicateCheck.ts
> +        }
같은 조건이 두 번 쓰인것 같네요!?

2022-09-14 13:23 UTC, pumpkiinbell commented on src/pages/Auth/SignupPage/hooks/useNicknameDuplicateCheck.ts
> +    {
useSignup 에서 useMutation 을 한단계 추상화한것처럼 useQuery 도 추상화를 할 수 있어 보여요

2022-09-14 13:28 UTC, pumpkiinbell commented on src/pages/Auth/SignupPage/index.tsx
> +    showToast('error', invalidFormEntry[1] as string);
isCurrentValidEntries 가 어떻게 추론되나요...? 만약 values 가 제대로 추론되지 않는다면 entries 에 generic 을 넣어서 추론되게 만들 수 있을것 같아요

2022-09-14 13:29 UTC, pumpkiinbell commented on src/pages/Auth/SignupPage/index.tsx
> +    }
RHF 처럼 string | true 로 타입을 지정한게 되게 마음에 드네요 ㅎㅎㅎ

2022-09-15 09:07 UTC, SimYunSup commented on src/utils/ts/showToast.ts
> +
후에 Toast를 없애야 하는 메소드도 필요한 경우 말씀하신대로 구현하는 것이 좋아보이네요 :) 조언 감사합니다.

2022-09-15 09:10 UTC, SimYunSup commented on src/pages/Auth/SignupPage/index.tsx
> +    showToast('error', invalidFormEntry[1] as string);
추론을 하지 않고 명시적으로 타입을 줌으로써 해결했습니다 :) 감사합니다

2022-09-15 12:44 UTC, ChoiWonBeen approved these changes

2022-09-17 12:52 UTC, daepan approved these changes
고생하셨습니다!

2022-09-18 11:15 UTC, merged

2022-09-18 11:18 UTC, HAEROOL commented
잘 봤습니다! React에서 TS를 어떻게 사용할 지에 대해 막막한 감이 있었는데, 많은 참고가 된 것 같습니다. 고생하셨습니다:)