상점 목록 페이지 작성
BCSDLab/KOIN_WEB_RECODE pull request #16
Opened 2022-09-18 10:58 UTC by daepan

## [#13] request

상점 페이지 생성 완료.
- 세션스토리지로 관리하던 검색어 필터 요소 URL 파라미터를 통해 필터링하도록 기능 변경
- 전체보기 카테고리 추가(아직 전체보기 이미지 추가와 UI 변경에 대해 아직 나온 것이 없어 카페를 지우고 임시이미지로 대체하였습니다)

## Please check if the PR fulfills these requirements

- [ ] It's submitted to `develop` branch, __not__ the `main` branch
- [ ] The commit message follows our guidelines
- [ ] There are no warning message when you run `yarn lint`
- [ ] Docs updated for breaking changes

### Screenshot
<img width="1440" alt="스크린샷 2022-09-18 오후 7 56 54" src="https://user-images.githubusercontent.com/50792467/190898646-68f79c2f-fc68-4369-8af5-531b245c4478.png">

2022-09-18 12:07 UTC, ChoiWonBeen requested changes
실행중 몇가지 버그를 발견했습니다.
1. `/store` 라우팅에 헤더와 푸터가 없습니다.
2. 라우팅 시 전체를 불러오지 못합니다.
3. 검색을 두 번 하면 두번째 결과가 없어집니다. (ex. "123"검색 후 "1234" 검색 시, 검색어 자체가 사라짐)

2022-09-18 12:39 UTC, SimYunSup requested changes
몸 상태가 좋지 않아 이유/미사여구를 안 붙인 점 죄송하게 생각합니다.

고칠 점이 많아 더 생각하고 고치셨으면 합니다.

2022-09-18 12:39 UTC, SimYunSup commented on src/pages/StorePage/index.tsx
> +};
작동하지 않습니다.

2022-09-18 12:39 UTC, SimYunSup commented on src/pages/StorePage/index.tsx
> +              { isStoreOpen(store.open_time, store.close_time) && <div className={styles['store-none-open']} />}
`before`와 같은 가상클래스에 content를 넣지 말고 밖에 놓아주세요.

2022-09-18 12:39 UTC, SimYunSup commented on src/pages/StorePage/index.tsx
> +                </div>
이 부분은 모바일에서 해당 옵션이 가능하다는 점을 보여줘야 할 것으로 보입니다. 방식은 다양하니 제시한 방법 외로 구현해도 됩니다. 그리고 모바일에서 안 보입니다. 그리고 disabled 되었을 때 안 보이게 하는 것 뿐만 아니라 없애야 할 것 같습니다.

- radio로 옵션이 가능하다는 점을 보이기
- 계좌이체 뒤에 가능이라는 텍스트를 두고 숨기기

2022-09-18 12:39 UTC, SimYunSup commented on src/pages/StorePage/index.tsx
> +  };
`setSearchParams`를 할 경우 `replace`하도록 바꿔주세요. 사용자가 뒤로가기를 했을 때 불편을 겪을 확률이 높습니다.

2022-09-18 12:39 UTC, SimYunSup commented on src/pages/StorePage/index.tsx
> +  const [searchParams, setSearchParams] = useSearchParams();
searchParams 관련 훅을 따로 만들어주세요.

2022-09-18 12:39 UTC, SimYunSup commented on src/pages/StorePage/index.tsx
> +        <img className={styles.search_bar__icon} src="https://static.koreatech.in/assets/img/search.png" alt="search_icon" />
버튼을 클릭해도 검색되게 만들어주세요.

2022-09-18 12:57 UTC, daepan commented
머지 중 라우팅 수정이 잘못되어 나오지 못한 부분이 있었습니다. 내용은 정상적으로 작동하도록 해두었습니다. 밑의 기능들에서 발견된 오류들 한번 수정해두겠습니다.

2022-09-21 11:09 UTC, daepan commented on src/pages/StorePage/index.tsx
> +                </div>
모바일에서 출력되지 않는 것은 확인되었습니다. 
일단은 모바일에서 display: block으로 해주게 되어 모바일에서는 출력되게 변경하였습니다.
추가적으로 질문 주신 사항에 대해 의문이 생깁니다. 과연 모바일에서 해당 옵션이 가능하다는 것을 보여준다는 것 어떤 의미인지를 잘 모르겠습니다.
사용성을 높히거나 더 좋은 방식의  보여줄 수 있게 할 수 있다면 시도해보겠지만, 어떤 식으로 개선을 원하시는지 예시 혹은 자세한 설명 부탁드립니다.

2022-09-22 09:37 UTC, daepan commented on src/pages/StorePage/index.tsx
> +  const [searchParams, setSearchParams] = useSearchParams();
훅 분리 완료했습니다. 잘못된 점 있다면 첨삭 혹은 피드백바랍니다.
[51dc6b1](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/16/commits/51dc6b1e7b945fe1ef632951f78906decc1b69d5)

2022-09-22 09:38 UTC, daepan commented on src/pages/StorePage/index.tsx
> +                </div>
제안해주신 내용을 처리를 위해 aria-hidden을 활용해 제거했습니다.
[c4b84ea](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/16/commits/c4b84ea34ca837ab4796752188d176c88eefce93)

2022-09-23 11:28 UTC, ChoiWonBeen requested changes
고생하셨어요~~ 리뷰 확인해서 수정해주세요!

2022-09-23 11:28 UTC, ChoiWonBeen commented on src/pages/StorePage/StorePage.module.scss
> +    background-color: #fff;
`cursor: pointer` 가 추가되어야 합니다.

2022-09-23 11:28 UTC, ChoiWonBeen commented on src/pages/StorePage/StorePage.module.scss
> +    }
selected라는 이름이 어울려보이고,
선택되지 않은 나머지 카테고리 목록들의 `font-weight`이 높게 조정되어있습니다.

2022-09-23 11:28 UTC, ChoiWonBeen commented on src/pages/StorePage/index.tsx
> +            <div className={styles['store-list__item']} key={store.id}>
해당 카드에 키보드로 접근할 수 없습니다. 
상세페이지로 가는 기능도 필요할텐데 Link나 Button으로 감쌀 필요가 있어보입니다.

2022-09-23 11:28 UTC, ChoiWonBeen commented on src/pages/StorePage/index.tsx
> +          </b>
`b`태그를 bold처리를 위해 사용을 [권장하지 않습니다](https://developer.mozilla.org/ko/docs/Web/HTML/Element/b). 

그 이유를 찾아보면서 알아낸 사실인데, [접근성을 고려해서 `strong`태그를 사용](https://stackoverflow.com/a/271776)하라고 하네요.

2022-09-24 10:07 UTC, daepan commented on src/pages/StorePage/StorePage.module.scss
> +  padding-left: 16px;
[2f64e50](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/16/commits/2f64e5086de6212f606d95246cdd86390eba57f8)
모바일헤더에서 width가 벗어나고 있어서 widht 100%를 제거하여 auto로 하도록 해두었습니다

2022-09-24 10:49 UTC, daepan commented on src/pages/StorePage/StorePage.module.scss
> +    }
selected로 변경하였고 선택된 카테고리의 경우에는 font-weight이 증가하도록 변경하였습니다.
[b195d4f](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/16/commits/b195d4fe47717f8e0eb4733f9f140a59d252c43f)
[d81c27b](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/16/commits/d81c27b0a8c6eade2a72335542154db575a98c8a)

2022-09-24 10:49 UTC, daepan commented on src/pages/StorePage/StorePage.module.scss
> +    background-color: #fff;
[f78df2a](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/16/commits/f78df2a74d9adc2da3b0ded58577605feaf0365e)
추가 되었습니다!

2022-09-24 10:49 UTC, daepan commented on src/pages/StorePage/index.tsx
> +            <div className={styles['store-list__item']} key={store.id}>
상세페이지 기능때 추가하려 했지만 미리 추가해두었습니다 :)
[da9e688](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/16/commits/da9e68818cd130b23102d7b09665e7b6ffb0b761)

2022-09-24 10:49 UTC, daepan commented on src/pages/StorePage/index.tsx
> +          </b>
새로운 정보군요! 감사합니다
[8d5b938](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/16/commits/8d5b938238f7cdd266e7128ca800d071953977f3)

2022-09-24 10:57 UTC, ChoiWonBeen submitted a review, later dismissed

2022-09-24 11:10 UTC, ChoiWonBeen approved these changes

2022-09-24 11:14 UTC, SimYunSup approved these changes

2022-09-25 09:57 UTC, merged