[식단 상세보기] QA반영 및 UX개선
BCSDLab/KOIN_WEB_RECODE pull request #165
Opened 2024-04-12 00:03 UTC by KimKyungYun

- Close #164 

## What is this PR? 🔍

- 기능 : QA반영 및 DatePicker UI개선, 미제공 식단 표시하지 않기
- issue : #164 

## Changes 📝

QA사항을 반영하여 값이 오지 않는 금액이 null로 표시되는 문제를 수정하였고,
미제공 식단에 대해 UI를 표시하지 않도록 설정했습니다.

## ScreenShot 📷

![image](https://github.com/BCSDLab/KOIN_WEB_RECODE/assets/60084235/d1fecd8e-c930-4df7-8d14-6ab700ab0f3a)
![image](https://github.com/BCSDLab/KOIN_WEB_RECODE/assets/60084235/8102c8bc-0626-4e1c-a6d3-dd87c773f2b6)

## Test CheckList ✅

- [ ] 현재날짜 전후에 따른 DatePicker의 색상의 차이
- [ ] 미제공식단의 표시여부

## Precaution

## Please check if the PR fulfills these requirements

- [ ] It's submitted to `develop` branch, __not__ the `main` branch
- [ ] The commit message follows our guidelines
- [ ] There are no warning message when you run `yarn lint`
- [ ] Docs updated for breaking changes

2024-04-12 02:08 UTC, daepan requested changes
수고하셨습니다. 몇 가지 질문 사항 남겨두었습니다. 답변 주시면 감사하겠습니다.

2024-04-12 02:08 UTC, daepan commented on src/pages/Cafeteria/CafeteriaPage/index.tsx
> +                        (value) => value.place === cafeteriaCategory.placeName
UI return 부분에서 Meal 함수를 따로 선언하셨는데 return 부분에서 함수선언은 저 같은 경우에는 가독성이 떨어지는 부분이라 생각해서 별로 사용하지 않는 케이스인데 특별하게 사용하신 이유가 있을까요?
따로 함수를 선언해서 조건부 렌더링 방식을 사용하지 않은 이유가 궁금합니다.

2024-04-12 02:11 UTC, KimKyungYun commented on src/pages/Cafeteria/CafeteriaPage/index.tsx
> +                ? CAFETERIA_CATEGORY.map((cafeteriaCategory) => (
좋은 생각입니다 ㅎ 기존에 작성된 코드를 최대한 유지하면서 진행하려고 했더니 개선점을 신경쓰지못했던 것 같습니다.
바로 반영하겠습니다!

2024-04-12 02:21 UTC, KimKyungYun commented on src/pages/Cafeteria/CafeteriaPage/index.tsx
>                                <div className={styles['category__menu-photo--soldOut']}>
오호 이미 좋은 기능이 존재하고 있었군요! 바로 수정하겠습니다

2024-04-12 02:41 UTC, KimKyungYun commented on src/pages/Cafeteria/CafeteriaPage/index.tsx
> +                        (value) => value.place === cafeteriaCategory.placeName
이 부분도 위와같이 기존의 코드를 유지하는 방안에 너무 초점을 둔 나머지, 개선해야할 점을 그냥 넘겨버린 것 같습니다..
한번 개선해서 반영해보겠습니다 ㅎ

2024-04-12 02:50 UTC, junghaesung79 commented
<img width="488" alt="image" src="https://github.com/BCSDLab/KOIN_WEB_RECODE/assets/96577250/9da5dd2d-4df0-4cb3-b2bd-9b718d34c56e">
컴포넌트 분리를 하면 좋겠지만 지금은 QA 이슈 처리니까 넘어가는 게 좋겠죠..?

2024-04-12 04:45 UTC, junghaesung79 approved these changes

2024-04-12 04:47 UTC, KimKyungYun commented
@junghaesung79 때마침 위에 리뷰 대응하느라 컴포넌트로 분리했습니다 ㅎ

2024-04-13 13:58 UTC, daepan approved these changes
수고하셨습니다.

2024-04-15 01:08 UTC, merged