Feature/#17
BCSDLab/KOIN_WEB_RECODE pull request #18
Opened 2022-10-11 01:38 UTC by daepan

## [#17] 상점 상세페이지 작성

상세페이지 UI 작성 및 상점 포스터 모달 작성

## Please check if the PR fulfills these requirements

- [ ] It's submitted to `develop` branch, __not__ the `main` branch
- [ ] The commit message follows our guidelines
- [ ] There are no warning message when you run `yarn lint`
- [ ] Docs updated for breaking changes

### Screenshot
<img width="1439" alt="스크린샷 2022-10-11 오전 10 34 49" src="https://user-images.githubusercontent.com/50792467/194977816-fe81364a-b544-418f-a68e-92c0a218b81a.png">
상점 상세페이지 

![image](https://user-images.githubusercontent.com/50792467/194977750-2b4a1c07-2068-42b5-9e0a-6e4607beb517.png)
상점 이미지 모달 (portal을 통해서 최상단에서 렌더링)

![image](https://user-images.githubusercontent.com/50792467/194977789-912fdfc1-76df-460d-816b-3087be4261ad.png)
상점 이미지 모달에서 사진 여러장일 경우에 대한 이동 클릭이벤트 작성

2022-10-11 06:44 UTC, SimYunSup requested changes
일부 TS의 안티패턴과 버그를 수정 요청 부탁드렸습니다.
@pumpkiinbell 의 PortalProvider에 대한 의견도 듣고 싶네요. 가능하면 PortalProvider에 대한 부분만 리뷰해주세요.

2022-10-11 06:44 UTC, SimYunSup commented on src/api/store/entity.ts
> +  }[],
string[]으로 바꿔주세요.

2022-10-11 06:44 UTC, SimYunSup commented on src/pages/Store/StoreDetailPage/index.tsx
> +  };
1. any 쓰지 마세요.
2. 모바일에서 openModal했을 때 두번째 이미지를 클릭했을 때 자동으로 첫번째 이미지로 뜹니다. 고쳐야 합니다.

2022-10-11 06:44 UTC, SimYunSup commented on src/pages/Store/StoreDetailPage/index.tsx
> +          </button>
1. 네이밍이 block-element__elemen이므로 block__element__element와 다를바 없다고 생각합니다. CSS Module이 적용되어있으니 차라리 `image__contnet`와 같이 써주세요.
2. image에 각자 button이 감싸야 합니다. 통합 버튼이 있는게 아니라요.
3. 2와 연계되어 스크롤 안됩니다.

2022-10-11 06:44 UTC, SimYunSup commented on src/components/common/Modal/PortalProvider.tsx
> +export const PortalProvider = function PortalProvider({ children }: any) {
1. any 쓰지 마세요.
2. 현재 코인에서는 중첩 modal을 지원할 생각이 없습니다. 중첩 modal을 지원한 이유라도 있을까요?
3. recoil이 있는데 Context API를 쓴 이유가 있을까요?

2022-10-11 10:37 UTC, daepan commented on src/pages/Store/StoreDetailPage/index.tsx
> +              <span>#계좌이체가능</span>
죄송합니다. 미처 확인하지 못한 부분 지적해주셔서 감사합니다
[3b41b28](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/18/commits/3b41b28b4233dae8b96b958f954dab65eb27280a)

2022-10-11 10:38 UTC, daepan commented on src/pages/Store/StoreDetailPage/hooks/useStoreDetail.ts
> +const useStoreDetail = (params: any) => {
타입 추가해둔다는 걸 깜빡했군요. 지적 감사합니다 👍 
[7a0950f](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/18/commits/7a0950f134e13406c8abeda8c1afd82ece846187)

2022-10-11 10:39 UTC, daepan commented on src/pages/Store/StoreDetailPage/index.tsx
> +  };
타입 추가해둔다는 걸 깜빡했군요. 지적 감사합니다 👍 
모바일 부분 테스트를 제대로 하지 못했습니다. 한번 더 확인해보겠습니다.
[7a0950f](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/18/commits/7a0950f134e13406c8abeda8c1afd82ece846187)

2022-10-11 10:39 UTC, daepan commented on src/pages/Store/StoreDetailPage/index.tsx
> +          </button>
전체적으로 className 수정했습니다. 이름 짓기 어렵네요 ㅠ
[1c08328](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/18/commits/1c08328a2a36cccd51838b7d666229f0a9e50294)

2022-10-11 10:56 UTC, daepan commented on src/components/common/Modal/PortalProvider.tsx
> +export const PortalProvider = function PortalProvider({ children }: any) {
1. [7a0950f](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/18/commits/7a0950f134e13406c8abeda8c1afd82ece846187)
수정해두었습니다!

2. 중첩 모달을 노린다기 보다는 원래 훅 라이브러리를 리팩토링 하는 과정에서 id 값을 하나로 고정해둔 상태입니다. 
현재 코드 수정이 아니라면 제가 만든 이 훅은 중첩 모달로 사용하지 못할 겁니다. 
구조적으로 중첩모달로 보일 수 있는 부분을 수정하도록 할까요?

3. context api 에서 상태값을 변경하면, provider 로 감싼 모든 자식 컴포넌트들이 리렌더링한다라는 단점이 있지만,
해당 Mordla의 경우에는 아예 외부에 선언되기에 recoil을 사용하나 context API를 사용하나 리렌더링에 큰 차이가 없을 거라고 생각했습니다

2022-10-11 10:57 UTC, daepan commented on src/api/store/entity.ts
> +  }[],
타입에 많이 익숙하지 않았군요 감사합니다.
[4e0da75](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/18/commits/4e0da7526ece4cb79affdfb8463574ae855220f0)

2022-10-11 10:57 UTC, daepan commented on src/components/common/Modal/ImageModal/ImageModal.module.scss
> +  cursor: pointer;
잘못된 커서 속성 지적 감사합니다!
[a19b982](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/18/commits/a19b982b674ee727cbc07baef292a3fe7483fdb3)

2022-10-11 14:36 UTC, ChoiWonBeen requested changes
고생하셨습니다!
고려해볼만한 사항들과 수정사항 올려놨으니 확인해주세요~

2022-10-11 14:36 UTC, ChoiWonBeen commented on src/components/common/Modal/PortalProvider.tsx
> +    </PortalContext.Provider>
제가 생각했던 단순한 Portal의 구현은, 
```tsx
export function ModalProvider({ Modal, isOpen, otherProps }) {
  if (isOpen) {
    return (createPortal(<Modal {...otherProps} />, document.body));
  }

  return null;
}
```
`createPortal`로 props혹은 children으로 전달한 Modal을 담아주는 `<ModalProvider />`를 만들어서,

```tsx
<ModalProvider Modal={Modal} isOpen={modalOpen} otherProps={{image: ....}} /> 
```
이렇게 만든 ModalProvider에 Modal을 담아주는 방식으로 생각했습니다.

`PortalProvider`를 최상단에 위치하도록 만들게되면 createPortal을 쓰는 이유가 희석되지 않을까요?? 
이 방법만의 장점이 궁금합니다..!

2022-10-11 14:36 UTC, ChoiWonBeen commented on src/components/common/Modal/ImageModal/index.tsx
> +    <div className={styles.background}>
PC에선 배경이 눌리거나 ESC키가 눌렸을 때 모달이 닫히는 게 좋은 UX일 것 같고,
모바일 환경에선 뒤로가기 버튼이 눌렸을 때 모달이 닫히는게 좋은 UX라고 생각합니다.
이런 구현이 되게끔 수정이 가능할까요??

2022-10-11 14:36 UTC, ChoiWonBeen commented on src/pages/Store/StoreDetailPage/index.tsx
> +              { storeDetail?.pay_bank && <span>#계좌이체가능</span> }
각 태그의 글자가 버튼에서 조금 상단에 치우쳐 있습니다.

2022-10-11 15:04 UTC, daepan commented on src/pages/Store/StoreDetailPage/index.tsx
> +              { storeDetail?.pay_bank && <span>#계좌이체가능</span> }
아 확인했습니다. 해당 부분 수정해보겠습니다.

2022-10-11 15:04 UTC, daepan commented on src/components/common/Modal/PortalProvider.tsx
> +export const PortalProvider = function PortalProvider({ children }: any) {
이거는 제가 훅을 잘못 이해했습니다. 리팩토링 다시하면서 수정해보겠습니다

2022-10-11 15:11 UTC, ChoiWonBeen commented on src/components/common/Modal/ImageModal/index.tsx
> +}
중첩모달을 제외하게끔 수정하면서, 사진에 대한 상태관리를 수정해야할 것 같아요.
선택된 모달에 대한 상태는 모달의 오픈 여부와 함께 DetailPage에서 관리하는게 좋을 것 같네요.
추가로 그 둘을 공통훅으로 감싸서 사용하면 편리할 것 같네요

2022-10-11 16:51 UTC, daepan commented on src/api/store/entity.ts
> +    created_at: string,
혹시 이거 있게 되면은 따로 빌드파일의 영향을 줄까요? 크게 지장이 없는거면 그대로 둬도 괜찮지 않을까 싶습니다.
나중에 저걸 활용해야할 수도 있으니 남겨두는 것도 차후 업데이트할 때 api를 분석할 필요가 줄어들 것 같습니다

2022-10-12 02:37 UTC, ChoiWonBeen commented on src/components/common/Modal/ImageModal/index.tsx
> +}
단순 구조상으로 생각했을때 ImageModal이 상태를 가질 이유가 없지 않나요?

ImageModal을 호출하는건 DetailPage고,
어떤 이미지가 띄워질 지 정하는 것도 DetailPage입니다.

ImageModal은 단순 props로 띄워야 할 이미지의 정보만 받으면 괜찮지 않을까요?
좌우버튼때문이라면 해당 정보도 props로 넘겨주는게 가능해보이네요. props가 너무 방대해지려나..

2022-10-13 01:29 UTC, D0Dam reviewed
수고하셨습니다. ImageModal 창 관련한 코드를 우선적으로 보았습니다. 
개인적인 생각과 UI적으로 추가했으면 하는 점을 작성해 보았으니 참고 부탁드립니다.

2022-10-13 01:29 UTC, D0Dam commented on src/components/common/Modal/ImageModal/ImageModal.module.scss
> +  cursor: pointer;
image에 클릭 이벤트가 별도로 존재하지 않아서 `cursor:pointer`가 없어도 될 것 같습니다.

add)
그리고 개인적인 UI 의견인데... 이 상점에 사진이 몇장 있는지 볼 수 있는 UI가 있었으면 합니다.(모달창을 켰을 때나 닫았을 때 언제라도) 예를 들자면 사진 수가 4개라면 .... 와 같이 사진 밑에 표시할 수 있는 UI라던가,  예시 사진으로 작게 들어가는 것도 좋겠네요.
ex) 출처 Apple developer
<img width="297" alt="스크린샷 2022-10-13 오전 10 08 37" src="https://user-images.githubusercontent.com/51052049/195475713-64156cab-8c70-4a83-9998-8ee54ea2faa4.png">

2022-10-13 01:29 UTC, D0Dam commented on src/components/common/Modal/ImageModal/ImageModal.module.scss
> +  max-width: 600px;
1. 이미지의 width를 600px으로 고정시켜놓아서 모바일 뷰인 574px로 되기 전까지 몇몇 상점들의 사진들이 가로가 잘립니다.
2. 그리고 이 때문에 화면이 작아지면 이미지 뒤로 버튼이 숨습니다.
따라서 이미지 width를 다르게 주어야 할 것 같습니다.
그리고 prev, next 버튼도 z-index 값을 높여주어 앞으로 빼거나 하는 방식으로 작은 화면에도 버튼을 어떻게 배치하거나 사용할 수 있게 할지 고민해 보아야 할 것 같습니다.
참고용 gif 올려둡니다.
![Oct-13-2022 10-15-06](https://user-images.githubusercontent.com/51052049/195476892-7964b333-5d6e-4071-9323-32f356d01436.gif)

2022-10-13 01:29 UTC, D0Dam commented on src/components/common/Modal/ImageModal/index.tsx
> +}
1. `image`라고 하면 뭔가 그 url이라던지 하는 사진 그 자체를 들고 있을 것 같습니다. 따라서 다른 사람들이 보았을 때 `image`가 왜 객체 배열을 담고 있지? 하는 의문이 들 수 있을 것 같습니다. 이도 좋은 네이밍이라고는 말 못하겠지만`imageList`..라던지 네이밍을 조금 수정하는게 어떨까하는 개인적인 의견입니다.
2. 이건 원빈이랑 같은 네이밍 의견이긴한데, 저는 `selectImg`라는 표현 자체가 함수라는 느낌보다는 number Type을 가진다고 생각하기 어려웠습니다. 타입에 맞는 네이밍이면 좋지 않을까 생각해봅니다.

2022-10-14 04:35 UTC, daepan commented on src/components/common/Modal/ImageModal/ImageModal.module.scss
> +  cursor: pointer;
cursor 부분이 기준 없이 들어가있었군요 지적 감사합니다 👍 
add 부분은 UI 팀과 관련이 있어서 직접적으로 추가하기는 어려울 것 같습니다. ㅠ

2022-10-14 04:37 UTC, daepan commented on src/components/common/Modal/ImageModal/ImageModal.module.scss
> +  max-width: 600px;
사진 크기들이 워낙 다들 제각각이라 확인하지 못한 부분이었습니다.
사진 크기를 동적으로 할 수 있도록 조정해보겠습니다

2022-10-14 04:38 UTC, daepan commented on src/pages/Store/StoreDetailPage/index.tsx
> +              { storeDetail?.pay_bank && <span>#계좌이체가능</span> }
padding 값을 조절해서 적절한 위치로 수정했습니다
[51faafe](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/18/commits/51faafe806d9e362e6af924bbad8b7294d76b979)

2022-10-14 04:42 UTC, daepan commented on src/components/common/Modal/PortalProvider.tsx
> +    </PortalContext.Provider>
음 이걸 제가 굉장히 많이 고민하고 분석해보았습니다.
결국에는 createPortal 만 사용한다고해서 모달이 출력되지 않더군요 어딘가에서는 반드시 출력을 해주어야 합니다. 그 방식으로 저는 contextAPI를 통해 PortalProvider를 App.tsx 파일에 출력을 두어 생성되도록 훅과 컴포넌트로 변경하였습니다.

2022-10-14 04:44 UTC, daepan commented on src/components/common/Modal/ImageModal/ImageModal.module.scss
> +  @media (max-width: 576px) {
변경해두었습니다 👍 
[f32a96b](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/18/commits/f32a96bfb9e1d1bb02369245355c9e897cf3d7d5)

2022-10-14 04:44 UTC, daepan commented on src/components/common/Modal/ImageModal/index.tsx
> +    <div className={styles.background}>
일단 ESC 는 개선하였습니다
[fa92d1a](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/18/commits/fa92d1a986aa72711f2f7b916a0ff99e241845ab)

2022-10-14 06:26 UTC, daepan commented on src/components/common/Modal/ImageModal/ImageModal.module.scss
> +  max-width: 600px;
max-width 를 모바일 크기에 맞게 수정하였고
버튼 z-index 위치를 올려두었습니다 👍 
[d2c8bfd](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/18/commits/d2c8bfd050adcd37e594f54b2fe7b1632a23fac8)

2022-10-14 06:27 UTC, daepan commented on src/components/common/Modal/ImageModal/index.tsx
> +    <div className={styles.background}>
스크롤 이벤트도 막고, 화살표 클릭시 이동하는 기능까지 추가했습니다
[c0f2128](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/18/commits/c0f2128db79c50cd4a0f335fa3427b1c27a53a2e)

2022-10-14 12:16 UTC, ChoiWonBeen requested changes
좌우 키보드에 모달에서의 이미지 변경이 동작하는게 좋네요 👍 
근데 테스트하다가 확인한 버그인데, 모달을 띄워둔 채로 뒤로가기 등으로 탭을 옮기면 모달이 그대로 남아있습니다 ㅋㅋㅋ 분리를 너무 해놔서 그런것같네요

2022-10-14 12:16 UTC, ChoiWonBeen commented on src/pages/Store/StoreDetailPage/hooks/useStoreDetail.ts
> +const useStoreDetail = (params: any) => {
any보다는 id값이 들어오니 number가 맞지 않을까요?

2022-10-14 12:16 UTC, ChoiWonBeen commented on src/pages/Store/StoreDetailPage/hooks/useStoreDetail.ts
> +  const storeDescription = storeDetail?.description ? parse(storeDetail?.description.replace(/(?:\\r\\n|\\r|\\n|\r|\n|\r\n)/g, '<br />')) : '-';
`html-react-parser`의 parse가 어떤 역할을 하나요??
그리고 지금 코인 식당들 설명에는 줄바꿈 없이 `/`로 구분하더라구요?
추후에 줄바꿈이 생기고나서, 이를 구현하기 위해서라면 `\n`을 유지한 채 `white-space: pre-wrap`정도로 해결하는게 어떨까 싶어요.

2022-10-14 12:16 UTC, ChoiWonBeen commented on src/components/common/Modal/ImageModal/hooks/useModalClickEvent.ts
> +    return () => window.removeEventListener('keydown', (event: KeyboardEvent) => pressKey(event));
익명함수로 작성한 이벤트리스너라서 `removeEventListener`가 동작하지 않을 것 같아요.

2022-10-14 12:16 UTC, ChoiWonBeen commented on src/components/common/Modal/ImageModal/hooks/useModalClickEvent.ts
> +function useModalClickEvent({ onClose, handleClickImage }: ClickEventProps) {
키보드이벤트를 다뤄주는 훅인데 ClickEvent보단 KeyboardEvent는 어떨까요? ㅋㅋ 
그리고 객체로 인자를 받는기보단, 두 개 인자를 받아서 쓰는게 재사용에 도움될 것 같아요

2022-10-14 13:21 UTC, daepan commented on src/pages/Store/StoreDetailPage/hooks/useStoreDetail.ts
> +const useStoreDetail = (params: any) => {
any 타입 제거가하겠습니다

2022-10-14 14:04 UTC, daepan commented on src/pages/Store/StoreDetailPage/hooks/useStoreDetail.ts
> +  const storeDescription = storeDetail?.description ? parse(storeDetail?.description.replace(/(?:\\r\\n|\\r|\\n|\r|\n|\r\n)/g, '<br />')) : '-';
아 이부분 제가 제플린 통해서 확인해봤는데 원래 줄바꿈이 되어야합니다. 3년전에는 위에 띄어쓰기나 그런게 다 존재를 해서 저런 식으로 replace이후 parser를 활용했었는데 방식이 변경되었는지 다르게 출력되고 있었던 겁니다.
<img width="1440" alt="스크린샷 2022-10-14 오후 11 03 52" src="https://user-images.githubusercontent.com/50792467/195866486-f005a0d9-ef16-489f-a276-fd0b3a9a674b.png">

2022-10-14 14:15 UTC, ChoiWonBeen commented on src/pages/Store/StoreDetailPage/hooks/useStoreDetail.ts
> +  const storeDescription = storeDetail?.description ? parse(storeDetail?.description.replace(/(?:\\r\\n|\\r|\\n|\r|\n|\r\n)/g, '<br />')) : '-';
현재 어드민에는 줄바꿈을 지원하지 않으니, 파서를 사용할 필요가 없어보이고,
다음 어드민에 추가된다 하더라도 `\n`으로 제공되는 줄바꿈을 단순 CSS속성으로 해결하는게 맞는 것 같아요.

2022-10-14 14:18 UTC, ChoiWonBeen commented on src/components/common/Modal/ImageModal/hooks/useModalClickEvent.ts
> +function useModalClickEvent({ onClose, handleClickImage }: ClickEventProps) {
**onClose와 handleClickImage라는 메소드를 담고있는 객체**를 인자로 주고있는거니깐요.
두 함수를 담고있는 객체를 보내는것보단, 그냥 함수 두개를 인자로 받는거에 대한 생각은 어떤가요?

2022-10-14 14:23 UTC, daepan commented on src/pages/Store/StoreDetailPage/hooks/useStoreDetail.ts
> +  const storeDescription = storeDetail?.description ? parse(storeDetail?.description.replace(/(?:\\r\\n|\\r|\\n|\r|\n|\r\n)/g, '<br />')) : '-';
결국은 현상황만 보았을때는 / 을 줄바꿈을 해야될 것 같습니다.
그리고 저런식의 표현식을 놔두면 어떤 자료형이 와도 바로 줄바꿈이 되어서 UI가 저런식으로 나오게 될겁니다.
만약 변경된다면 결국 변경해야할 것 같군요
지금 상황에서는 / 을 대처를 해야하기 떄문에 현 상황에서는 그대로 두는게 맞는 것 같습니다.
css에서 / 을 줄바꿈 처리하는 방법이 따로 있다면, 제안해주시면 감사하겠습니다.

2022-10-14 15:27 UTC, daepan commented on src/components/common/Modal/ImageModal/hooks/useModalClickEvent.ts
> +function useModalClickEvent({ onClose, handleClickImage }: ClickEventProps) {
위에서도 말씀드렸지만 저는 굳이? 라는 생각이 드는 겁니다.
두 가지 방식에 결정적인 차이가 있을까요 그 부분을 알려주시면 감사하겠습니다

2022-10-15 01:00 UTC, ChoiWonBeen commented on src/pages/Store/StoreDetailPage/hooks/useStoreDetail.ts
> +  const storeDescription = storeDetail?.description ? parse(storeDetail?.description.replace(/(?:\\r\\n|\\r|\\n|\r|\n|\r\n)/g, '<br />')) : '-';
" / " 를 `\n`으로 replace 하고, white space만 추가하면 될 것 같아요.

2022-10-15 01:27 UTC, ChoiWonBeen commented on src/components/common/Modal/ImageModal/hooks/useModalClickEvent.ts
> +function useModalClickEvent({ onClose, handleClickImage }: ClickEventProps) {
코드 스타일 차이일 수도 있으니 넘어가도 됩니다만,
이 훅을 사용할 때 반드시 `onClose` 와 `handleClickImage` 두 함수가 담긴 객체를 넘겨줘야 하는데, 함수 두개를 넘기려면 그냥 넘기면 될 텐데, 불필요하게 객체로 wrapping한게 아닌가 싶었습니다.

두 메소드를 담은 객체가 객체로서 쓰이지 않고, 다시 구조분해해서 사용하고 있으니, 넘길때 묶고 넘기자마자 꺼내야하는데다, 프로퍼티의 네이밍에 함수가 종속되게되니 불필요하다는 생각이 드네요 ㅋㅋ

2022-10-15 03:53 UTC, daepan commented on src/pages/Store/StoreDetailPage/hooks/useStoreDetail.ts
> +  const storeDescription = storeDetail?.description ? parse(storeDetail?.description.replace(/(?:\\r\\n|\\r|\\n|\r|\n|\r\n)/g, '<br />')) : '-';
그렇게 하면 본문 내용안에서의 띄어쓰기는 모두 줄바꿈이 될 것 같은데요? 어떻게 생각하시나요?

2022-10-15 03:56 UTC, ChoiWonBeen commented on src/pages/Store/StoreDetailPage/hooks/useStoreDetail.ts
> +  const storeDescription = storeDetail?.description ? parse(storeDetail?.description.replace(/(?:\\r\\n|\\r|\\n|\r|\n|\r\n)/g, '<br />')) : '-';
🤔?? " / "를 "\n"으로 바꾸는거지 " "를 "\n"로 바꾸는게 아닌걸요>

2022-10-15 16:06 UTC, daepan commented on src/pages/Store/StoreDetailPage/hooks/useStoreDetail.ts
> +  const storeDescription = storeDetail?.description ? parse(storeDetail?.description.replace(/(?:\\r\\n|\\r|\\n|\r|\n|\r\n)/g, '<br />')) : '-';
위에 내용 제가 오해했습니다. 3년전에 있었던 코드가 무의미하게 적혀있지 않을꺼라 생각되어 사용했었습니다.
확인 결과, 전체 변경되었고 해당 부분 요청에따라 수정하였습니다 👍 
[767ec85](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/18/commits/767ec857bf6378d22642618b12741906ef2ec1b7)

2022-10-19 10:54 UTC, daepan commented on src/components/common/Modal/PortalProvider.tsx
> +  const el = document.getElementById('modal') as HTMLElement;
요게 그 element 요소 위치가 modal을 미리해두면 맨 위로 오는데 저런식으로 만들면 하단에 생겨서 모달찾으려면 스크롤로 한번 내려서 찾아야 한다는 점이 있어서 저렇게 넣었습니다.
다시 생각해보니 내부 element가 많지 않아서, 크게 필요하지 않은 부분이기에 제거하고 위의 제시된 내용으로 수정했습니다
[67174f3](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/18/commits/67174f3761e28f9d0fae4834b2b5dcc2e5dacc22)

2022-10-19 10:55 UTC, daepan commented on src/pages/Store/StoreDetailPage/hooks/useStoreDetail.ts
> +const useStoreDetail = (params: any) => {
any 타입 지적 감사합니다
[6b60a3c](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/18/commits/6b60a3ca67dd5365e9e9f55d41673c04b1bc9e9e)

2022-10-19 10:56 UTC, daepan commented on src/components/common/Modal/ImageModal/hooks/useModalClickEvent.ts
> +    return () => window.removeEventListener('keydown', (event: KeyboardEvent) => pressKey(event));
이번 이벤트리스너에 대한 내용.. 타입스크립트 사용한다고 타입 지정한다고 했었는데 remove의 경우 제거되지 않는 현상이 있었군요.
좋은 조언 감사합니다.
[ebdd2ee](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/18/commits/ebdd2ee00b2aca31ac866cf01a5f56c5763eb3ca)

2022-10-19 11:58 UTC, kimeodml requested changes
고생하셨습니다!

2022-10-19 11:58 UTC, kimeodml commented on src/pages/Store/StoreDetailPage/StoreDetailPage.module.scss
> +    cursor: pointer;
주변 상점에 `coursor: pointer`를 넣은 이유가 궁금합니다.

2022-10-19 11:58 UTC, kimeodml commented on src/pages/Store/StoreDetailPage/index.tsx
> +                ))}
메뉴 종류가 다양한 음식점(ex. 미친짬뽕)은 스크롤이 길어져서 부담이 되는데 모바일 앱처럼 더보기 기능을 추가하면 어떨까요?

2022-10-19 14:20 UTC, daepan commented on src/pages/Store/StoreDetailPage/index.tsx
> +                ))}
음 그러면 좋을 것 같습니다. 제가 스크롤에 간단하게 줄여봤는데, 그렇게 딱히 성능향상도 없고, 디자인적으로 별로였습니다.
그래서 차라리 이 부분의 경우 UI/UX팀과 소통하여 해당 부분 디자인을 수정해달라고 이야기해보면 좋을 것 같습니다.
아마도 변경되면 안드로이드와 iOS에서도 대응을 해주어야할 부분이 될 것 같습니다. 👍 
해당 부분은 제가 이슈로 올려서 차후 기능과 디자인 수정 추가하는 기간에 진행하겠습니다.

2022-10-25 13:34 UTC, SimYunSup approved these changes
좋습니다 :)

2022-10-25 15:10 UTC, ChoiWonBeen approved these changes

2022-10-26 03:05 UTC, kimeodml approved these changes

2022-10-26 04:59 UTC, merged