[식단] 웹 식단 뷰 리뉴얼(MZ식단표)
BCSDLab/KOIN_WEB_RECODE pull request #214
Opened 2024-04-29 07:36 UTC by junghaesung79

- Close #196

## What is this PR? 🔍

- 기능 : 웹 식단 뷰 리뉴얼(MZ식단표)
- issue : #196 

## Changes 📝

웹 식단 뷰를 리뉴얼하였습니다.
* 아점저 드롭다움
* 화살표 날짜 이동
* 날짜 클릭 시 오늘로
* 일주일 클릭 시 그날로
* 오늘자에 파란 색
* 변경됨, 품절 칩
* 품절 시 사진 가리기(클릭 시 상세 보여주는 이벤트는 유지)
* 2주 전 주까지 사진 확인 가능
* 식단 여러 개일 때 masonry 형식 정렬
* 사진 클릭 시 상세(확대)

## ScreenShot 📷

<img width="974" alt="image" src="https://github.com/BCSDLab/KOIN_WEB_RECODE/assets/96577250/cebbd2cf-43a9-495b-a5e3-738cc34da7d8">
<img width="982" alt="image" src="https://github.com/BCSDLab/KOIN_WEB_RECODE/assets/96577250/460ddff7-26be-4c87-a6b2-435e60f84699">
<img width="1023" alt="image" src="https://github.com/BCSDLab/KOIN_WEB_RECODE/assets/96577250/6b08ec35-b007-4930-8d66-8b718b615bb3">

## Test CheckList ✅

## Precaution

## Please check if the PR fulfills these requirements

- [x] It's submitted to `develop` branch, __not__ the `main` branch
- [x] The commit message follows our guidelines
- [x] There are no warning message when you run `yarn lint`
- [x] Docs updated for breaking changes

2024-04-29 07:47 UTC, LUNA-KK commented
MZ하네요... 수고하셨습니다 👍

2024-04-29 11:20 UTC, hoooooony commented
<img width="1263" alt="image" src="https://github.com/BCSDLab/KOIN_WEB_RECODE/assets/112807899/b9f04758-de13-4b06-9a2e-1d3e3a7ba009">
불러오지 못한 날에 대한 정보를 알아야할 것 같아요. 로딩중인지, 에러인지 구별이 안가요
그리고 지금 날짜를 클릭할때마다 다시 블럭 크기를 계산하는것으로 보이는데 여기서 effect가 발생할때 새로고침되면서 다른 요소들도 다시 렌더링되면서 화면이 깜빡깜빡하는데 최적화가 필요해 보입니다.

2024-04-29 13:38 UTC, junghaesung79 commented
날짜 이동 시 깜빡거리는 문제의 원인을 찾고 있습니다.
현재 알게 된 것은 한 날의 식단을 불러온 다음 아점저 넘어갈 때는 깜빡거림이 없는 것으로 보아 블럭크기를 계산하는 것 때문은 아닌 것 같습니다. 
suspense를 개선하는 것으로 문제를 해결할 수 있을지 찾아보고 있습니다.

2024-04-29 14:53 UTC, LUNA-KK commented
몇가지 요청사항 남기고갑니다 ㅎㅎ 파이팅~!

- `ㅇㅇ식단` 토글 열렸을 때, 뒷배경 클릭 시 토글 닫히게 해주세요!
- 식단 사진 미리보기, 상세보기 모달 `object-fit: cover;` 요고 맞는지도 한번만 확인 부탁드릴게요 🙇‍♀️
- 이번주, 저번주 식단에 대해서만 사진 넣어주세요! (현재는 2주전까지 보여지고 있음)

2024-04-29 16:02 UTC, hoooooony commented on src/pages/Cafeteria/PCCafeteriaPage/components/DateNavigator/index.tsx
> +class DayInfo {
클래스로 선언해서 사용한 이유가 있을까요?
week배열에 날짜 정보를 넣고 싶다면
```
interface DayInfo {
  weekDay: string;
  dateOfMonth: number;
  date: Date;
}
```
로 정의해서 그냥 
```
 week.push({
      weekDay,
      dateOfMonth,
      date: newDate
    })
```; 이렇게 넣으면 될것 같아요.
[참고](https://youtu.be/qjEcsNYFWYg?si=-4YvFWhYkFXrXqX6)에서 앞부분에서 class의 this의 문제점에 대해서 말해주는데 한번 보는 걸 추천드립니다.

2024-04-30 00:47 UTC, KimKyungYun requested changes
고생하셨습니다..! 빌드쪽에 린트에러 캐치되어있는 것 같습니다. 같이 확인한번 부탁드려요!

2024-04-30 00:47 UTC, KimKyungYun commented on src/pages/Cafeteria/index.tsx
>    const { cafeteriaList } = useCafeteriaList(
깜빡이는 문제는 여기에서 API를 fetch해오는 동안 생기는 시간을 suspese의 fallback이 대체하는것 때문에 생기는 문제입니다.
해당 문제를 해결하려면, API를 호출하는 위치를 수정하는게 맞을 것 같습니다. 각각의 Cafeteria 안에 리스트를 출력하는 컴포넌트에서 해당 API를 호출하고 suspense를 해당 컴포넌트 상위에 걸어놓게 되면, 해당 리스트 UI만 Fallback으로 대체되어 깜빡이는 문제가 해결됩니다.

다만.. 번거롭고 좀 수고스러운작업이라 저같은 경우는 fetch가 잦은 컴포넌트에서는 suspense를 빼고 진행하는 방법도 많이 사용했었습니다..ㅠ

2024-04-30 00:47 UTC, KimKyungYun commented on src/pages/Cafeteria/MobileCafeteriaPage/index.tsx
> +  const logger = useLogger();
모바일은 제가 했어야했는데..ㅠ 감사합니다

2024-04-30 00:47 UTC, KimKyungYun commented on src/pages/Cafeteria/PCCafeteriaPage/index.tsx
> +          {dropdownOpen && (
해당 드롭다운은 피그마에선 드롭다운 메뉴 뒤편에 shadow가 있는거로 보이는데 누락된 것 같습니다!

2024-04-30 07:19 UTC, junghaesung79 commented on src/pages/Cafeteria/PCCafeteriaPage/index.tsx
> +          {dropdownOpen && (
수정했습니다!

2024-04-30 07:21 UTC, junghaesung79 commented on src/pages/Cafeteria/index.tsx
>    const { cafeteriaList } = useCafeteriaList(
하단으로 fetch 위치를 옮겨서 suspense를 적용했습니다!
50db04f31c3ef48b2b376395e9d903af30d7c02e

2024-04-30 07:58 UTC, MinGu-Jeong commented on src/pages/Cafeteria/MobileCafeteriaPage/index.tsx
> +        logger.actionEventClick({ actionTitle: 'SCROLL', title: 'menu_time', value: MEAL_TYPE_MAP[mealType] });
`actionTitle`에는 팀명이 들어가야됩니다!
```suggestion
        logger.actionEventClick({ actionTitle: 'CAMPUS', title: 'menu_time', value: MEAL_TYPE_MAP[mealType] });
```

2024-04-30 08:32 UTC, junghaesung79 commented on src/pages/Cafeteria/MobileCafeteriaPage/index.tsx
> +        logger.actionEventClick({ actionTitle: 'SCROLL', title: 'menu_time', value: MEAL_TYPE_MAP[mealType] });
오 실수했네요

2024-04-30 09:51 UTC, MinGu-Jeong commented on src/pages/Cafeteria/PCCafeteriaPage/components/PCMenuBlocks/index.tsx
> +        const x = columnIndex * (276 + 12); // 열 인덱스에 따라 x 위치 계산
`276+12`는 무슨 값인가요?

2024-05-01 03:35 UTC, junghaesung79 commented on src/pages/Cafeteria/PCCafeteriaPage/components/PCMenuBlocks/index.tsx
> +        const x = columnIndex * (276 + 12); // 열 인덱스에 따라 x 위치 계산
276은 식단 카드의 너비이고 12는 카드 사이 갭입니다

2024-05-01 09:02 UTC, KimKyungYun approved these changes

2024-05-02 05:32 UTC, merged