공지사항 리스트 페이지 작성
BCSDLab/KOIN_WEB_RECODE pull request #22
Opened 2022-12-05 07:56 UTC by daepan

## [#19 ] 공지사항 리스트 페이지 작성
공지사항 메인 리스트페이지와 가장 많이 본 게시글과 페이지네이션을 작성하였습니다.

변경된 내역은 아래와 같습니다.
1. api의 경우 선택된 페이지에 대해서 page를 받아오도록 하였습니다. 
2. 현재 리코드되는 내용에 대해서 추가적인 홍보페이지등의 페이지의 변동이 필요할 것을 생각 boradId를 추가해두었습니다.
3. HotPost, Post, PostList로 컴포넌트들을 분할하여 사진과 같은 UI를 구성할 때 입력값만 바꿔서 넣어준다면 재사용가능하도록 하였습니다.
4. PageNation의 경우 totalPageNum을 useParamsHandler에 값을 유지하여 페이지가 유지되는 동안으로 설정하였습니다.
5. useParamsHandler의 경우 공통훅으로 분리하였습니다

## Please check if the PR fulfills these requirements

- [ ] It's submitted to `develop` branch, __not__ the `main` branch
- [ ] The commit message follows our guidelines
- [ ] There are no warning message when you run `yarn lint`
- [ ] Docs updated for breaking changes

### S
<img width="1132" alt="스크린샷 2022-12-05 오전 1 02 09" src="https://user-images.githubusercontent.com/50792467/205583508-a3d90b84-d2bd-4a0a-83b1-ee0bcdc4c30f.png">
creenshot

2022-12-05 14:11 UTC, ChoiWonBeen requested changes
고생하셨어요. 일단은 짧게 수정사항 올려놨는데, 다음에 더 자세히 보고 마저 리뷰할게요

2022-12-05 14:11 UTC, ChoiWonBeen commented on src/pages/Notice/NoticePage/index.tsx
> +  const articleList = useArticleList(params.boardId === undefined ? '1' : params.boardId);
아래처럼 줄일 수 있을 것 같아요.
```suggestion
  const articleList = useArticleList(params.boardId ?? '1');
```

2022-12-05 14:11 UTC, ChoiWonBeen commented on src/pages/Notice/hooks/useArticleList.tsx
> +  }
`articleList`를 활용하는게 목표인 훅이니 저라면 `loading`문자열보단 명시적으로 `null`을 반환하게 만들 것 같아요.

2022-12-06 05:28 UTC, daepan commented on src/App.tsx
> +import NoticePage from 'pages/Notice/NoticePage';
폴더 구조랑 route 구조를 보았을 때 Board 아래에 store 페이지도 존재하고 있네요
두개 파일 둘다 옮기는 것으로 변경하겠습니다

2022-12-06 05:30 UTC, daepan commented on src/components/Post/HotPost/index.tsx
> +const useHotArticleList = () => {
처음에 훅으로 작성한 파일 수정하는 과정에서 네이밍 변경이 제대로 이루어지지 않았습니다.
수정하고 올리겠습니다

2022-12-06 05:36 UTC, daepan commented on src/pages/Notice/NoticePage/index.tsx
> +    if (params.totalPageNum === undefined && articleList !== 'loading') setParams('totalPageNum', String(articleList!.totalPage), false, true);
react-query를 통해 불러온 정보들은 캐싱되지만 PageNation props 전달 과정에 있어서 loading 상태가 존재하게 되면 페이지네이션에서 페이지 이동 시 페이지네이션 자체가 깜빡거리면서 사용자의 UX를 해친다고 생각하였습니다.
recoil을 사용하기에는 공지사항에서만 사용하는 정보이기에 useParamsHandler를 통해 저장하였습니다,

2022-12-06 05:37 UTC, daepan commented on src/pages/Notice/NoticePage/index.tsx
> +  }, [params, setParams, articleList]);
조건문에 의존되니 코드가 너저분하네요. 지적 감사합니다. 수정하고 올리겠습니다

2022-12-06 05:38 UTC, daepan commented on src/pages/Notice/hooks/useArticleList.tsx
> +  }
문자열을 반환하면서 메모리적으로 불필요할 수도 있겠네요 수정하겠습니다.

2022-12-06 05:38 UTC, daepan commented on src/components/Post/PostList/index.tsx
> +};
죄송합니다. 급한 일정에 맞추느라 예전코드를 리팩토링 하는 것을 빼먹었군요. 수정하겠습니다.

2022-12-06 07:23 UTC, ChoiWonBeen commented on src/pages/Notice/NoticePage/index.tsx
> +  }, [params, setParams, articleList]);
지금보니깐 문자열 '1'인 이유가 있나요? `number`형태로 바꿔쓰는게 맞을 것 같은데

2022-12-06 12:44 UTC, SimYunSup commented on src/components/Post/PageNation/index.tsx
> +            <span key={limit}>
`key`가 의미가 있나요?

2022-12-06 12:46 UTC, SimYunSup commented on src/components/Post/HotPost/HotPost.module.scss
> +@use "src/utils/scss/media" as media;
BEM 표기법을 지키려고 노력했는지 다시 한 번 생각해보심이 좋습니다.

2022-12-06 12:47 UTC, SimYunSup commented on src/components/Post/PageNation/PageNation.module.scss
> +@use "src/utils/scss/media" as media;
BEM 표기법을 지키려고 노력했는지 다시 한 번 생각해보심이 좋습니다.

2022-12-06 12:47 UTC, SimYunSup commented on src/components/Post/PostHeader/PostHeader.module.scss
> +@use "src/utils/scss/media" as media;
BEM 표기법을 지키려고 노력했는지 다시 한 번 생각해보심이 좋습니다.

2022-12-06 12:47 UTC, SimYunSup commented on src/components/Post/PageNation/index.tsx
> +const onNowPageNum = (params: string) => {
네이밍이 `changeParamstoNumber`가 좋겠네요.

2022-12-06 12:49 UTC, SimYunSup commented on src/components/Post/PageNation/index.tsx
> +function PageNation(props: PageNationProps) {
PascalCase적용이 잘못되었습니다. `Pagination`이 옳은 표현식입니다.

2022-12-06 12:51 UTC, SimYunSup commented on src/components/Post/PageNation/index.tsx
> +  const { params, setParams } = useParamsHandler();
onClick에 너무 많은 로직이 들어가 있는데다가, 해당 함수들이 무슨 역할을 하는지 모르겠습니다. Hook으로 따로 빼는 방식을 생각해 보심이 좋을 것 같습니다.

2022-12-06 12:51 UTC, SimYunSup commented on src/components/Post/PostList/PostList.module.scss
> +@use "src/utils/scss/media" as media;
BEM 표기법을 지키려고 노력했는지 다시 한 번 생각해보심이 좋습니다.

2022-12-06 12:53 UTC, SimYunSup commented on src/components/Post/PostList/index.tsx
> +};
해당 함수는 분리해야 할 것으로 보입니다.

2022-12-06 12:56 UTC, SimYunSup commented on src/utils/hooks/useParamsHandler.ts
> +  const setParams = (key: string, value: string, isDelete: boolean, replaceOption: boolean) => {
이렇게 option에 대한 파라미터를 많이 두기보다는 객체(ex.`{isDelete: boolean, replace: boolean}`)로 두는 것이 코드 확인할 때 깔끔합니다.

2022-12-12 16:05 UTC, daepan commented on src/pages/Notice/NoticePage/index.tsx
> +  }, [params, setParams, articleList]);
setParams의 인자로는 string을 받아야해서 '1'과 같은 형태로 작성하였습니다.
1을 toString이나 String(1)로 사용하는 것이 좋을까요?

2022-12-12 16:18 UTC, ChoiWonBeen commented on src/pages/Notice/NoticePage/index.tsx
> +  }, [params, setParams, articleList]);
`boardType=notice`같은 방향도 괜찮을 것 같아요. 그냥 유지해도 큰 문제는 없겠지만, 상수로 적는거보다는 의미를 가지는게 좋아보이네요 ㅋㅋ

2022-12-15 15:30 UTC, daepan commented on src/App.tsx
> +import NoticePage from 'pages/Notice/NoticePage';
[51fdd84](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/22/commits/51fdd84c21965f97074818760add8203932c6575)
구조 변경 완료했습니다.

2022-12-15 15:32 UTC, daepan commented on src/pages/Notice/hooks/useArticleList.tsx
> +  }
[0f75130](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/22/commits/0f7513081e8d88040f279536754eca334a2141d4)
null 반환으로 변경하였습니다

2022-12-15 15:34 UTC, daepan commented on src/components/Post/PageNation/PageNation.module.scss
> +@use "src/utils/scss/media" as media;
[5004e7e](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/22/commits/5004e7eeee75aaabaa306f8c63ae7cd86fc13451)
BEM 표기법 적용하였습니다.

2022-12-15 15:34 UTC, daepan commented on src/components/Post/HotPost/HotPost.module.scss
> +@use "src/utils/scss/media" as media;
[99ee710](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/22/commits/99ee710693b4655caf45e1ff6ebceca1f7089fad)
BEM 표기법 적용하였습니다

2022-12-15 15:35 UTC, daepan commented on src/components/Post/PostHeader/PostHeader.module.scss
> +@use "src/utils/scss/media" as media;
[b0dcc41](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/22/commits/b0dcc4110e579a9d0bf010275e30c035a4474ef2)
BEM 표기법 적용하였습니다.

2022-12-15 15:35 UTC, daepan commented on src/components/Post/PageNation/index.tsx
> +  const { params, setParams } = useParamsHandler();
[911952a](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/22/commits/911952aafde3b667454239e3a54cabe28bca9b38)
훅으로 분리하여 해당 click 이벤트 분리하였습니다

2022-12-15 15:36 UTC, daepan commented on src/pages/Notice/NoticePage/index.tsx
> +  }, [params, setParams, articleList]);
[10f4b5a](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/22/commits/10f4b5a95f228895592583d18139afe2354848ee)
전체 게시글을 가져오는 정보를 통한 useEffect 이기에 해당 전체를 훅으로 분리하였습니다. 한번 확인 부탁드립니다.

2022-12-15 15:37 UTC, daepan commented on src/utils/hooks/useParamsHandler.ts
> +  const setParams = (key: string, value: string, isDelete: boolean, replaceOption: boolean) => {
[ba1966d](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/22/commits/ba1966d394e784c17e07aa4e32c786213dad89f8)
인수 변경 하였습니다!

2022-12-15 15:37 UTC, daepan commented on src/components/Post/PostList/index.tsx
> +};
[bfe8df2](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/22/commits/bfe8df236c78f083a6b0c810967b9fcd429fda71)
훅을 사용해서 분리하였습니다!

2022-12-15 16:09 UTC, daepan commented on src/components/Post/HotPost/index.tsx
> +const useHotArticleList = () => {
[01e2f16](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/22/commits/01e2f1630bee1c43ade94cb1f8e7acd7b81762df)
네이밍 알맞게 변경하였습니다.

2022-12-15 16:09 UTC, daepan commented on src/pages/Notice/NoticePage/index.tsx
> +      { hotArticleList }
[c9d7d26](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/22/commits/c9d7d267f313a77527e94580fb6928f4f25ac4e1)
제안하신 내용으로 수정하였습니다.

2022-12-15 16:10 UTC, daepan commented on src/pages/Notice/NoticePage/index.tsx
> +  const articleList = useArticleList(params.boardId === undefined ? '1' : params.boardId);
새로운 조건식 배워갑니다 👍

2022-12-15 16:11 UTC, daepan commented on src/components/Post/PageNation/index.tsx
> +const onNowPageNum = (params: string) => {
[911952a](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/22/commits/911952aafde3b667454239e3a54cabe28bca9b38)
네이밍 제안감사합니다!

2022-12-16 01:16 UTC, SimYunSup requested changes
페이지네이션 부분은 다시 생각해보세요.

2022-12-16 01:16 UTC, SimYunSup commented on src/pages/BoardPage/Notice/hooks/useBoardParams.ts
> +  }, [params, setParams, articleList]);
1. boardId가 없을 때 `'1'`로 취급하는 코드를 쓰고 따로 또 `setParams`를 하는 코드를 쓴 이유가 무엇인가요?
2. url의 Params는 사용자가 쉽게 접근할 수 있는 수정가능 사항입니다. `totalPageNum`을 `params`에 저장한 이유는 무엇인가요?

2022-12-16 01:16 UTC, SimYunSup commented on src/components/Post/Pagination/hooks/usePagination.ts
> +    LIMIT_COUNT,
hook에서 상수를 반환하는 이유는 무엇인가요?

2022-12-17 10:35 UTC, daepan commented on src/components/Post/PageNation/index.tsx
> +            <span key={limit}>
해당 Key에 limit가 존재하지 않는 경우, 코인 메인헤더에 공지사항을 클릭하게 될 시
페이지네이션에 NaN 값을 가지는 버튼이 여러개 생성됩니다. 해당 상황을 방지하기 위해 위와 같은 처리가 되었습니다.

2022-12-17 10:38 UTC, daepan commented on src/components/Post/Pagination/hooks/usePagination.ts
> +    LIMIT_COUNT,
LIMIT_COUNT에 대해서 훅과 pagination 컴포넌트에서 공유된다고 생각하고 export와 import 하는 과정에서 코드 수정이 제대로 이루저지 않았습니다.
수정해두겠습니다.

2022-12-17 10:46 UTC, daepan commented on src/pages/BoardPage/Notice/hooks/useBoardParams.ts
> +  }, [params, setParams, articleList]);
1. boradId가 없는 경우 페이지네이션에서 현재 페이지에 대한 값을 props가 아닌 setParams로 처리하는 것이 좋을 것 같다고 생각하였습니다. 사용자가 url 파라미터를 통해 현재 페이지에서 어느 부분에 해당하는 페이지를 읽고 있는지 확인도 쉽고, 개발 과정에서도 페이지네이션이 잘 작동하고 있는지 확인하는 것에 대한 이점이 있었습니다.
그렇기에 페이지로 처음 들어올 때 렌더링 과정에서 boardId가 없는 경우 페이지네이션에 NaN요소가 나오게 되어 useEffect를 통해 현재 페이지가 없는 경우 1 페이지를 자동적으로 넣을 수 있도록 하였습니다.

2. 이것 또한 페이지네이션에 대한 관리가 편할 수 있게 해당 방법을 이용하였습니다. 위에 말했듯 개발하는 과정에서도 현재 페이지가 맞게 있는지 확인도 용이했습니다. url parameter를 수정하게 된다는 부분은 생각을 얕게 한 것 같습니다.
props나 recoil을 활용하는 방법으로 수정해보겠습니다.

2022-12-17 10:47 UTC, daepan commented on src/utils/hooks/useParamsHandler.ts
> +      isReplace: boolean,
저는 boolean 값이기에 is~~를 하는 방식의 네이밍을 생각해봤습니다만, 
좀 더 해당 옵션에 대한 기능을 보여줄 수 있는 직관적인 네이밍이 필요하다는 조언으로 생각해도 좋을까요?

2022-12-21 13:37 UTC, daepan commented on src/utils/hooks/useParamsHandler.ts
> +      isReplace: boolean,
일단 말씀하신대로 처리했습니다
[0dd3b37](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/22/commits/0dd3b37ee6d3260c8a8622c5227907094c81e0d6)

2022-12-21 15:42 UTC, ChoiWonBeen requested changes
허걱 페이지네이션에 크리티컬한 문제가 있어 다시 요청드려요.. ㅋㅋㅋ ㅠㅠ

2022-12-21 15:42 UTC, ChoiWonBeen commented on src/components/Post/Pagination/index.tsx
> +};
이 함수의 의도가 정말 좋네요. 그렇지만 여기서 export할 필요는 없을 것 같아요!

2022-12-21 15:42 UTC, ChoiWonBeen commented on src/components/Post/Pagination/index.tsx
> +        onClick={() => setParams('boardId', moveNextNumber(Number(params.boardId) + 1, Number(totalPageNum)), { deleteBeforeParam: false, replacePage: true })}
페이지를 바꾸는데 왜 boardId가 바뀌죠..?
만들어진 의도와 맞지 않는 것 같아요.
`?boardId=1&page=3`같은 구조로 만들어져야하지 않을까요 ㅋㅋ

2022-12-22 01:01 UTC, daepan commented on src/components/Post/Pagination/index.tsx
> +        onClick={() => setParams('boardId', moveNextNumber(Number(params.boardId) + 1, Number(totalPageNum)), { deleteBeforeParam: false, replacePage: true })}
아앗 네이밍에 대한 미스가 있었군요 다시한번 확인하겠습니다

2022-12-22 06:30 UTC, daepan commented on src/components/Post/Pagination/index.tsx
> +        onClick={() => setParams('boardId', moveNextNumber(Number(params.boardId) + 1, Number(totalPageNum)), { deleteBeforeParam: false, replacePage: true })}
boradId의 경우에는 페이지로 분활된 현재 페이지 구조상 필요 없기에 boradId가 page로 변경하였습니다.

2022-12-22 06:31 UTC, daepan commented on src/components/Post/Pagination/index.tsx
> +};
pageNation 훅에서 사용하다 제거했는데 미쳐 수정하지 못했습니다. 제거하겠습니다

2022-12-22 06:32 UTC, daepan commented on src/components/Post/Pagination/index.tsx
> +};
[4fd8eea](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/22/commits/4fd8eea42051b8901979f16dc25fb8fb96aaa3e0)

2022-12-22 09:00 UTC, ChoiWonBeen submitted a review, later dismissed
고생했습니다~

2022-12-27 04:49 UTC, SimYunSup requested changes

2022-12-27 04:49 UTC, SimYunSup commented on src/components/Post/HotPost/index.tsx
> +  if (hotArticleList instanceof Array) {
`useQuery`에는 `isSuccess`로 타입 좁하기가 가능한 것으로 알고 있습니다. 참고해서 바꿔주세요.
https://tkdodo.eu/blog/react-query-and-type-script#type-narrowing

2022-12-27 04:49 UTC, SimYunSup commented on src/components/Post/HotPost/index.tsx
> +              </button>
다른 페이지로 넘어가는 것을 버튼으로 만들 이유가 있을까요?

2022-12-27 04:49 UTC, SimYunSup commented on src/pages/BoardPage/Notice/hooks/usePageParams.ts
> +  }, [params, setParams, articleList]);
이 코드는 없어도 될 것 같네요.

2022-12-27 04:49 UTC, SimYunSup commented on src/components/Post/PostList/index.tsx
> +};
`setDate`이름을 바꾸지 않은 이유라도 있을까요?

2022-12-27 04:49 UTC, SimYunSup commented on src/components/Post/Pagination/index.tsx
> +            <span key={limit + 1}>
`key`가 모두 같습니다.

2022-12-27 04:49 UTC, SimYunSup commented on src/components/Post/HotPost/index.tsx
> +  );
`useQuery`를 hook으로 빼지 않은 이유는 무엇인가요?

2022-12-27 04:49 UTC, SimYunSup commented on src/components/Post/Pagination/index.tsx
> +  }
필요한 구문인가요?

2022-12-27 04:49 UTC, SimYunSup commented on src/components/Post/Pagination/index.tsx
> +        aria-label="page-index-prev"
label 이름은 읽기 가능하도록 만들어야 합니다.

2022-12-27 04:49 UTC, SimYunSup commented on src/pages/BoardPage/Notice/hooks/usePageParams.ts
> +  const articleList = useArticleList(params.page ?? '1');
params중 page를 다루는 hook인데 article을 반환하는 이유가 있나요?

2022-12-27 04:49 UTC, SimYunSup commented on src/pages/BoardPage/Notice/hooks/useArticleList.tsx
> +  }
`data`가 `undefined`가 일때도 넣어서 타입 가드를 지켜주세요.

2022-12-27 04:49 UTC, SimYunSup commented on src/components/Post/Pagination/index.tsx
> +};
`move`라는 이름은 적절하지 않은 것 같습니다.

2023-01-02 11:48 UTC, daepan commented on src/components/Post/HotPost/index.tsx
> +              </button>
button에 대한 onClick 속성을 넣기 위하여 ESLint의 규칙을 생각해서 button태그를 활용하였습니다.

2023-01-02 11:48 UTC, daepan commented on src/components/Post/Pagination/index.tsx
> +            <span key={limit + 1}>
key가 왜 같죠? 각 인수에 대한 값이 다르고 값에 대한 내용이 렌더링되는 것과 일치하는데 왜 같은지 모르겠습니다.

2023-01-02 11:48 UTC, daepan commented on src/components/Post/PostList/index.tsx
> +};
날짜를 지정해준다는 방식이라 큰 어색함이 없어 그대로 두게 되었습니다.
다시 생각해보니 `setDate`보다는 생성된 날짜를 반환해주는 이름의 함수로 변경하겠습니다.

2023-01-02 11:48 UTC, daepan commented on src/pages/BoardPage/Notice/hooks/usePageParams.ts
> +  }, [params, setParams, articleList]);
이 코드가 없으면 pagination이 제대로 돌아가지 않아 필요한 부분입니다.

2023-01-02 11:48 UTC, daepan commented on src/pages/BoardPage/Notice/hooks/usePageParams.ts
> +  const articleList = useArticleList(params.page ?? '1');
article의 반환이기도 하지만 결국에는 해당 리스트를 반환하는 경우가`params`와 함께 이루어져야 한다고 생각해서 params의 조작이 이루어진 다음에 공지사항 리스트를 불러오는 것을 생각하게 되었습니다.
말씀을 들어보니 해당 부분은 네이밍 설계가 이상하군요 수정하겠습니다.

2023-01-02 11:48 UTC, daepan commented on src/components/Post/Pagination/index.tsx
> +  }
꼭 필요한 구문은 아닙니다. 제거하고 다른 식으로 변경하겠습니다

2023-01-02 11:48 UTC, daepan commented on src/components/Post/Pagination/index.tsx
> +};
onHandlePrevPage 식으로 변경하였는데 어떤가요?

2023-01-02 15:19 UTC, daepan commented on src/components/Post/HotPost/index.tsx
> +  );
분리해야했는데 안했군요 훅으로 분리하여 다시 작성하였습니다.
[427a8bf](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/22/commits/427a8bf266d7a8d69559db104caffb14f2d8c6f7)

변경한 방식은 `useHotPost`에서  `React-Query`를 통해 불러온 데이터를 `HotPost`컴포넌트에 넘김으로 출력하는 형식으로 하였습니다.
이런식을 통해 `useHotPost`에서 데이터를 불러왔느냐 아닌가에 대해서 로딩 중일 경우에는 로딩스피너를,
데이터가 있는 경우에는 `HotPost` 컴포넌트를 출력합니다.

2023-01-02 15:19 UTC, daepan commented on src/components/Post/Pagination/index.tsx
> +        aria-label="page-index-prev"
[79d3afe](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/22/commits/79d3afe6c50acf23fdc4251ae201ae98debd13ff)

2023-01-02 15:19 UTC, daepan commented on src/pages/BoardPage/Notice/hooks/usePageParams.ts
> +  const articleList = useArticleList(params.page ?? '1');
[2422a13](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/22/commits/2422a13079e247fa2c4f943eab00affaeacf7833)

2023-01-02 15:20 UTC, daepan commented on src/pages/BoardPage/Notice/hooks/useArticleList.tsx
> +  }
[be801d8](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/22/commits/be801d86ef30a5d6045a441c7c1c0bd4e447a95d)
솔직히 이 부분 어떻게 적용해야할지 몰라서 조건문으로 추가했는데 괜찮나요?

2023-01-02 15:23 UTC, daepan commented on src/pages/BoardPage/Notice/hooks/useArticleList.tsx
> +  }
[db63ba6](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/22/commits/db63ba6afcab2ee58c2590b0400a6a59efac91e3)

2023-01-02 15:24 UTC, daepan commented on src/components/Post/PostList/index.tsx
> +};
[db63ba6](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/22/commits/db63ba6afcab2ee58c2590b0400a6a59efac91e3)

2023-01-02 15:25 UTC, daepan commented on src/components/Post/HotPost/index.tsx
> +  if (hotArticleList instanceof Array) {
훅을 분리하는 과정에서 `isSuccess` 를 활용해서 수정하였습니다. 제가 타입을 잘 좁혔는지에 대한 자신은 없습니다. 한번 확인해주시고 피드백 주시면 감사하겠습니다.
[427a8bf](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/22/commits/427a8bf266d7a8d69559db104caffb14f2d8c6f7)

2023-01-03 00:01 UTC, SimYunSup commented on src/pages/BoardPage/Notice/hooks/useHotPost.tsx
> +  return <LoadingSpinner size="80px" />;
hooks에서 loading스피너를 반환하는 경우는 처음보네요. 다음과 같이 구성한 이유라도 있을까요?

2023-01-03 02:01 UTC, daepan commented on src/pages/BoardPage/Notice/hooks/useHotPost.tsx
> +  return <LoadingSpinner size="80px" />;
Query내에서 값이 도착하는 경우에만 해당 경우를 생각하며 작성하였습니다. 
타입이 정상적인 경우에만 렌더링이 되어 기본적인 반환값을 어떻게 해야할지에 대하 고민하다가 단순하게 생각하면서 작성하였습니다.
성공하면 반환, 아닐 경우에는 로딩 스피너를 반환하자였습니다.

2023-01-03 02:07 UTC, daepan commented on src/components/Post/HotPost/index.tsx
> +        }
그렇군요! 제가 클릭이벤트와 UI가 버튼과 동일하다고 생각하여 해당 방식으로 작성했었습니다. 
말씀하신 내용대로 수정하겠습니다.

2023-01-03 02:34 UTC, daepan commented
https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/22#discussion_r1060213900
해당 리뷰에 대해서 댓글을 달 수 없어 이렇게 답변드립니다. 해당 부분은 제가 에러 콘솔이 찍히지 않아 확인이 어려웠습니다. 당연히 될거라고 생각한 안일함이 있었군요. 해당 부분은 배열을 생성하는 메서드를 통해 배열을 만들어서 하는 방식으로 변경하겠습니다.

2023-01-03 02:41 UTC, daepan commented on src/components/Post/HotPost/index.tsx
> +        }
[6b37d93](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/22/commits/6b37d93b2c8223c7b589345f123d3b48f6de6fef)

2023-01-03 02:41 UTC, daepan commented on src/pages/BoardPage/Notice/hooks/usePageParams.ts
> +};
[7654307](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/22/commits/7654307d5c7ffeb31cae56d3258a84659ea6810b)

2023-01-03 05:43 UTC, SimYunSup approved these changes

2023-01-03 05:43 UTC, merged