[버스 페이지] 상단 카드 영역 및 상태 관리 로직 추가
BCSDLab/KOIN_WEB_RECODE pull request #24
Opened 2022-12-10 12:12 UTC by ChoiWonBeen

## [#23] request

버스페이지 상단 카드 영역을 추가했습니다.
- 메인페이지 영역에서 경로 별 버스 정보를 조회할 것을 대비해 **`[셔틀, 대성, 마을]`** 순으로 출발지(`departList`)와 목적지(`arrivalList`)를 받습니다.
- 최대 1분에 한번씩은 조회하도록 `staleTime`과 `refetchInterval`을 설정했습니다.
- 미운행인 구간에 대해서는 API가 에러를 반환하는데(천안역 -> 야우리 등), 해당 부분은 `remain_time`에 `'미운행'`을 담고 있는 `emptyRouteData`를 반환하도록 만들었습니다. UI를 작성하는 부분에 있어서 편의를 위해 이렇게 작성했는데, 더 나은 방안이 생각난다면 추천 부탁드립니다.

추가로, 글꼴이 정확히 나오지 않고 있는 문제가 있어 `-webkit-font-smoothing: antialiased;`를 전역으로 추가했습니다.

## Please check if the PR fulfills these requirements

- [x] It's submitted to `develop` branch, __not__ the `main` branch
- [x] The commit message follows our guidelines
- [x] There are no warning message when you run `yarn lint`
- [x] Docs updated for breaking changes

### Screenshot

<img width="1167" alt="image" src="https://user-images.githubusercontent.com/50780281/206854306-29af1a58-b7ef-45ad-8a6f-0e5c7842f179.png">

2022-12-14 01:38 UTC, SimYunSup requested changes
한번 더 생각해보면 좋을만한 것들을 리뷰드렸습니다.

2022-12-14 01:38 UTC, SimYunSup commented on src/api/bus/entity.ts
> +  } | null
`BusType`은 따로 타입으로 분리하고 중복되는 next_bus의 객체는 타입으로 분리하지 않은 이유라도 있을까요?

2022-12-14 01:38 UTC, SimYunSup commented on src/pages/BusPage/hooks/useBusLeftTime.ts
> +    queryFn: () => getBusInfo(type, departList[idx], arrivalList[idx]),
해당 함수는 밑과 같이 바꿀 수 있겠네요.
```suggestion
    queryFn: ([_, busType, department, arrival]) => getBusInfo(busType, department, arrival),
```

2022-12-14 01:38 UTC, SimYunSup commented on src/api/bus/entity.ts
> +  }[]
end of line을 통일해주세요. 보통 세미콜론으로 통일하므로 세미콜론으로 지금까지 통일해왔습니다.

2022-12-14 01:38 UTC, SimYunSup commented on src/pages/BusPage/ts/busModules.ts
> +// eslint-disable-next-line consistent-return
eslint를 비활성화 한 이유를 알 수 있을까요?

2022-12-14 04:51 UTC, ChoiWonBeen commented on src/api/bus/entity.ts
> +  }[]
`api/auth/entity.ts`파일을 보고 따라서 작성했는데 해당 파일이 통일되지 않은 부분이었네요. 지금 다른 PR도 올라와있으니 버스 관련 타입만 수정하고 나머지도 한번에 바꿀 필요가 있어보이네요.

2022-12-14 04:53 UTC, ChoiWonBeen commented on src/api/bus/entity.ts
> +  } | null
`BusType`이 다른 파일에서 함수의 인자를 정의하는데 쓰는 타입으로 독립적으로 반복해서 사용되어 분리했습니다. 
`next_bus`와 `now_bus`에서 중복되지만 해당 객체를 벗어나 사용되지 않아 가독성이 더 낫다고 생각했습니다.

2022-12-14 04:56 UTC, ChoiWonBeen commented on src/pages/BusPage/ts/busModules.ts
> +// eslint-disable-next-line consistent-return
처음에 마지막 return문이 없을 때 추가했는데, 막상 로직을 변경하면서 지우지 않았네요. 지우겠습니다.

2022-12-14 05:06 UTC, ChoiWonBeen commented on src/pages/BusPage/hooks/useBusLeftTime.ts
> +    queryFn: () => getBusInfo(type, departList[idx], arrivalList[idx]),
[쩝쩝박사 프로젝트에서 남긴 코멘트](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/42#discussion_r1048010583) 내용과 더불어, queryKey의 타입이 `unknown[]`으로 정해져있어 `string` 타입에 맞출 수 없습니다.
타입 이슈를 해결할 방법이 있을까요?
```tsx
  const queries: UseQueryOptions[] = BUS_TYPES.map((type, idx) => ({
     // ~~~~~~~ 'queryFn' 타입이 올바르지 못함
    queryKey: [BUS_KEY, type, departList[idx], arrivalList[idx]],
    queryFn:
      (
        { queryKey: [busType, department, arrival] }: { queryKey: string[] },
      ) => getBusInfo(busType, department, arrival),
```

2022-12-14 07:22 UTC, SimYunSup commented on src/pages/BusPage/hooks/useBusLeftTime.ts
> +    queryFn: () => getBusInfo(type, departList[idx], arrivalList[idx]),
해당 코멘트 참고해주세요 :)

2022-12-14 08:04 UTC, ChoiWonBeen commented on src/pages/BusPage/hooks/useBusLeftTime.ts
> +    queryFn: () => getBusInfo(type, departList[idx], arrivalList[idx]),
`unknown[]`으로 나오는 문제는 타입을 직접 지정해서 해결할 수 있었네요. 수정했습니다. [c055489](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/24/commits/c0554894e5e3275e777faecfdabf351cc32c75b5)
```tsx
const queries = BUS_TYPES.map<QueryOptions<BusResponse, AxiosError, BusResponse, string[]>>(
```

2022-12-15 16:07 UTC, daepan requested changes
완성도 있고 예쁜 UI이 입니다!
css나 궁금한 점 올려놓았으니 한번 확인해주시고 답변주시면 감사하겠습니다.

2022-12-15 16:07 UTC, daepan commented on src/pages/BusPage/BusLookUp/index.tsx
> +              <div className={styles.cards__content}>
static을 이런식으로 활용해서 반복문에 대한 css 처리가 가능하군요!
한번 저도 적용해보겠습니다 👍

2022-12-15 16:07 UTC, daepan commented on src/pages/BusPage/BusLookUp/index.tsx
> +                  )}
위와 같이 typeof 를 통해 숫자임을 확인하는 이유가 있을까요?
undefined나 다른 렌더링이 발생하나요?

2022-12-15 16:20 UTC, ChoiWonBeen commented on src/pages/BusPage/BusLookUp/BusLookUp.module.scss
> +  }
BEM 표기법을 따랐습니다.
Block__Element--Modifier 구조로, `-`이 두개인 것은 Modifier를 나타냅니다. 블록의 속성을 나타내는 것이죠.
원래라면 `cards__title--bottom`이 각각 cards라는 블록에, title 요소에, bottom속성을 추가했다고 보시면 될 것 같습니다.

`bus-type`이나 `bus-icon`등은 모두 Element를 나타내는데, 띄어쓰기를 표현하기 위해 `-`을 한번 써서 표현했습니다.

2022-12-15 16:40 UTC, ChoiWonBeen commented on src/pages/BusPage/BusLookUp/index.tsx
> +                  )}
조금 특이하지만,`remain_time`이 갖는 타입은 `number | "미운행" | undefined`입니다.
로딩중일 시 undefined, 에러시(경로가 없을 시) 미운행, 값이 있을 시 number라서 해당 조건으로 분기처리했습니다

2022-12-16 00:55 UTC, SimYunSup approved these changes

2022-12-17 08:29 UTC, daepan approved these changes

2022-12-17 08:30 UTC, merged