[식단 상세] 2차스프린트 QA수정사항 반영
BCSDLab/KOIN_WEB_RECODE pull request #241
Opened 2024-05-08 12:13 UTC by KimKyungYun

- Close #216 

## What is this PR? 🔍

- 기능 : QA반영
- issue : 

## Changes 📝

모바일 picker의 UI깨짐과 디자인변경사항에 대한 수정

## ScreenShot 📷

![image](https://github.com/BCSDLab/KOIN_WEB_RECODE/assets/60084235/75a7b565-f610-486f-9f05-c0e9cf0511fc)
![image](https://github.com/BCSDLab/KOIN_WEB_RECODE/assets/60084235/c6ee1e17-6337-4e98-bca7-48eafb746ae8)

## Test CheckList ✅

## Precaution

## Please check if the PR fulfills these requirements

- [ ] It's submitted to `develop` branch, __not__ the `main` branch
- [ ] The commit message follows our guidelines
- [ ] There are no warning message when you run `yarn lint`
- [ ] Docs updated for breaking changes

2024-05-08 15:08 UTC, MinGu-Jeong requested changes

2024-05-08 15:08 UTC, MinGu-Jeong commented on src/pages/Cafeteria/MobileCafeteriaPage/components/WeeklyDatePicker/index.tsx
>                  onClick={() => setDate(day)}
https://github.com/BCSDLab/KOIN_WEB_RECODE/assets/51395707/882bea91-3f65-41ae-a216-fa283a6c0729

오늘 날짜를 한국시간으로 안 받는 문제로 추정됩니다
날짜가 하루씩 밀리는 이슈 수정이 필요해보여요

2024-05-09 00:13 UTC, KimKyungYun commented on src/pages/Cafeteria/MobileCafeteriaPage/components/WeeklyDatePicker/index.tsx
>                  onClick={() => setDate(day)}
useDatePicker로 분리된 로직 중, setDate의 toIsoString에 문제가 있는것 같아서 로직을 수정해서 해결했습니다.

2024-05-09 03:25 UTC, MinGu-Jeong approved these changes
수고하셨습니다!

2024-05-09 06:46 UTC, merged