[버스 페이지] 하단 시간표 영역 및 반응형 UI 추가
BCSDLab/KOIN_WEB_RECODE pull request #26
Opened 2022-12-18 10:55 UTC by ChoiWonBeen

## [#23] request(2)

버스페이지 하단 시간표 영역을 추가하고, 이전 상단 카드 영역까지 반응형 UI를 적용했습니다.

 - `<Suspense />`를 통해 로딩중인 경우 로딩스피너를 출력합니다.
   -  `/assets/svg`폴더를 만들어 해당 파일 추가했습니다.
 - GET: `bus/timetable/` api는 `bus_type`이 `shuttle`이냐, `express`냐에 따라 다른 타입을 반환합니다.
 - 접근성 관련 문제 등을 빠르게 해결하기 위해 native `<select />`태그를 사용했습니다.

## Please check if the PR fulfills these requirements

- [x] It's submitted to `develop` branch, __not__ the `main` branch
- [x] The commit message follows our guidelines
- [x] There are no warning message when you run `yarn lint`
- [x] Docs updated for breaking changes

### Screenshot
![timetable](https://user-images.githubusercontent.com/50780281/208294091-0576d655-0e33-458f-9dd0-ea0578b15850.gif)
<img width="848" alt="image" src="https://user-images.githubusercontent.com/50780281/208294142-0903c6f8-a558-42df-a60e-15f415941cde.png">

2022-12-18 12:25 UTC, daepan requested changes
좋은 래퍼런스가 되는 PR입니다!
앞으로 개발하면서 제 코드에 대한 수정 사항이 보이네요 👍

2022-12-18 12:25 UTC, daepan commented on src/pages/BusPage/BusTimetable/index.tsx
> +      </Suspense>
Suspense를 보니 제가 저번에 처리했던 React-Query의 로딩 방식보다 더 나은 것 같아 보이네요!
이건 앞으로의 코인리코드에서 한번 Suspense로 통일하는 방식으로 하는 작업을 진행해보는게 좋을 것 같네요

2022-12-18 12:25 UTC, daepan commented on src/pages/BusPage/hooks/useBusTimetable.ts
> +const TIMETABLE_KEY = 'timetable';
query key를 상수 처리하는 부분도 한번 적용해봐야겠군요
좋은 레퍼런스가 됩니다!

2022-12-19 00:54 UTC, SimYunSup requested changes

2022-12-19 00:54 UTC, SimYunSup commented on src/pages/BusPage/hooks/useBusTimetable.ts
> +  const [selectedCourseId, handleCourseChange] = useIndexValueSelect();
select를 담당하는 hook을 여기에 둘 이유가 있었을까요?

2022-12-19 00:54 UTC, SimYunSup commented on src/pages/BusPage/hooks/useBusTimetable.ts
> +    queryFn: () => getBusTimetableInfo({ bus_type, direction, region }),
이전에도 말했지만 `context`의 `queryKey`에서 추출해서 사용해주세요.

2022-12-19 00:54 UTC, SimYunSup commented on src/pages/BusPage/BusTimetable/index.tsx
> +      </Suspense>
https://aoa.gitbook.io/skymimo/aoa-2018/2018-aria/tab
tab UI에는 다음과 같은 접근성을 높이면 좋습니다.

2022-12-19 00:54 UTC, SimYunSup commented on src/pages/BusPage/BusTimetable/index.tsx
> +      {timetable?.type === 'shuttle' && (
이 조건부 렌더링을 만든 이유가 알고싶네요.

2022-12-19 08:09 UTC, ChoiWonBeen commented on src/pages/BusPage/BusTimetable/index.tsx
> +      {timetable?.type === 'shuttle' && (
정확히는 `{timetable && timetable.type === 'shuttle'}`이고, 줄여서 표현했습니다.
`timetable`이 가질 수 있는 데이터 타입은 useQuery의 select단에서 결정되는데, info의 타입을 강제하기 위해 `type`필드로 구분했습니다.
```tsx
    select: (response) => {
      if (bus_type === 'express') {
        return {
          info: response as ExpressInfo[],
          type: 'express' as const,
        };
      }
      // bus_type이 'shuttle'인 경우
      return {
        info: response as BusRouteInfo[],
        type: 'shuttle' as const,
      };
    },
```

2022-12-19 09:26 UTC, ChoiWonBeen commented on src/pages/BusPage/BusTimetable/index.tsx
> +      </Suspense>
오 좋은 정보 감사합니다! 열심히 적용해볼게요 😍

2022-12-19 11:14 UTC, ChoiWonBeen commented on src/pages/BusPage/hooks/useBusTimetable.ts
> +    queryFn: () => getBusTimetableInfo({ bus_type, direction, region }),
이게.. 변수명이 겹치는 문제도 있고.. `queryKey`의 타입을 직접 정의해줘야 하는 문제가 있습니다.
그런데 queryKey를 정의하려면 response타입과 함께 select 반환 타입까지 명시해줘야 하는데,
select타입이 `as`를 사용해 직접 명시한 부분이 있어 이를 다 정의하고 쓰자니 너무 가독성을 너무 해치게 됩니다.
```tsx
type BusTimetableInfo = {
  info: ExpressInfo[],
  type: 'express'
} | {
  info: BusRouteInfo[],
  type: 'shuttle',
};

const useBusTimetable = (courseList: readonly Course[]) => {
  const [selectedCourseId, handleCourseChange] = useIndexValueSelect();

  // eslint-disable-next-line @typescript-eslint/naming-convention
  const { bus_type, direction, region } = courseList[selectedCourseId];

  const { data } = useQuery<
  BusTimetableResponse,
  AxiosError,
  BusTimetableInfo,
  ['timetable', CourseBusType, Direction, string]
  >({
    queryKey: [TIMETABLE_KEY, bus_type, direction, region],
    queryFn: (
      { queryKey: [, busType, busDirection, busRegion] },
    ) => getBusTimetableInfo({ bus_type: busType, direction: busDirection, region: busRegion }),
    suspense: true,
    select: (response) => {
      if (bus_type === 'express') {
        return {
          info: response as ExpressInfo[],
          type: 'express' as const,
        };
      }

      return {
        info: response as BusRouteInfo[],
        type: 'shuttle' as const,
      };
    },
  });
```
알아서 추론되는 부분을 포기하면서 이렇게까지 적용할 필요가 있을까 싶어서 생략했는데 어떻게 생각하시나여?

2022-12-19 11:15 UTC, ChoiWonBeen commented on src/pages/BusPage/hooks/useBusTimetable.ts
> +  const [selectedCourseId, handleCourseChange] = useIndexValueSelect();
해당 훅에 관심사가 이상해진 것 같네요. 수정하겠습니다~

2022-12-19 13:14 UTC, ChoiWonBeen commented on src/pages/BusPage/BusTimetable/index.tsx
> +function Timetable({ headers, arrivalList }: { headers: string[], arrivalList: string[][] }) {
공유하는 값과 함수가 꽤 겹치고, 앞으로도 이 파일을 벗어나지 않을 것이라 생각해 이렇게 작성했는데 import가 많아 파일이 지저분해지는 느낌이 있네요. 따로 분리하고 묶어서 관리하는 방식으로 수정했습니다~ [4e5b16d](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/26/commits/4e5b16d4f6017361ede96c9625e941737ac39d4f)
```tsx
      <Suspense fallback={<LoadingSpinner className={styles['template__loading-spinner']} />}>
        {selectedTab.key === 'shuttle' && <Timetable.Shuttle />}
        {selectedTab.key === 'express' && <Timetable.Express />}
        {selectedTab.key === 'city' && <Timetable.City />}
      </Suspense>
```

2022-12-20 00:05 UTC, SimYunSup commented on src/pages/BusPage/hooks/useBusTimetable.ts
> +    queryFn: () => getBusTimetableInfo({ bus_type, direction, region }),
공식 블로그에서 as const를 하면 자동으로 추론된다고 적혀있고, 이를 권장합니다. queryKey를 const로 만들고 자동 추론 기능을 이용하는 것이 어떨까요?
https://tkdodo.eu/blog/leveraging-the-query-function-context

2022-12-20 00:14 UTC, SimYunSup commented on src/pages/BusPage/BusTimetable/index.tsx
> +      {timetable?.type === 'shuttle' && (
제가 질문을 너무 간단하게 한 것 같군요. 제가 묻고싶은 것은 "해당 변수가 어디서 왔는지"가 아니라 "해당 조건부 렌더링은 불필요한 것으로 보이는데 왜 사용했는지"를 물어본 것입니다. `useBusTimetable`에 넘기는 파라미터값으로 이미 `bus_type`이 고정되어있는데 필요한 이유를 찾지 못했기 때문입니다. 만약 데이터가 없을 경우를 고려한거라면 `Suspense`가 처리해줄텐데요.

2022-12-20 00:19 UTC, ChoiWonBeen commented on src/pages/BusPage/hooks/useBusTimetable.ts
> +    queryFn: () => getBusTimetableInfo({ bus_type, direction, region }),
아니 헉 세상에나.. 바로 써서 수정할게요 ㅋㅋㅋㅋ ㅋㅋㅋ

2022-12-20 07:45 UTC, ChoiWonBeen commented on src/pages/BusPage/BusTimetable/index.tsx
> +      {timetable?.type === 'shuttle' && (
hook단에서 타입을 단언해서 data만 사용할 수 있게끔 수정했습니다~ [04ade25](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/26/commits/04ade2508ce0054c20a069767e8ec1523fde34c4)

2022-12-21 08:33 UTC, kimeodml reviewed
코드 너무 깔끔하게 잘 쓰셨어요😳 많이 배워갑니다!!

2022-12-21 08:33 UTC, kimeodml commented on src/static/bus.ts
> +export const CITY_BUS_TIMETABLE = [
버스가 493 급행 버스도 있는데 혹시 추가하실 생각 있나요?

2022-12-22 06:36 UTC, daepan submitted a review, later dismissed

2022-12-22 09:01 UTC, ChoiWonBeen commented on src/static/bus.ts
> +export const CITY_BUS_TIMETABLE = [
아하.. 그버스는 시간이 달라서 테이블을 맞추기 약간 아쉽긴 한데, 번호는 추가해놓으면 좋겠네요

2022-12-22 09:02 UTC, ChoiWonBeen commented on src/static/bus.ts
> +  ['시간표(병천', '6:10(첫) - 22:45(막) (10분간격)'],
헉 바로 수정했습니다

2022-12-23 07:48 UTC, SimYunSup approved these changes

2022-12-23 07:49 UTC, merged