[메인 페이지] 주변식당 카테고리, 버스 컴포넌트 추가
BCSDLab/KOIN_WEB_RECODE pull request #29
Opened 2023-01-22 18:42 UTC by ChoiWonBeen

## [#28] request

메인페이지에 필요한 주변식당 카테고리 목록과, 버스 컴포넌트를 추가했습니다.
메인페이지에 각 컴포넌트에 공간을 할당해두었으니, 추후에 시간표 / 식당 / 공지사항도 추가해주세요.
최대한 기존 페이지에 존재하는 훅과 static 데이터를 활용했고, 이 과정에서 몇가지 리팩토링을 진행했습니다.

- 카테고리에 존재하는 헝가리안 표기법 레거시를 제거했습니다
- 버스 캐러셀 UI 조작 방식을 중복되는 부분만 제거하고 유지했습니다.
- 버스의 상태를 다루는 부분은 최적화를 진행했습니다.
  - 데이터는 `[셔틀, 대성, 시내]` 순서로 가지고있고, 모바일의 경우 UI 표시 순서를 `mobileBusTypes`로 가지고 있고, 동기화를 위해 `matchToMobileType`를 사용해 

## Please check if the PR fulfills these requirements

- [x] It's submitted to `develop` branch, __not__ the `main` branch
- [x] The commit message follows our guidelines
- [x] There are no warning message when you run `yarn lint`
- [x] Docs updated for breaking changes

### Screenshot
<img width="1095" alt="스크린샷 2023-01-23 오전 3 03 10" src="https://user-images.githubusercontent.com/50780281/213932616-a649a587-d000-40fd-8eb4-2a3dbc63ca25.png">

![recodeindex](https://user-images.githubusercontent.com/50780281/213932623-3926b78e-5fe6-4e8d-9648-a4ae9ce95262.gif)

2023-01-23 09:31 UTC, SimYunSup requested changes
고생하셨습니다. 리뷰드린 부분만 수정해주세요.

2023-01-23 09:31 UTC, SimYunSup commented on src/pages/IndexPage/components/IndexBus/hooks/useIndexBusDirection.ts
> +    setToSchoolList(newList);
```suggestion
    setToSchoolList((value) => {
     const newValue = [...value];
     value[index] = !value[index];
     return newValue;
    });
```
으로 외부 변수 참조를 최소화 할 수 있을 것 같습니다.

2023-01-23 09:31 UTC, SimYunSup commented on src/pages/IndexPage/components/IndexBus/hooks/useMobileBusCarousel.ts
> +    const centerPoint = window.innerWidth * 0.625;
`window.innerWidth` 값을 고정하는 것이 맞을까요?

2023-01-23 09:31 UTC, SimYunSup commented on src/pages/IndexPage/components/IndexStore/IndexStore.module.scss
> +    overflow-x: auto;
스크롤이 두개 생깁니다.
![image](https://user-images.githubusercontent.com/47362439/214005091-e62ebbd0-26c1-484f-ae61-9309d1e5652e.png)

2023-01-23 09:31 UTC, SimYunSup commented on src/pages/IndexPage/components/IndexBus/hooks/useMobileBusCarousel.ts
> +      sliderRef.current.addEventListener('touchmove', slideTouchMove);
event listener를 지우는 클린업 함수가 필요해 보입니다.

2023-01-23 09:31 UTC, SimYunSup commented on src/pages/IndexPage/components/IndexBus/hooks/useMobileBusCarousel.ts
> +      }
간단하게 만들 수 있고, else if 를 지양해주세요.

2023-01-24 12:38 UTC, ChoiWonBeen commented on src/pages/IndexPage/components/IndexBus/hooks/useIndexBusDirection.ts
> +    setToSchoolList(newList);
오 좀 더 목적에 알맞네요!
수정했습니다. [7865767](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/29/commits/7865767013da7f725f7e9e241e3fdb184b192f1b)

2023-01-24 12:47 UTC, ChoiWonBeen commented on src/pages/IndexPage/components/IndexBus/hooks/useMobileBusCarousel.ts
> +    const centerPoint = window.innerWidth * 0.625;
최초 이벤트리스너 할당 이후 갱신될 필요가 없다고 생각했었는데, 화면 사이즈가 유동적으로 변할 때를 다뤄보니 카드의 이동이 생각한거랑 다르게 이동하네요. 반복이 많지도 않으니 그냥 전부 할당된 값으로 바꾸겠습니다.

2023-01-24 12:48 UTC, ChoiWonBeen commented on src/pages/IndexPage/components/IndexBus/hooks/useMobileBusCarousel.ts
> +      }
불필요한 조건이 껴있었네요. 맞춰서 수정했습니다. [f5aafb6](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/29/commits/f5aafb6a9b5896422fd416504784c42498617067)
```tsx
    const stopSlide = () => {
      if (sliderRef.current) {
        sliderRef.current.scrollLeft = window.innerWidth * 0.625;
        if (walk < -120) {
          setMobileBusTypes((state) => [state[2]].concat(state.slice(0, 2)));
        }
        if (walk > 120) {
          setMobileBusTypes((state) => state.slice(1, 3).concat(state[0]));
        }
      }
      walk = 0;
    };
```

2023-01-24 13:21 UTC, ChoiWonBeen commented on src/pages/IndexPage/components/IndexBus/hooks/useMobileBusCarousel.ts
> +      sliderRef.current.addEventListener('touchmove', slideTouchMove);
`sliderRef.current`가 cleanup 시점과 effect실행 시점에서 바뀔 수 있다는 에러가 나길래 "어차피 빈배열이니깐" 하고 넘어갔었는데, effect내부에서 `sliderRef.current`를 복사하니 문제가 해결되네요.

그런데 그 과정에서 엄청난 버그를 마주쳤는데, React18버전의 StrictMode에서 effect가 두 번씩 실행돼서 넘기는 로직이 두번씩 들어가고 있었네요 ㅋㅋㅋㅋ  그래서 오른쪽으로 옮기는 로직이 (왼쪽 + 왼쪽) 으로 동작하고 있어 이것도 같이 고쳤습니다.[8facb8d](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/29/commits/8facb8d76a81d774322cec7bbd9b3fea984c6ffc)

2023-01-24 13:33 UTC, ChoiWonBeen commented on src/pages/IndexPage/components/IndexStore/IndexStore.module.scss
> +    overflow-x: auto;
저게 왜 생기나 했더니, `width: 100%`와 내부 padding이 겹쳐서 생기는 문제였네요.
`box-sizing: border-box`를 추가해서 width를 맞추고, 기존 스크롤바는 유지했습니다. [2a1ccca](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/29/commits/2a1cccac91d66f5ade1f46113d588e24003a6078)

2023-01-25 03:21 UTC, SimYunSup approved these changes

2023-01-30 03:45 UTC, merged