[공지사항]공지사항 상세 페이지 + 반응형 세팅
BCSDLab/KOIN_WEB_RECODE pull request #30
Opened 2023-01-23 19:21 UTC by daepan

## [#27] request
공지사항 상세페이지 작성 및 반응형 웹 스타일 작성하였습니다.
공지사항에 대한 페이지에 대한 로딩 방식을 변경하였습니다. 
router의 경우
Notice (공지사항 헤더와 인기 글등 공통 렌더링컴포넌트들)
ㄴ NoticePage (공지사항 리스트)
ㄴ NoticeDetailPage (공지사항 상세)
식으로 변경하였습니다.

id를 통해서 불러오는 api를 추가하였고 해당 로딩에 대한 suspense를 적용하였습니다. 알맞게 적용되었는지 한번 봐주세요.

## Please check if the PR fulfills these requirements

- [ ] It's submitted to `develop` branch, __not__ the `main` branch
- [ ] The commit message follows our guidelines
- [ ] There are no warning message when you run `yarn lint`
- [ ] Docs updated for breaking changes

### Screenshot
<img width="493" alt="스크린샷 2023-01-24 오전 4 13 01" src="https://user-images.githubusercontent.com/50792467/214130346-28639e8f-d6c8-4067-bf49-f367660ced23.png">
<img width="484" alt="스크린샷 2023-01-24 오전 4 12 47" src="https://user-images.githubusercontent.com/50792467/214130351-59bc48af-0cd3-48ea-9a90-65cc7876915b.png">
<img width="1229" alt="스크린샷 2023-01-24 오전 4 13 13" src="https://user-images.githubusercontent.com/50792467/214130409-c55f4d9e-1f3a-4012-910d-cdc58f587b9f.png">

2023-01-24 15:53 UTC, ChoiWonBeen requested changes
고생하셨어요~ 눈에 띄는 문제들을 먼저 확인했으니 이 부분 고쳐지고 나면 다시 자세히 리뷰할게요!

2023-01-24 15:53 UTC, ChoiWonBeen commented on src/components/Post/PostDetail/PostDetailHeader/PostDetailHeader.module.scss
> +  border-top: 2px solid #175c8e;
헤더가 둥글어서 이 상단 선이 엄청 불편하게 보이는데, 헤더를 하루빨리 수정해야겠네요 ㅋㅋ 
<img width="426" alt="image" src="https://user-images.githubusercontent.com/50780281/214333112-1146889c-16a2-4c4a-b600-b03b46b4c105.png">
<img width="434" alt="image" src="https://user-images.githubusercontent.com/50780281/214333172-56cbd574-d807-433f-aa31-b6652cc03874.png">

2023-01-24 15:53 UTC, ChoiWonBeen commented on src/pages/BoardPage/Notice/NoticeDetailPage/index.tsx
> +      />
타입 단언보다는 해당 데이터가 있을 때 렌더링 하는건 어떨까요? 전 그렇게 했었어요.
```suggestion
    <div>
      {articleDetail && (
      <>
        <PostDetailHeader
          boardId={articleDetail.board_id}
          title={articleDetail.title}
          createdAt={articleDetail.created_at}
          commentCount={articleDetail.comment_count}
          nickname={articleDetail.nickname}
          hit={articleDetail.hit}
        />
        <PostDetailContent
          content={articleDetail.content}
        />
      </>
      )}
    </div>
```

2023-01-24 15:53 UTC, ChoiWonBeen commented on src/pages/BoardPage/Notice/NoticeDetailPage/index.tsx
> +        content={articleDetail!.content}
props가 너무 많이 생겨서 결합이 너무 강해진 것 같은데...
차라리 `PostDetailHeader`와 `PostDetailContent` 내부에서 각각 `useArticleDetail`을 호출하는게 어떨까요?
쿼리키가 같으면 캐싱되니 성능상 문제는 적을거예요.

2023-01-24 15:53 UTC, ChoiWonBeen commented on src/components/Post/utils/setPostCreateDate.ts
> +  return [`${created}`, false];
배열을 그대로 출력해서 `[2023, 1, 23]` 형태 값이 그대로 변경되어 목록에서 날짜가  `.`이 아닌 `,`으로 찍히는 문제가 있어요.
월, 일 표현에도 `padStart(2, '0')` 과정이 빠진 것 같네요.

2023-02-01 15:40 UTC, daepan commented on src/components/Post/PostDetail/PostDetailHeader/PostDetailHeader.module.scss
> +  border-top: 2px solid #175c8e;
헤더는 다음 기회에...

2023-02-01 15:58 UTC, daepan commented on src/components/Post/utils/setPostCreateDate.ts
> +  return [`${created}`, false];
해결은 했습니다.
![image](https://user-images.githubusercontent.com/50792467/216095376-aba569bd-05f9-4583-b304-6f84166624d4.png)

2023-02-01 16:03 UTC, daepan commented on src/pages/BoardPage/Notice/NoticeDetailPage/index.tsx
> +        content={articleDetail!.content}
흠,, 제생각에는 결합이 강해지는 것도 있지만 코드를 그렇게 두번써서 쿼리를 두번 넘기는거랑 그닥 다를 거 없다고 생각은 합니다.
제 생각이지만 결국 props에 대해서는 그닥 다를 것이 없다고 생각합니다. 상세페이지에 대한 헤더가 직접 변경되지 않는 이상 큰 일 없을 것 같습니다.

2023-02-04 15:32 UTC, daepan commented on src/components/Post/PostDetail/PostDetailHeader/PostDetailHeader.module.scss
> +  border-top: 2px solid #175c8e;
[4ae0f45](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/30/commits/4ae0f455008c085c886b2e462e73a56ec9c84fff)ㅁ
밑줄 제거랑 아래 줄 색깔 바꿧습니다

2023-02-04 15:32 UTC, daepan commented on src/pages/BoardPage/Notice/NoticeDetailPage/index.tsx
> +      />
[c3ace06](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/30/commits/c3ace064f57ce9eb95365606eacac21a4b0ec6dd)
제안해주신대로 변경 완료했습니다

2023-02-04 15:33 UTC, daepan commented on src/components/Post/utils/setPostCreateDate.ts
> +  return [`${created}`, false];
[a0dc301](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/30/commits/a0dc301f7dcea2183a519fb5493aee458101c391)
padStart는 굳이 필요하지는 않았고 배열에서 . 으로 구분하도록 join()메서드 활용했습니다

2023-02-18 07:21 UTC, ChoiWonBeen commented on src/pages/BoardPage/Notice/hooks/useArticleDetail.ts
> +    ['articleList', id],
해결해주세요! @daepan

2023-02-23 14:14 UTC, ChoiWonBeen approved these changes
남은 부분은 다음 브랜치에서 처리해도 될 것 같네요. 고생하셨어요~

2023-03-01 09:34 UTC, merged