[시간표] 시간표 메인페이지 구현
BCSDLab/KOIN_WEB_RECODE pull request #306
Opened 2024-06-07 01:36 UTC by Gwak-Seungju

- Close #295 
  
## What is this PR? 🔍

- 기능 :  시간표 메인페이지  UI 완성
- issue : #295 

## Changes 📝

- 시간표 메인페이지 UI를 구현했습니다.
- 학기 드롭다운 구현
- 커리큘럼 드롭다운 구현
- 버튼 스타일 개선
- 학기, 시간표 설정 모달 구현
- 시간표 디자인 변경

**미 구현 로직 - 아직 API 생성이 되지 않아 다음에 구현 가능한 로직들입니다.**
- 학기, 시간표 추가 이벤트
- 기본 학기, 시간표 설정
- 학기, 시간표 삭제, 저장 이벤트

## ScreenShot 📷

![image](https://github.com/BCSDLab/KOIN_WEB_RECODE/assets/74342515/3ce0a88c-2140-46ab-8ac9-c99ad9b3c0d2)
![image](https://github.com/BCSDLab/KOIN_WEB_RECODE/assets/74342515/8fc4f0d0-4c16-4eb2-afb9-1b551acb1d9f)
![image](https://github.com/BCSDLab/KOIN_WEB_RECODE/assets/74342515/37e0ab5e-b80a-484b-bec6-6809a078b0ff)
![image](https://github.com/BCSDLab/KOIN_WEB_RECODE/assets/74342515/923996ae-5c89-47f6-abd3-c63d12686bae)

## Test CheckList ✅

## Precaution

## ✔️ Please check if the PR fulfills these requirements

- [ ] It's submitted to the correct branch, not the `develop` branch unconditionally?
- [ ] If on a hotfix branch, ensure it targets `main`?
- [ ] There are no warning message when you run `yarn lint`

2024-06-08 05:32 UTC, haejinyun requested changes
마이그레이션 하면서 봤던 시간표보다 정말 많이 예뻐졌네요!!

몇가지 궁금한 점과 개선 방향에 대해서 적어보았습니다!
처음 코인 유저를 참여하게 되어 제가 아직 파악하지 못한 부분도 있을 것 같네요.
리뷰 중 어색한 부분이 있다면 말씀해주세요!

수고하셨습니다!

2024-06-08 05:32 UTC, haejinyun commented on src/pages/Timetable/components/Curriculum.tsx
> +        </ul>
```ts
        <div className={styles['select__curriculum-list']} role="listbox">
          {list.map((dept) => (
            <a
              href={dept.curriculum_link}
              target="_blank"
              rel="noreferrer"
              onClick={onClickOption}
            >
              <span
                className={styles.select__curriculum}
                key={dept.name}
                role="option"
                aria-selected="false"
                data-value={dept.name}
                tabIndex={0}
              >
                {dept.name}
              </div>
            </a>
          ))}
          <div className={styles.select__curriculum}>
            <a
              href="https://www.koreatech.ac.kr/board.es?mid=a10103010000&bid=0002"
              target="_blank"
              rel="noreferrer"
            >
              대학 요람
            </a>
          </div>
        </div>
```

2024-06-08 05:32 UTC, haejinyun commented on src/pages/Timetable/components/Curriculum.tsx
> +        </ul>
저는 이런식으로 생각을 해봤습니다!
현재 eslint 에러가 나고 있는 부분은 li요소에 onClick이 들어가 있어 키보드 제어의 순간의 로직 처리가 필요하다고 하는 것이라고 하네요...! 

ul와 li가 아닌 div로 사용해서 전체를 묶고 내부 요소 또한 div로 관리하지만 각각 요소들에 a태그로 묶어주어 링크 제어로 구성해보았습니다. ul+li, div는 개인 취향 차이라고도 생각이 되네요. 
그런데 보통 a태그로는 링크 관리만 해주며 a태그 내부에서 div or span 태그를 활용해서 요소를 분리해주는 경우가 많더라구요! ex) 네이버, 오늘의 집 

또한 li에 있던 onClick을 a태그 쪽으로 옮겨주어 eslint에러를 지울 수  있었습니다!

개인적인 팁으로는 html 요소를 구성할 때 다른 대형 사이트를 비교해보며 참고하면 흐름을 잡기 편하더라구요!

2024-06-08 05:32 UTC, haejinyun commented on src/pages/Timetable/components/TimetableList/index.tsx
> +          <div className={styles['timetable-list__list--item']}>
이후 api 세팅 후 key 설정이 필요할 것 같습니다!

2024-06-08 05:32 UTC, haejinyun commented on src/pages/Timetable/components/SemesterList/index.tsx
> +  });
해당 부분이 Listbox, SemesterListbox, CurriculumListBox등에서 중복되어 사용되고 있는 것 같아요.
기능적으로 요구하는게 외부 영역 클릭시 팝업이 닫히는 기능 등과 관련 된 것 같은데 커스텀 훅과 같이 분리해서 공용으로 사용할 수 있게 수정하면 좋을 것 같습니다!

2024-06-08 08:08 UTC, Gwak-Seungju commented on src/components/TimetablePage/Listbox/index.tsx
> +  version?: 'default' | 'new' | 'new_2';
따로 피그마에서 아카이빙된 건 아닙니다.
새로운 버전을 추가한 이유는 `Listbox` 컴포넌트와 같은 용도로 사용되지만,  드롭다운을 펼쳤을 때 기존 `Listbox`와 스타일이 달라져서 추가하게 되었습니다. 따라서 네이밍도 임시로 하였는데, 이런 경우에는 네이밍을 어떤 식으로 하면 좋을까요?! 아니면 새로운 버전을 추가할 필요없이 스타일 속성을 바꿀 수 있을까요?!

2024-06-08 08:14 UTC, Gwak-Seungju commented on src/components/TimetablePage/Listbox/index.tsx
> +            <div>
수정했습니다! e06a5ad021dfe44a51869f964467faa65dfc55e8

2024-06-08 08:50 UTC, Gwak-Seungju commented on src/pages/Timetable/components/Curriculum.tsx
> +        </ul>
li 요소에 onClick이 들어가 있어서 eslint 에러가 발생한 것이었군요! 조언해주신 부분 반영했습니다! ace8bcd2a72de1bec20e7ba97f8d7a084fb218b8

2024-06-08 10:27 UTC, Gwak-Seungju commented on src/pages/Timetable/components/TimetableList/index.tsx
> +          <div className={styles['timetable-list__list--item']}>
반영했습니다! 95e4fec8cfa6a25aa69a3d14baedec31edebe241

2024-06-08 11:21 UTC, Gwak-Seungju commented on src/pages/Timetable/components/Curriculum.tsx
> +        </ul>
밑에 리뷰에서  `onKeyPressOption`  처리를 위해 코드를 다시 보다가 eslint룰을 다시 보게 되었는데 `div`나 `li`와 같은 `non-interactive element`에 `onClick`을 넣으면 적어도 하나의 `keyboard listener`가 필요하다고 하네요! 그래서 생긴 lint 에러인 것 같습니다..!

2024-06-08 11:36 UTC, Gwak-Seungju commented on src/pages/Timetable/components/SemesterList/index.tsx
> +  });
- `handleClickOutside` 경우에는 이미 custom hook으로 `useOnClickOutside`라고 지정된 것이 있어 그 훅을 사용했습니다.

`onKeyPressOption`의 경우에는 위에서 eslint 에러와 관련해 리뷰해주신 부분과 연관이 있습니다!
`onClick`을 사용하면서 eslint 에러 때문에 `onKeyPress`까지 사용하게 된 것인데 `onKeyPress`를 사용하려고 보니 `deprecated`하다며 취소선이 되어 있었습니다. 
- 그래서 아예 없애도 된다 판단하여 `onKeyPressOption` 함수를 없앴습니다.
- 그리고 `div` 대신 `iteractive element`인  `button` 을 사용했습니다.

adbf3cd7c871607a21eb405d96ae4c4f3c70ca10

2024-06-10 05:33 UTC, haejinyun commented on src/components/TimetablePage/Listbox/index.tsx
> +  version?: 'default' | 'new' | 'new_2';
버전으로 관리를 하는 것도 나쁘지는 않지만, 이후 드롭다운이라는 역할은 동일하지만, 다양한 형태의 ui로 해당 기능을 가지게 된다면 그때마다 version이 늘어나야할 것입니다. 그 문제와 관련해서는 아래 영상을 추천드립니다!
https://www.youtube.com/watch?v=fR8tsJ2r7Eg
이전에 드롭다운을 추상적으로 구현할 때 추천 받았던 영상인데 정말 도움이 많이 되었습니다!

만약 버전으로 관리하게 된다면 해당 **ui의 특징을 담은 네이밍**을 지어보는 것은 어떨까 싶습니다.
trigger 섹션과 떨어져 있다라는 느낌을 담에 space라는 의미를 담거나 장기적으로 본다면 디자인 팀과 이야기를 나누어 해당 디자인은 modal에서만 쓰인다라는 등의 디자인 시스템이 정의된다면 modal listBox 등의 네이밍은 어떨까 싶습니다.

2024-06-10 05:38 UTC, haejinyun commented on src/components/TimetablePage/Listbox/index.tsx
> +  version?: 'default' | 'new' | 'new_2';
버전으로 관리를 하는 것도 나쁘지는 않지만, 이후 드롭다운이라는 역할은 동일하지만, 다양한 형태의 ui로 해당 기능을 가지게 된다면 그때마다 version이 늘어나야할 것입니다. 그 문제와 관련해서는 아래 영상을 추천드립니다!
https://www.youtube.com/watch?v=fR8tsJ2r7Eg
이전에 드롭다운을 추상적으로 구현할 때 추천 받았던 영상인데 정말 도움이 많이 되었습니다!

만약 버전으로 관리하게 된다면 해당 ui의 특징을 담은 네이밍을 지어보는 것은 어떨까 싶습니다.
trigger 섹션과 떨어져 있다라는 느낌을 담에 space라는 의미를 담거나 장기적으로 본다면 디자인 팀과 이야기를 나누어 해당 디자인은 modal에서만 쓰인다라는 등의 디자인 시스템이 정의된다면 modal listBox 등의 네이밍은 어떨까 싶습니다.

2024-06-13 12:04 UTC, Gwak-Seungju commented on src/components/TimetablePage/Listbox/index.tsx
> +  version?: 'default' | 'new' | 'new_2';
반영했습니다!! 91a9cd59ef81e595f94b3a415a55339b6bbdb268

2024-06-13 12:07 UTC, merged