[시간표] 직접 추가 UI 구현
BCSDLab/KOIN_WEB_RECODE pull request #325
Opened 2024-06-26 06:15 UTC by haejinyun

- Close #ISSUE_NUMBER
  
## What is this PR? 🔍

- 기능 : 시간표 수정 내부 직접 추가의 UI를 구현하였습니다.
- issue : #319 

## Changes 📝

* 직접 추가 UI를 구현하였습니다.
* API 요청 구조에 따라 UI 작업에 대한 구조가 변경될 가능성이 높습니다.

## ScreenShot 📷

![image](https://github.com/BCSDLab/KOIN_WEB_RECODE/assets/86779590/f06eec6d-66c7-425f-a76b-4b8664169824)
![image](https://github.com/BCSDLab/KOIN_WEB_RECODE/assets/86779590/11f162b6-2aa3-4007-98a2-dccac186fe00)
![image](https://github.com/BCSDLab/KOIN_WEB_RECODE/assets/86779590/76cf2847-7af0-42ff-9bf0-9f74de0bdf17)

## Test CheckList ✅

## Precaution
* 현재 API 명세가 없어 시간표 저장 요청이 담기는 구조를 파악하기 어려워 임의로 form 구조를 만들어 놓았습니다. 이후 api 명세를 확인하여 구조 및 [시간 및 장소 추가] 기능의 연장 개발이 필요합니다.
 
## ✔️ Please check if the PR fulfills these requirements

- [x] It's submitted to the correct branch, not the `develop` branch unconditionally?
- [x] If on a hotfix branch, ensure it targets `main`?
- [x] There are no warning message when you run `yarn lint`

2024-06-26 06:40 UTC, Gwak-Seungju reviewed
정말 수고하셨습니다!! 제 생각 몇 가지 적어보았습니다!

2024-06-26 06:40 UTC, Gwak-Seungju commented on src/components/TimetablePage/Listbox/NewListbox.module.scss
> +    &--selected-add-lecture {
> &--selected-add-lecture {
      color: #000;
    }
    
 145-147 줄과 동일한 클래스인 것 같아 하나로 합치는 것이 좋을 것 같습니다!

2024-06-26 06:40 UTC, Gwak-Seungju commented on src/pages/Timetable/components/CustomLecture/index.tsx
> +        <input type="text" name="professorName" placeholder="수업명을 입력하세요." />
placeholder에 `"교수명을 입력하세요."` 가 맞는 것 같습니다!

2024-06-26 06:40 UTC, Gwak-Seungju commented on src/pages/Timetable/components/CustomLecture/index.tsx
> +const MIN = [{ label: '00분', value: '00분' },
정말 사소한 것일 수 있는데, 저는 처음에 봤을 때 `MINIMUM`의 `MIN`으로 봐서 `MINUTE`으로 명확하게 표현하는 것도 좋을 것 같습니다!

2024-06-26 10:11 UTC, dooohun requested changes
팀 들어와서 처음 작성하는 코드라 조금 힘드셨을 것 같은데 고생 많으셨습니다!
좀 더 기능 구현이 필요해 보이는 부분이 있어서 필요한 부분 리뷰 작성했습니다~

2024-06-26 10:11 UTC, dooohun commented on src/pages/Timetable/components/CustomLecture/index.tsx
> +
이런 상수들은 `static/timetable.ts`에 관리하거나 아예 새로 만들어서 관리하면 좋을 것 같아요!

2024-06-26 10:11 UTC, dooohun commented on src/pages/Timetable/components/CustomLecture/index.tsx
> +// import { cn } from '@bcsdlab/utils';
필요없으면 삭제하는 것도 괜찮을 것 같아요!

2024-06-26 10:11 UTC, dooohun commented on src/pages/Timetable/components/CustomLecture/index.tsx
> +      </button>
이거 기능 구현은 아직 안된건가요?

2024-06-26 10:11 UTC, dooohun commented on src/pages/Timetable/components/CustomLecture/index.tsx
> +                <button type="button" className={styles['form-group-time__weekdays-button']}>{weekday}</button>
버튼 클릭 했을 때 배경색이랑 글자가 변경되어야 할 것 같아요! 현재 클릭 만 되고 따로 기능구현이 안되어 있어요!

2024-06-26 10:11 UTC, dooohun commented on src/pages/Timetable/components/CustomLecture/index.tsx
> +              <Listbox list={MIN} value="00분" onChange={onChangeMin} version="addLecture" />
아직 api가 나오지는 않았지만, value, onChangeHours는 구현 가능할 것 같은데 어떻게 생각하시나요?

2024-06-26 17:47 UTC, haejinyun commented on src/components/TimetablePage/Listbox/NewListbox.module.scss
> +    &--selected-add-lecture {
74줄은 __trigger하위의 요소이고 145줄은 __option 관련 요소로 다른 css를 가지고 있습니다!

2024-06-26 17:48 UTC, haejinyun commented on src/pages/Timetable/components/CustomLecture/index.tsx
> +        <input type="text" name="professorName" placeholder="수업명을 입력하세요." />
오타가 있었네요 감사합니다!ㅠㅠ

2024-06-26 17:52 UTC, haejinyun commented on src/pages/Timetable/components/CustomLecture/index.tsx
> +
해당 부분이 api로 오는지 직접 구현인지 아직 모르겠어 임의로 작성해두었습니다! 
그래도 static으로 옮겨 작성하는 편이 좋아보이는 군요.. 앞으로 해당 부분 인지해두겠습니다!

2024-06-26 18:01 UTC, haejinyun commented on src/pages/Timetable/components/CustomLecture/index.tsx
> +      </button>
해당 부분에 대해서 고민이 많이되네요... 
api 구조를 받아봐야 생각이 잘 잡힐 것 같은데 `시간 및 장소 추가`섹션을 따로 컴포넌트화 시키는 것은 좋은 생각인 것 같아요! 
추가 기능이 있는 부분에서도 더 좋아보이네요! 해당 부분 빠르게 수정해서 커밋 추가하겠습니다!

2024-06-26 18:04 UTC, haejinyun commented on src/pages/Timetable/components/CustomLecture/index.tsx
> +                <button type="button" className={styles['form-group-time__weekdays-button']}>{weekday}</button>
다중 입력을 받는 부분이라 어떤 식으로 api 요청이 들어올지 몰라 후순위로 두었습니다. 
1차적으로 문자열 리스트로 생각하고 구현해보겠습니다! 이것도 빠르게 수정하여 추가 커밋 하겠습니다!

2024-06-26 18:04 UTC, haejinyun commented on src/pages/Timetable/components/CustomLecture/index.tsx
> +              <Listbox list={MIN} value="00분" onChange={onChangeMin} version="addLecture" />
이전에 시간을 담아 보내던 api 구조 파악 후 비슷한 결로 구현해보겠습니다!

2024-06-27 09:15 UTC, haejinyun commented on src/pages/Timetable/components/CustomLecture/index.tsx
> +      </button>
65f03903e3fc33b136367f17afe938198d353d16
말씀해주신 부분과 함께 구조를 조금 변경해보았습니다.
각 컴포넌트의 상태 즉 입력 값은 상태 객체를 하나 두어 관리 할 예정입니다.

2024-06-27 09:16 UTC, haejinyun commented on src/pages/Timetable/components/CustomLecture/index.tsx
> +                <button type="button" className={styles['form-group-time__weekdays-button']}>{weekday}</button>
1c5c19f7eb042493f8c318d851f58bc33918b638
문자열 배열에 요일이 ['월', '화'] 이렇게 들어가는 형식으로 구현하였습니다.
임의로 만들어 둔 것이라 api 확인 후 수정 가능성이 높습니다.

2024-06-27 09:19 UTC, haejinyun commented on src/pages/Timetable/components/CustomLecture/index.tsx
> +              <Listbox list={MIN} value="00분" onChange={onChangeMin} version="addLecture" />
cebd692f605bbc9a5c0f65db979175de7d78e8eb
이전에 비슷한 구조를 찾기 어려워 임의로 객체상태 `startHour(시작시), startMinute(시작분), endHour(종료시), endMinute(종료분) `를 만들어 구현하였습니다. 이도 api 구조 파악 후 수정 가능성이 높습니다

2024-06-27 10:29 UTC, dooohun approved these changes
정말 수고많으셨습니다~

2024-06-27 11:51 UTC, merged