[복덕방] 복덕방 메인 페이지 작성
BCSDLab/KOIN_WEB_RECODE pull request #34
Opened 2023-03-12 08:32 UTC by kimeodml

## [#32] request

 복덕방 페이지 생성 완료했습니다.
- 이전 디자인의 월세에서 텍스트가 넘치면 스타일이 깨지는 오류가 발생했는데 텍스트가 넘치면 말줄임표를 생성하도록 추가했습니다.

## Please check if the PR fulfills these requirements

- [x] It's submitted to `develop` branch, __not__ the `main` branch
- [x] The commit message follows our guidelines
- [x] There are no warning message when you run `yarn lint`
- [x] Docs updated for breaking changes

### Screenshot

2023-03-12 10:18 UTC, daepan requested changes
일단 전체적으로 간단하게 살펴봤습니다. 
수정사항 한번 확인해주시고 수정해주세요.

2023-03-12 10:18 UTC, daepan commented on src/pages/Room/RoomPage/RoomPage.module.scss
> +
![image](https://user-images.githubusercontent.com/50792467/224537790-f52da1ee-ba69-4fdb-a238-81735afd5ff6.png)
![image](https://user-images.githubusercontent.com/50792467/224537792-c05bed69-334f-409a-ba2b-fffbf889360b.png)
두 페이지의 UI가 조금 맞지 않는 것 같네요. 하단맞춰서 수정 부탁드립니다.

2023-03-12 10:18 UTC, daepan commented on src/pages/Room/RoomPage/component/MarkerIcon.tsx
> +export default MarkerIcon;
따로 컴포넌트파일이 있는데 그곳에 같이 두면 좋을 것 같습니다.

2023-03-12 10:18 UTC, daepan commented on src/pages/Room/RoomPage/index.tsx
> +  const navermaps = useNavermaps();
```suggestion
  const naverMaps = useNavermaps();
```
camelCase를 지켜주세요

2023-03-12 10:18 UTC, daepan commented on src/pages/Room/RoomPage/index.tsx
> +                </div>
요것도 컴포넌트 분할이 가능하지 않을까요?

2023-03-12 10:18 UTC, daepan commented on src/pages/Room/RoomPage/index.tsx
> +                }}
요거 혹시 모르고 사용하셨다면, 한번 알아보고 가도 좋을것 같네요

2023-03-12 10:37 UTC, ChoiWonBeen commented on src/api/room/entity.ts
> +  created_at: string,
API Response로 `Date`객체가 들어오진 않고 `2021-01-01` 형태일 것 같지 않나여?

2023-03-12 10:48 UTC, daepan commented on src/api/room/entity.ts
> +  created_at: string,
확인해보니깐 해당 형태이긴한데 문자열로 new Date 생성도 가능해서 Date 타입으로 해도 괜찮을 것 같은데요?

2023-03-12 11:38 UTC, SimYunSup requested changes

2023-03-12 11:38 UTC, SimYunSup commented on src/pages/Room/RoomPage/component/MarkerIcon.module.scss
> +/* stylelint-disable scss/double-slash-comment-empty-line-before */
lint를 비활성화 했으면 이유도 함께 적어주세요.

2023-03-12 11:51 UTC, ChoiWonBeen commented on src/api/room/entity.ts
> +  created_at: string,
그 Date가 `new Date()` 생성자를 써서 나오는 클래스를 설명하는 타입으로 알고있었는데 아니었나요??
```ts
const date: Date = new Date() // ok
const dateString: Date = '2021-01-01' // error!
```

2023-03-14 06:48 UTC, SimYunSup commented
![Screenshot_20230314_154113_Parallels Access](https://user-images.githubusercontent.com/47362439/224917173-5ae1071c-3aed-4663-a6ca-9940cf54def0.jpg)

위 사진을 보면 react-dom-server가 꽤 많은 부분을 차지하는 것을 확인할 수 있습니다(react-dom.production.min.js 옆 두 공간). 그리고 react-naver-maps로 import한 lodash 패키지 + react-naver-maps(react-toastify.esm.mjs 밑에 있습니다)가 react-toastify보다 큰 것을 확인할 수 있습니다. 이는 지정한 패키지 이외의 서드 파티 패키지를 쓰지 않는 방식으로 번들 사이즈를 줄이려던 노력을 무시하는 결과가 될 수도 있습니다. 이를 통해서 패키지를 추가할 때에는 주의를 기울여서 추가해주시길 바랍니다.

여담으로 recoil이 꽤 무겁네요.

2023-03-15 09:34 UTC, ChoiWonBeen requested changes
고생하셨어요~ 몇가지 사소한 변경점 보이는것들 리뷰했는데 남은 부분 확인해서 올려주세여
아마 `react-naver-map`패키지 제거하고나면 다시 리뷰해야할거같으니 그때 더 자세히 볼게요!

2023-03-15 09:34 UTC, ChoiWonBeen commented on src/pages/Room/RoomPage/index.tsx
> +  Container as MapDiv, NaverMap, useNavermaps, Marker,
`MapDiv`? 보다는 `MapContainer`가 더 적절해 보이는데 어떤가요?

2023-03-15 09:34 UTC, ChoiWonBeen commented on src/pages/Room/RoomPage/hooks/useRoomList.ts
> +    },
room 목록을 가져오는 이 함수가 특별하게 `retry: 0`을 가져야 하는 이유가 있나요?? 궁금

2023-03-15 09:34 UTC, ChoiWonBeen commented on src/pages/Room/RoomPage/index.tsx
> +            <div className={styles.list__box} key={room.id}>
지금은 `div` + `cursor: pointer`로 버튼처럼 만들었지만, 라우팅을 추가하면서 버튼처럼 만들어야 할 거예요. 
아마 `<Link />`나 `<button />`처럼 사용해 접근성을 챙길 수 있을텐데 미리 바꿔두면 좋을것 같네요.
이참에 라우팅도?

2023-03-16 02:16 UTC, kimeodml commented on src/pages/Room/RoomPage/RoomPage.module.scss
> +  }
수정했습니다. [efcdd45](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/34/commits/efcdd4593fabadbc3a89ebbe141958ad9421ff38)

2023-03-16 02:17 UTC, kimeodml commented on src/api/room/entity.ts
> +}
수정했습니다. [7347fbf](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/34/commits/7347fbf3b9f0189a2b0c2e8d3ae2efa0053e6328)

2023-03-16 02:17 UTC, kimeodml commented on src/pages/Room/RoomPage/component/MarkerIcon.tsx
> +export default MarkerIcon;
수정했습니다. [52a7a97](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/34/commits/52a7a97bf62b20d607f6a176748d3c48beb3ae0c)

2023-03-16 02:18 UTC, kimeodml commented on src/pages/Room/RoomPage/index.tsx
> +                </div>
수정했습니다. [52a7a97](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/34/commits/52a7a97bf62b20d607f6a176748d3c48beb3ae0c)

2023-03-16 02:18 UTC, kimeodml commented on src/pages/Room/RoomPage/index.tsx
> +  const navermaps = useNavermaps();
수정했습니다. [4dc1ea0](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/34/commits/4dc1ea09519be1bfb022d27c07299f1aa8d21bde)

2023-03-16 02:18 UTC, kimeodml commented on src/api/room/APIDetail.ts
> +  path = 'lands/:id';
수정했습니다. [a23623e](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/34/commits/a23623e7593d8b041f455bdcaf29ecdc27f20d8e)

2023-03-16 02:19 UTC, kimeodml commented on src/pages/Room/RoomPage/component/MarkerIcon.module.scss
> +/* stylelint-disable scss/double-slash-comment-empty-line-before */
깜빡하고 제거 못 한채로 푸쉬했습니다. 수정했습니다. [4dc1ea0](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/34/commits/4dc1ea09519be1bfb022d27c07299f1aa8d21bde)

2023-03-16 02:36 UTC, kimeodml commented on src/pages/Room/RoomPage/RoomPage.module.scss
> +
이전 css에서 margin값을 `margin: 68px auto 84px;` 이런 식으로 줘서 첫 번째 이미지의 여백이 맞는 것 같은데 기존 코인에서 화면을 75%로 축소하면 마진 겹침 현상으로 두 번째 이미지의 여백처럼 좁아지더라고요. 혹시 화면 비율이 75%인가요?

2023-03-18 08:36 UTC, kimeodml commented on package.json
> +    "react-naver-maps": "^0.1.2",
이전 패키지에서는 naver의 네임스페이스를 인식하지 못 해서 패키지를 변경했습니다. 이에 맞게 서드파티 라이브러리 지양하는 방향으로 코드를 수정했습니다. [01da2dd](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/34/commits/01da2dd832ed123e8dfceefbb096bec2b06627c9)

2023-03-18 08:38 UTC, kimeodml commented on src/pages/Room/RoomPage/index.tsx
> +import ReactDOMServer from 'react-dom/server';
icon의 content 타입이 string이라 JSX를 string으로 변경하는 것으로 수정했습니다. [f92d517](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/34/commits/f92d5170c8daa1d138b2051f486c4b7aa028d660)

2023-03-18 08:39 UTC, kimeodml commented on src/pages/Room/RoomPage/index.tsx
> +  Container as MapDiv, NaverMap, useNavermaps, Marker,
패키지를 변경해서 코드가 크게 바뀌었습니다. [01da2dd](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/34/commits/01da2dd832ed123e8dfceefbb096bec2b06627c9)

2023-03-18 08:43 UTC, kimeodml commented on src/pages/Room/RoomPage/hooks/useRoomList.ts
> +    },
불필요한 재시도를 주기 싫어서 0으로 설정했습니다.

2023-03-18 08:43 UTC, kimeodml commented on src/pages/Room/RoomPage/index.tsx
> +            <div className={styles.list__box} key={room.id}>
수정했습니다. 라우팅 부분은 다음 브랜치에서 추가하겠습니다! [6c4b6ff](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/34/commits/6c4b6ff0219809305a3d8916a30c4fa447fce1e0)

2023-03-18 08:44 UTC, kimeodml commented
네이버 지도 패키지를 변경해서  코드가 조금 수정되었습니다!

2023-03-18 08:56 UTC, kimeodml commented on src/api/room/entity.ts
> +  created_at: string,
혹시 [이런식](https://stackoverflow.com/questions/45485073/how-do-i-express-a-date-type-in-typescript)으로 타입지정 하라는 의미인가요?

2023-03-18 09:14 UTC, SimYunSup requested changes

2023-03-18 09:14 UTC, SimYunSup commented on src/pages/Room/RoomPage/hooks/useMarker.ts
> +  }, [map, roomList?.lands]);
map의 값을 추적해봤더니 ref가 저장하는 값이 들어가는군요. useEffect의 dependency list에 ref가 들어가면  무슨 일이 일어날까요?

2023-03-18 09:14 UTC, SimYunSup commented on src/pages/Room/RoomPage/hooks/useMarker.ts
> +import MarkerIcon from 'components/Room/MarkerIcon/index';
```suggestion
import MarkerIcon from 'components/Room/MarkerIcon';
```
index는 넣을 필요가 없어보입니다.

2023-03-18 09:14 UTC, SimYunSup commented on src/pages/Room/RoomPage/hooks/useMarker.ts
> +  }, [map, roomList?.lands]);
추가로 roomList?.lands를 dependency list에 들어간 이유도 묻고 싶네요.

2023-03-18 09:14 UTC, SimYunSup commented on src/components/Room/MarkerIcon/index.tsx
> +      <div class=${styles.pluse}></div>
따옴표가 빠져있습니다.

2023-03-18 09:14 UTC, SimYunSup commented on src/components/Room/RoomList/index.tsx
> +        <Link className={styles.list__link} to={`/room/${room.id}`} key={room.id}>
리스트와 아이템에는 ul 태그 / li 태그로 감싸주어야 합니다.

2023-03-18 09:14 UTC, SimYunSup commented on src/pages/Room/RoomPage/hooks/useMarker.ts
> +    setMarkerArray(newMarkers);
조건문을 밖으로 빼기 / array.map을 사용하기를 적용하면 더 깔끔해질 수 있겠네요.

2023-03-18 12:32 UTC, kimeodml commented on src/components/Room/RoomList/index.tsx
> +        <Link className={styles.list__link} to={`/room/${room.id}`} key={room.id}>
수정했습니다. [10b097a](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/34/commits/10b097aaed2aa7a73f407e39a3be27a7446778b6)

2023-03-18 12:33 UTC, kimeodml commented on src/pages/Room/RoomPage/hooks/useMarker.ts
> +    setMarkerArray(newMarkers);
수정했습니다. [e65efff](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/34/commits/e65efff446063f0b01ede034afed1869afb45508)

2023-03-18 12:33 UTC, kimeodml commented on src/components/Room/MarkerIcon/index.tsx
> +      <div class=${styles.pluse}></div>
백틱을 사용했기 때문에 따옴표를 넣으면 UI에 나타나는데 혹시 어느 부분을 말하는지 알 수 있을까요..?

2023-03-18 12:41 UTC, kimeodml commented on src/pages/Room/RoomPage/hooks/useMarker.ts
> +  }, [map, roomList?.lands]);
> 추가로 roomList?.lands를 dependency list에 들어간 이유도 묻고 싶네요.

esling에 map과 roomList?.lands를 넣으라고 해서 넣었습니다. deps에 ref값을 넣으면 ref값이 변경되는 것을 감지하지 못해 useCallback을 사용해야 한다는 것을 [블로그](https://velog.io/@shmoon2917/useEffect-%EC%9D%98%EC%A1%B4%EC%84%B1%EC%97%90-ref%EB%A5%BC-%EB%8B%B4%EC%9D%84-%EB%95%8C%EB%A7%88%EB%8B%A4-%EC%B0%9C%EC%B0%9C%ED%95%98%EC%8B%A0-%EB%B6%84%EB%93%A4%EC%9D%84-%EC%9C%84%ED%95%B4)를 통해 알게 되었습니다. useCallback으로 감싸겠습니다!

2023-03-18 12:42 UTC, kimeodml commented on src/pages/Room/RoomPage/hooks/useMarker.ts
> +import MarkerIcon from 'components/Room/MarkerIcon/index';
수정했습니다. [e65efff](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/34/commits/e65efff446063f0b01ede034afed1869afb45508)

2023-03-20 13:07 UTC, kimeodml commented on src/pages/Room/RoomPage/hooks/useMarker.ts
> +  }, [map, roomList?.lands]);
수정했습니다. [f330dc8](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/34/commits/f330dc870f0547b8fd249322fc7d29eb424f1de5)

2023-03-20 14:17 UTC, SimYunSup commented on src/pages/Room/RoomPage/hooks/useMarker.ts
> +  }, [map, roomList?.lands]);
수정을 임시방편으로 한 것 같습니다. useCallback의 dependency list에 ref가 들어간 것은 똑같지 않나요?

2023-03-21 08:04 UTC, kimeodml commented on src/components/Room/MarkerIcon/index.tsx
> +      <div class=${styles.pluse}></div>
수정했습니다. [fa3d6a7](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/34/commits/fa3d6a7b4ba1c79cf0b144337c898af772429adf)

2023-03-21 08:58 UTC, kimeodml commented on src/pages/Room/RoomPage/hooks/useMarker.ts
> +  }, [map, roomList?.lands]);
map을 필수로 집어 넣어야 해서 그 부분만 lint 예외 처리했습니다. [8be3e04](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/34/commits/8be3e04844931cb851956a5d638d82e91570d570)

2023-03-21 09:25 UTC, kimeodml commented on src/api/room/entity.ts
> +  created_at: string,
데이터 값을 string으로 주었기 때문에 string으로 유지하겠습니다.

2023-03-21 12:34 UTC, daepan commented on src/pages/Room/RoomPage/RoomPage.module.scss
> +
딱히 % 문제는 아니었던 것 같고 지금은 정상적으로 나오는 거 확인했습니다!

2023-03-21 13:19 UTC, ChoiWonBeen approved these changes
아래 사소한 내용 제외하곤 다 잘 만들어진 것 같네요
Marker부분 마저 화이팅하세여~~ 🔥

2023-03-21 13:19 UTC, ChoiWonBeen commented on src/api/room/entity.ts
> +  floor: null,
`null`인 데이터가 들어오나요?
안쓰는 데이터라면 빼도 될 것 같아요

2023-03-21 13:19 UTC, ChoiWonBeen commented on src/api/room/entity.ts
> +  opt_air_conditioner: boolean,
option들은 옵션끼리 모아두는게 나중에 관리하기 편하지 않을까... 개인적으로 생각합니다 ㅎ

2023-03-21 13:19 UTC, ChoiWonBeen commented on src/pages/Room/RoomPage/hooks/useMarker.ts
> +            content: MarkerIcon(),
👍

2023-03-21 16:23 UTC, kimeodml commented on src/pages/Room/RoomPage/hooks/useMarker.ts
> +  }, [map, roomList?.lands]);
어쩐지...고치면서 계속 이게 맞나? 이생각 했네요. 다음부터 주의하겠습니다! [c5837b2](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/34/commits/c5837b259c13ee1abc357e0986f6f2404547b3db) [a55d2ae](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/34/commits/a55d2ae3ab30c6379696b9bbe025c6a4fe943c9d)

2023-03-22 04:11 UTC, SimYunSup approved these changes
원빈이가 말한 부분만 수정하면 추가로 고칠 부분은 없어보입니다. 고생하셨습니다.

2023-03-22 06:19 UTC, kimeodml commented on src/api/room/entity.ts
> +  floor: null,
수정했습니다. [b9c24bb](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/34/commits/b9c24bbba0c41a8a74ab56e16f36ae1730d2882f)

2023-03-22 06:19 UTC, kimeodml commented on src/api/room/entity.ts
> +  opt_air_conditioner: boolean,
수정했습니다. [b9c24bb](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/34/commits/b9c24bbba0c41a8a74ab56e16f36ae1730d2882f)

2023-03-22 07:44 UTC, ChoiWonBeen approved these changes
고생하셨어요~ 브랜치 관리 설정에 새로 push를 할 경우 이전 approve들을 dissmiss해버리는 설정이 있어서 수정했습니다.

2023-03-22 10:21 UTC, daepan approved these changes
수고하셨습니다

2023-03-22 10:21 UTC, merged