[hotfix] access토큰 만료 시 페이지 이동 조건 추가
BCSDLab/KOIN_WEB_RECODE pull request #372
Opened 2024-07-23 14:19 UTC by Gwak-Seungju

- Close #371 
  
## What is this PR? 🔍

- 기능 : access 토큰 만료 시 refresh토큰이 없는 경우에만 로그인 페이지로 이동하게 합니다.
- issue : #371 

## Changes 📝

access토큰 만료 시 refresh토큰 access 토큰을 갱신하여 로그인이 유지되어 있음에도 불구하고 로그인 페이지로 이동하여 재로그인을 유도하는 것을 방지하기 위해 `localStorage`에 저장하는 refreshToken의 유무에 따라 로그인 페이지로의 이동 여부를 판단했습니다.

## Precaution
reload를 하지 않으면 토큰 갱신 api를 불러오지 않아서 `window.location.reload()`를 사용했습니다.

## ✔️ Please check if the PR fulfills these requirements
----------------------------------------------------------------------------------
- [ ] It's submitted to the correct branch, not the `develop` branch unconditionally?
- [ ] If on a hotfix branch, ensure it targets `main`?
- [ ] There are no warning message when you run `yarn lint`

2024-07-24 09:50 UTC, daepan requested changes
뭔가 강제로 리로딩하는게 맞는 방법일지에 대한 많은 고민이 듭니다. 이전에 이런 문제를 통해 많은 고민을 하던 모습을 봤었는데 해결방법이 그렇게 좋지 않은 방향이라는 생각은 듭니다.
이렇게 선택하게 된 이유가 있다면 공유 부탁드립니다.

2024-07-24 09:50 UTC, daepan commented on src/utils/ts/apiClient.ts
> +      }
이렇게 새로고침을 강제하게 된다면은 사용자 5분 동안 사용한 경우에 새로고침을 2번 하게 되겠네요
이 방식은 앞으로 들어오게 되는 리뷰 작성이나 사용자가 실제로 무엇인가 작성하고 있는 경우에 내용자체가 없어질 수 있다고 생각합니다.

혹시 이에 대해서 새로고침 이외의 401을 캐치했다면 Refresh 로직 이후에 실패한 API를 재동작 할 수 있는 방식은 없었을까요?
혹은 현재 Zustand를 통한 전역 구조로 관리하는데 setInterval과 같은 비동기 처리 로직을 통해 클라이언트 자체 에서 리프레쉬 시키는 방법은 어떨까요?

혹여나 팀원끼리 해당 방식을 선택하게 된 회의록이 있다면 추가로 공유해주시고, 급한 hotfix라면 해당 내용에 대한 주석을 달아주시면 좋을 것 같습니다.

2024-08-04 10:11 UTC, MinGu-Jeong commented
@Gwak-Seungju
PR 올라온지 2주이상 지나서 확인차 리마인드 드립니다.
리뷰사항을 반영하는데 시간이 오래걸릴 것 같으면 해당 리뷰에 👀 이모지라도 달아야 진행상황을 알 수 있을것 같습니다.
만약 리뷰사항에 궁금한 점이 있다면 리뷰에 reply나 슬랙에 적극적으로 물어봐도 좋을 것 같습니다.

리뷰사항이 반영되었다면 리뷰어에게 Re-request review를 요청해주시면 좋을 것 같아요.

2024-08-10 01:51 UTC, Gwak-Seungju commented
대관님의 Review를 참고하여 코드를 수정했습니다.
## 바뀐점
- refreshAccessToken 로직을 APIClient로 옮겼습니다.
 --> 그 이유는 401에러 시점에서 refresh를 바로 해야된다고 생각했고, 그러기 위해서 `APIClinet`에서 `api/auth`에 있는 refresh를 불러와야 합니다. 하지만, `api/auth`에서도 `APIClient`를 참조하고 있어 순환참조 문제가 발생했기 때문에 api/auth에 있는 로직을 APIClient로 옮겼습니다.
 - useTokenState에서refreshAccessToken을 하지 않음.
 --> `useTokenState`에서 refresh를 하게 되면 `useTokenState`를 사용하는 컴포넌트마다 refresh를 호출하기 때문에 불필요한 호출이 많이 생기게 됩니다.

2024-08-10 05:47 UTC, daepan approved these changes
승주님이라면 해결할 줄 알았습니다. 쉽지 않은 문제였을텐데 근거있게 해결해보신 경험이 되셨길 바랍니다. 
해당 로직이 들어옴으로써 어떤 기대효과가 있을까요? 제가 말한 문제가 발생하지 않을까요?
해당 로직은 공통 로직이기에 이번 해결과정과 근거를 문서로 정리해두고 머지 이전에 내용을 프론트엔드 슬랙채널에 공유해주신 이후에 머지를 진행해주세요

2024-08-10 05:47 UTC, daepan commented
추가로 confilct 확인해주세요~

2024-08-10 11:49 UTC, merged