[리뷰하기] 리뷰하기 api 연동
BCSDLab/KOIN_WEB_RECODE pull request #388
Opened 2024-08-02 02:21 UTC by kimeodml

- Close #340 
  
## What is this PR? 🔍

- 기능 : api 추가
- issue : #340 

## Changes 📝

- 리뷰 작성하기 api 연동 완료했습니다.
- 비회원 모달창을 공용 컴포넌트로 구현했습니다.
  - `LoginRequiredModal`
- 음식점 상세 페이지에서 로그인을 하면 경로가 유지됩니다.

## ScreenShot 📷
![image](https://github.com/user-attachments/assets/b47dbf7a-eeb3-4464-88de-0f84652d74c0)

## Test CheckList ✅

- [ ] 리뷰 작성 시 오류 없이 api 요청이 잘 되는지 확인

## Precaution

## ✔️ Please check if the PR fulfills these requirements

- [ ] It's submitted to the correct branch, not the `develop` branch unconditionally?
- [ ] If on a hotfix branch, ensure it targets `main`?
- [ ] There are no warning message when you run `yarn lint`

2024-08-02 02:49 UTC, MinGu-Jeong commented on src/pages/Store/StoreDetailPage/Review/components/ReviewButton/index.tsx
> +            onClick();
`onClick()`이라는 네이밍으로는 어떤 동작을 할지 예측하기가 조금 어려운 것 같아요🥲

2024-08-02 02:49 UTC, MinGu-Jeong commented on src/pages/Store/StoreDetailPage/index.tsx
> +        {tapType === '리뷰' && <ReviewPage id={params.id!} />}
`id`가 undefined인 경우는 아마 없겠죠..?

2024-08-02 02:49 UTC, MinGu-Jeong commented on src/pages/StoreReviewPage/hooks/useStoreReview.ts
> +        showToast('error', err.message || '에러가 발새했습니다.');
오타 ㅠㅠ

2024-08-02 02:49 UTC, MinGu-Jeong commented on src/utils/hooks/useImageUpload.ts
> +    if (files && (files.length > 3 || imageFile.length >= 3 || imageFile.length + files.length > 3)) {
`imageFile.length + files.length >3`만 있어도 `files.length > 3 || imageFile.length >= 3` 이 두 경우를 다 커버하지 않나요?

2024-08-02 02:49 UTC, MinGu-Jeong commented on src/utils/hooks/useImageUpload.ts
> +
위에 console.log가 몇개 있던데 목적이 있는 콘솔인가용?

2024-08-02 02:50 UTC, MinGu-Jeong commented on src/pages/StoreReviewPage/hooks/useStoreReview.ts
> +        showToast('error', err.message || '에러가 발새했습니다.');
앗 고쳤네요 굿굿

2024-08-02 02:59 UTC, kimeodml commented on src/utils/hooks/useImageUpload.ts
> +
lint 오류에 안 걸려서 제거하지 못 했네요. 제거하겠습니다!

2024-08-02 04:25 UTC, chaeseungyun commented on src/utils/hooks/useImageUpload.ts
> +    if (files && (files.length > 3 || imageFile.length >= 3 || imageFile.length + files.length > 3)) {
(2, 2) (3, 2) 일때 안되네용

2024-08-02 04:35 UTC, kimeodml commented on src/utils/hooks/useImageUpload.ts
> +    if (files && (files.length > 3 || imageFile.length >= 3 || imageFile.length + files.length > 3)) {
(2, 2) (3, 2)가 무슨 소리죠...? 지금 생각해 보니까 `imageFile.length + files.length >3`만 있어서도 필터링 되는 것 같아서요

2024-08-02 04:35 UTC, kimeodml commented on src/pages/Store/StoreDetailPage/index.tsx
> +        {tapType === '리뷰' && <ReviewPage id={params.id!} />}
없을겁니다..!

2024-08-02 04:37 UTC, kimeodml commented on src/pages/Store/StoreDetailPage/Review/components/ReviewButton/index.tsx
> +            onClick();
수정했습니다. [05565b7](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/388/commits/05565b74ca11846b9c101ce65a5b12480ded388e)

2024-08-02 06:50 UTC, daepan requested changes
수고하셨습니다. 몇가지 질문 남겨놨습니다.
모달 훅이 별로 유용하지 않았나요? 재사용이 간단할거라고 작성했던 로직인데 생각보다 유용하지 않다면 새로 변경을 고려해보겠습니다. 모달로직쪽으로 한번 검토 부탁드려요

2024-08-02 06:50 UTC, daepan commented on src/pages/Store/StoreDetailPage/Review/components/ReviewButton/index.tsx
> +    </>
이전에 제가 따로 모달과 관련된 훅을 따로 선언했었는데, 혹시 그건 사용할 수 없었을까요?
따로 구현하신 이유가 궁금합니다.
https://github.com/BCSDLab/KOIN_WEB_RECODE/blob/develop/src/pages/Store/StoreDetailPage/index.tsx

2024-08-02 06:50 UTC, daepan commented on src/pages/StoreReviewPage/index.tsx
> +    }
submit 과정에 대한 validation 체크 로직은 따로 필요 없을까요? 따로 선택하지 않아도 잘 들어가는지 궁금합니다.

2024-08-02 06:50 UTC, daepan commented on src/utils/hooks/useImageUpload.ts
> +      console.log('72', uploadedFile);
콘솔 지워도 될 것 같아요!

2024-08-02 06:50 UTC, daepan commented on src/utils/hooks/useImageUpload.ts
> +          console.log('49',data);
요기도 console

2024-08-02 06:50 UTC, daepan commented on src/utils/hooks/useImageUpload.ts
> +export default function useImageUpload() {
eslint왜 disable 된 건가요?

2024-08-02 07:33 UTC, kimeodml commented on src/pages/Store/StoreDetailPage/Review/components/ReviewButton/index.tsx
> +    </>
엇..? 있었네요ㅠ 공용 훅을 미처 파악 못 했었네요. 모달 하면 createPortal로만 생각하고 있어서 이참에 한 번 사용해 보겠습니다! 저희 프로젝트에 createPortal로 생성한 모달도 존재하는데 뭔가 공용 훅과 관련해서 다른 사람도 알 수 있게 공통 노션이나 wiki에 파악할 수 있게 추가하는 것도 나쁘지 않을 것 같네요..!

2024-08-03 07:48 UTC, kimeodml commented on src/pages/StoreReviewPage/index.tsx
> +    }
넵 없어도 괜찮습니다

2024-08-03 10:38 UTC, kimeodml commented on src/utils/hooks/useImageUpload.ts
> +export default function useImageUpload() {
`new RegExp` 사용하면서 disable 처리한 것으로 추측됩니다. (오너쪽에서 가져온 거라서..ㅎ)

2024-08-03 10:39 UTC, kimeodml commented on src/utils/hooks/useImageUpload.ts
> +    if (files && (files.length > 3 || imageFile.length >= 3 || imageFile.length + files.length > 3)) {
조건문 수정했습니다. [9a022b1](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/388/commits/9a022b1a92e7e85aecb9cd6eb4132dbea5be40ed)

2024-08-03 10:43 UTC, kimeodml commented on src/pages/Store/StoreDetailPage/Review/components/ReviewButton/index.tsx
> +    </>
useModalPortal로 변경완료했습니다. 상태값 추가로 구현 안 해도 돼서 편리한 것 같네요. useNavigate 기능 때문에 BrowserRouter 내부로 이동했습니다! [5f36e0e](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/388/commits/5f36e0ed32879447ddbbc9c929c25579ddcf6e80)

2024-08-04 08:17 UTC, daepan approved these changes
수고하셨습니다.
Review에 붙이는 기능에 대해서는 따로 develop을 안가져와도 될 것 같아요 ^^

2024-08-04 08:17 UTC, daepan commented on package.json
> +    "dayjs": "^1.11.12",
예전에 나 이거 도입하려고 했을때 많이 토론했었는데 ㅋㅋ 개인적으로 개발의 질이 올라가는 느낌!
아주 좋습니다.

2024-08-04 09:16 UTC, merged