[복덕방] 복덕방 상세 페이지 작성
BCSDLab/KOIN_WEB_RECODE pull request #39
Opened 2023-03-28 04:17 UTC by kimeodml

## [#33] request

복덕방 상세 페이지 작성 완료했습니다.
- 테이블, 이미지 슬라이더, 옵션, 지도를 컴포넌트 폴더에 분류했습니다.
- 모바일 상에서 어두운 이미지일 경우 이미지 슬라이더 버튼이 안 보여서 디자인을 변경했습니다.

## Please check if the PR fulfills these requirements

- [x] It's submitted to `develop` branch, __not__ the `main` branch
- [x] The commit message follows our guidelines
- [x] There are no warning message when you run `yarn lint`
- [x] Docs updated for breaking changes

### Screenshot
![image](https://user-images.githubusercontent.com/88065770/228126794-fe74164d-386b-4b6a-89d5-f7b6e42726a4.png)

<img src="https://user-images.githubusercontent.com/88065770/228126520-0b72be8e-9f70-4dc8-8698-96757190d8df.png" width="40%" />

2023-03-28 04:40 UTC, SimYunSup requested changes
생각해볼만한 제안을 많이 드렸습니다. 리코드는 라이브러리만 바꾸는 것만이 아닌 코드 구조 개선도 같이 이루어진다는 점 명심드리면서 변경을 제안합니다.

2023-03-28 04:40 UTC, SimYunSup commented on src/api/room/APIDetail.ts
> +  constructor(id: string | undefined) {
id는 무조건 string이여야 합니다. undefined값에 따른 API값이 없기 때문에 undefined를 삽입하는 것은 옳지 않습니다.

2023-03-28 04:40 UTC, SimYunSup commented on src/components/Room/RoomDetailImg/RoomDetailImg.module.scss
> +  &__indx {
대중적이지 않은 줄임말은 혼란을 초래합니다. index로 바꿔주세요.

2023-03-28 04:40 UTC, SimYunSup commented on src/components/Room/RoomDetailImg/index.tsx
> +      {imgUrl ? (
imgUrl이 없을 때를 안에서 판단하지 않아도 된다고 생각합니다. 이 상태는 밖에서 관리하는 것이 좋아보입니다.

2023-03-28 04:40 UTC, SimYunSup commented on src/components/Room/RoomDetailImg/index.tsx
> +            <img src="https://static.koreatech.in/assets/ic-room/left-arrow.png" alt="이전 화살표" />
```suggestion
            <img src="https://static.koreatech.in/assets/ic-room/left-arrow.png" alt="이전 이미지 보기" />
```
위 표현이 더 옳습니다.

2023-03-28 04:40 UTC, SimYunSup commented on src/pages/Room/RoomDetailPage/hooks/useDetailMap.ts
> +}
약간의 추상화를 거치면 이전에 썼던 useLocationMap을 재사용할 수 있을 것 같습니다.

2023-03-28 04:40 UTC, SimYunSup commented on src/pages/Room/RoomDetailPage/hooks/useDetailMap.ts
> +      setMap(newMaps);
```suggestion
      setMap(newMaps);
      return () => {
        newMaps.destory();
      }
```
map 객체를 파괴하는 절차가 필요합니다.

2023-03-28 04:40 UTC, SimYunSup commented on src/pages/Room/RoomDetailPage/hooks/useDetailMap.ts
> +  }, [latitude, longitude, map]);
map은 dependency에 필요없다고 생각합니다.

2023-03-28 04:40 UTC, SimYunSup commented on src/components/Room/RoomDetailTable/index.tsx
> +export default RoomDetailTable;
컴포넌트를 나눈 이유라도 있을까요?

2023-03-28 04:40 UTC, SimYunSup commented on src/components/Room/RoomDetailOption/index.tsx
> +}
option만 넣을 수 있고, 더 구체화할 수 있을 것 같습니다.
```suggestion
type OptionProps = {
  [key in typeof OPTION_CATEGORY[number]['img_code']]: boolean;
};
```

2023-03-28 04:40 UTC, SimYunSup commented on src/components/Room/RoomDetailMap/index.tsx
> +  roomDetail: LandDetailResponse
통째로 넘기는 것은 좋지 못한 선택입니다. 컴포넌트가 종속될 뿐만 아니라 다른 곳에 쓰이기도 어렵습니다.

2023-03-29 02:52 UTC, ChoiWonBeen requested changes
고생하셨어요~ 작업이 빠르시네요 👍 
몇가지 사소한점들 짚어봤으니 확인해주세여~

2023-03-29 02:52 UTC, ChoiWonBeen commented on src/components/Room/RoomDetailImg/index.tsx
> +          </div>
간단하게 아래처럼 줄일 수 있을 것 같아요.
옛날에도 이런 리뷰를 드렸던 것 같은 기억이? ㅋㅋㅋ
```suggestion
          <div className={styles['img-slider__indx']}>
            {`${imgIndx + 1} / ${imgUrl.length}`}
          </div>
```

2023-03-29 02:52 UTC, ChoiWonBeen commented on src/components/Room/RoomDetailImg/index.tsx
> +            onClick={() => clickRightArrow(imgUrl?.length)}
사소하지만 imgUrl이 있는 조건이기에 불필요한 옵셔널이져
```suggestion
            onClick={() => clickRightArrow(imgUrl.length)}
```

2023-03-29 02:52 UTC, ChoiWonBeen commented on src/components/Room/RoomDetailImg/index.tsx
> +          <div className={styles['img-slider__no-img']}>
bem style로 생각하면 `img-slider__img--empty` 같은 구문이 적절할 것 같은데 어때보이나요??

2023-03-29 02:52 UTC, ChoiWonBeen commented on src/components/Room/RoomDetailMap/RoomDetailMap.module.scss
> +.mapContainer {
camelCase의 클래스네임은 바꿔야할 것 같아요 ㅋㅋ

2023-03-29 02:52 UTC, ChoiWonBeen commented on src/components/Room/RoomDetailOption/RoomDetailOption.module.scss
> +  }
여기도 camelCase로 작성되어있네요

2023-03-29 02:52 UTC, ChoiWonBeen commented on src/components/Room/RoomDetailTable/index.tsx
> +        </tr>
객체 + 반복문으로 돌리는 건 어땠을까 싶어요.
셀 내부 내용때문에 힘드려나요?

2023-04-01 14:25 UTC, kimeodml commented on src/components/Room/RoomDetailImg/RoomDetailImg.module.scss
> +  &__indx {
수정했습니다. [6bee8d8](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/39/commits/6bee8d800081d8f6cbeaee232f92ec771ae7935f)

2023-04-01 14:26 UTC, kimeodml commented on src/components/Room/RoomDetailImg/index.tsx
> +            <img src="https://static.koreatech.in/assets/ic-room/left-arrow.png" alt="이전 화살표" />
수정했습니다. [6bee8d8](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/39/commits/6bee8d800081d8f6cbeaee232f92ec771ae7935f)

2023-04-01 14:26 UTC, kimeodml commented on src/components/Room/RoomDetailImg/index.tsx
> +          </div>
수정했습니다. [6bee8d8](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/39/commits/6bee8d800081d8f6cbeaee232f92ec771ae7935f)

2023-04-01 14:27 UTC, kimeodml commented on src/components/Room/RoomDetailImg/index.tsx
> +          <div className={styles['img-slider__no-img']}>
이름이 어색하다고 생각했었는데 수정했습니다. [6bee8d8](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/39/commits/6bee8d800081d8f6cbeaee232f92ec771ae7935f)

2023-04-01 14:28 UTC, kimeodml commented on src/components/Room/RoomDetailMap/RoomDetailMap.module.scss
> +.mapContainer {
수정했습니다. [fe38e65](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/39/commits/fe38e65060d55e5035e8d17b1a6668a4615c7093)

2023-04-01 14:28 UTC, kimeodml commented on src/components/Room/RoomDetailOption/RoomDetailOption.module.scss
> +  }
수정했습니다. [fe38e65](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/39/commits/fe38e65060d55e5035e8d17b1a6668a4615c7093)

2023-04-01 14:29 UTC, kimeodml commented on src/components/Room/RoomDetailImg/index.tsx
> +            onClick={() => clickRightArrow(imgUrl?.length)}
수정했습니다. [6bee8d8](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/39/commits/6bee8d800081d8f6cbeaee232f92ec771ae7935f)

2023-04-01 14:30 UTC, kimeodml commented on src/components/Room/RoomDetailMap/index.tsx
> +  roomDetail: LandDetailResponse
수정했습니다. [30b00d4](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/39/commits/30b00d479374c3dcc6b0d46017b7d6dd99a8c40d)

2023-04-01 14:32 UTC, kimeodml commented on src/pages/Room/RoomDetailPage/hooks/useDetailMap.ts
> +}
수정했습니다. [da21295](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/39/commits/da21295c12e52151b5010b7031bd2f2d42d0505f) [30b00d4](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/39/commits/30b00d479374c3dcc6b0d46017b7d6dd99a8c40d)

2023-04-01 14:33 UTC, kimeodml commented on src/pages/Room/RoomDetailPage/hooks/useDetailMap.ts
> +  }, [latitude, longitude, map]);
map을 제외하면 eslint 예외 처리를 추가해야 해서 부득이하게 추가되었습니다. [da21295](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/39/commits/da21295c12e52151b5010b7031bd2f2d42d0505f)

2023-04-01 14:34 UTC, kimeodml commented on src/pages/Room/RoomDetailPage/hooks/useDetailMap.ts
> +      setMap(newMaps);
수정했습니다. [da21295](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/39/commits/da21295c12e52151b5010b7031bd2f2d42d0505f)

2023-04-01 14:39 UTC, kimeodml commented on src/components/Room/RoomDetailTable/index.tsx
> +export default RoomDetailTable;
RoomDetailPage에 모든 코드가 있으면 가독성이 떨어지는 것 같아 컴포넌트로 분리했습니다.

2023-04-02 11:21 UTC, daepan requested changes
수고하셨습니다.
하나만 추가해야하는 기능만 확인해주세요
복덕방에서 상세로 들어가는 카드를 클릭했을 때 스크롤이 상단으로 초기화되는 기능 하나만 추가해주세요
useScrollToTop이라는 훅을 넣어두었으니 활용하시면 좋을 것 같습니다.

2023-04-09 04:50 UTC, kimeodml commented on src/api/room/APIDetail.ts
> +  constructor(id: string | undefined) {
params.id값이 `undefined | string`을 나타내고 있어서 undefined를 추가했습니다. store의 `APIDetail`에서처럼 any로 변경해도 될까요?

2023-04-09 05:41 UTC, ChoiWonBeen commented on src/api/room/APIDetail.ts
> +  constructor(id: string | undefined) {
이 함수가 인자로 들어올 params.id의 타입을 신경쓰는건 분리가 덜 된 부분이라고 보여요.
오히려 인자로 들어오는 params.id쪽의 타입을 string이나 number형태로 고정시켜줘야 한다고 생각해요.

2023-04-09 15:27 UTC, kimeodml commented on src/components/Room/RoomDetailImg/index.tsx
> +      {imgUrl ? (
수정했습니다. [ee78b9f](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/39/commits/ee78b9fbfbae66f89e1969bbac84395343621635)

2023-04-09 15:27 UTC, kimeodml commented on src/api/room/APIDetail.ts
> +  constructor(id: string | undefined) {
수정했습니다. [63291ce](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/39/commits/63291cec59a8a6bd5ebc6a7a9843124bad88beac)

2023-04-10 11:57 UTC, kimeodml commented on src/components/Room/RoomDetailTable/index.tsx
> +        </tr>
음...셀 내부 내용 때문에 어려울것 같습니다

2023-04-10 13:16 UTC, kimeodml commented on src/components/Room/RoomDetailOption/index.tsx
> +}
roomDetail의 값이 boolean 값 외에도 여러 타입의 값들이 존재하는데 위의 방식으로 하면 타입 오류가 뜨지 않나요?

2023-04-10 13:48 UTC, SimYunSup commented on src/components/Room/RoomDetailOption/index.tsx
> +}
roomDetail중 option값만 추출해서 props로 넘기면 됩니다.

2023-04-11 03:51 UTC, SimYunSup requested changes

2023-04-11 03:51 UTC, SimYunSup commented on src/pages/Room/RoomDetailPage/hooks/useClickArrow.ts
> +  };
length를 훅의 파라미터로 받는 것이 확장(ex. moveToIndex)에도 좋고 통일성에도 좋을 것으로 보입니다.

2023-04-11 03:51 UTC, SimYunSup commented on src/pages/Room/RoomDetailPage/index.tsx
> +            address={roomDetail?.address}
optional chaining을 한 이유라도 있나요?

2023-04-11 03:51 UTC, SimYunSup commented on src/pages/Room/RoomPage/index.tsx
> +  const location = { latitude: 36.764617, longitude: 127.2831540 };
해당 변수는 컴포넌트 바깥으로 빼도 됩니다.

2023-04-11 03:51 UTC, SimYunSup commented on src/components/Room/RoomDetailTable/index.tsx
> +  phone: string
다른 interface처럼 member-delimiter-style를 지켜주세요.

2023-04-11 03:51 UTC, SimYunSup commented on src/components/Room/RoomDetailOption/index.tsx
> +              [option.img_code as keyof LandDetailResponse] === false,
하나로 통일하고 `:not()`키워드로 나눌 수 있을 것 같습니다.

2023-04-11 03:51 UTC, SimYunSup commented on src/pages/Room/RoomDetailPage/RoomDetailPage.module.scss
> +}
BEM표기법을 사용하지 않았다고 볼 수 있습니다. BEM표기법을 사용하지 않는다면 맞는 이름짓기이지만 BEM표기법을 사용하기 위해 같은 컴포넌트는 블록으로, 그 안의 요소는 `block__element`같은 방식으로 바꾸어야 합니다.

2023-04-11 03:51 UTC, SimYunSup commented on src/components/Room/RoomDetailTable/index.tsx
> +        </tr>
반복문으로 변경 가능할 것같습니다. 표현식을 통일하고(어느 키워드는 `||`를 사용하고 다른 키워드는 삼항 연산자를 사용) 다음 링크를 통해 어떻게 만들지 고민해보세요.
https://fe-developers.kakaoent.com/2023/230330-frontend-solid/#ocp--open-closed-principle

2023-04-11 05:13 UTC, ChoiWonBeen commented on src/pages/Room/RoomPage/index.tsx
> +  const location = { latitude: 36.764617, longitude: 127.2831540 };
초기값이라면 상수처럼 네이밍을 지어주는것도 좋겠네여

2023-04-25 07:32 UTC, kimeodml commented on src/pages/Room/RoomDetailPage/RoomDetailPage.module.scss
> +}
수정했습니다. [322c515](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/39/commits/322c515268caed543835fb2bb38c2867fce14401)

2023-04-25 07:32 UTC, kimeodml commented on src/components/Room/RoomDetailTable/index.tsx
> +  phone: string
수정했습니다. [959ad10](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/39/commits/959ad10f7682c88653d7d4a5ce4d8c295800fb3e)

2023-04-25 12:36 UTC, kimeodml commented on src/components/Room/RoomDetailTable/index.tsx
> +        </tr>
수정했습니다. [64fab6c](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/39/commits/64fab6ca590fe13723a63c64b15526e8badd0bfa)

2023-04-28 10:09 UTC, kimeodml commented on src/pages/Room/RoomDetailPage/index.tsx
> +            address={roomDetail?.address}
무의식 중에 계속 넣어버렸습니다. 제거했습니다. [c07410d](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/39/commits/c07410d79bc8294aa5c477d278d914c359e28996)

2023-04-28 10:09 UTC, kimeodml commented on src/components/Room/RoomDetailOption/index.tsx
> +}
수정했습니다. [c07410d](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/39/commits/c07410d79bc8294aa5c477d278d914c359e28996)

2023-04-28 10:09 UTC, kimeodml commented on src/components/Room/RoomDetailOption/index.tsx
> +              [option.img_code as keyof LandDetailResponse] === false,
그냥 부정문으로 표현했는데 괜찮을까요? [c07410d](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/39/commits/c07410d79bc8294aa5c477d278d914c359e28996)

2023-05-02 13:54 UTC, kimeodml commented on src/components/Room/RoomDetailOption/index.tsx
> +              [option.img_code as keyof LandDetailResponse] === false,
수정 완료했습니다. [c7e3864](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/39/commits/c7e3864ceafcc72809eb4be0db47bca4fa1dc5a3)

2023-05-24 04:45 UTC, SimYunSup approved these changes

2023-05-24 05:58 UTC, merged