[비즈니스] 리뷰 삭제 기능 추가
BCSDLab/KOIN_WEB_RECODE pull request #399
Opened 2024-08-07 01:43 UTC by chaeseungyun

- Close #ISSUE_NUMBER
  
## What is this PR? 🔍

- 기능 : 
- issue : #

## Changes 📝

리뷰 삭제 기능을 추가했습니다. 추가적으로 수정, 삭제, 신고 성공 시 하단에 뜨는 토스트를 제작했습니다.

수정, 신고를 작업 중이신 분들은 참고해서 적용해주세요
지금 리뷰 정렬을 클라이언트쪽에서 하고 있어서 상태관리가 어려운 상황입니다.
백엔드에게 문의했으니 이 부분은 추후 반영하겠습니다.

## ScreenShot 📷
![image](https://github.com/user-attachments/assets/8d4befb2-7e30-4f96-8786-997873436077)
![image](https://github.com/user-attachments/assets/62386785-e00b-43d9-adb6-a561304a99ba)

## Test CheckList ✅

- [ ] test 1
- [ ] test 2
- [ ] test 3

## Precaution

## ✔️ Please check if the PR fulfills these requirements

- [ ] It's submitted to the correct branch, not the `develop` branch unconditionally?
- [ ] If on a hotfix branch, ensure it targets `main`?
- [ ] There are no warning message when you run `yarn lint`

2024-08-07 09:03 UTC, daepan requested changes
수고하셨습니다. Portal 사용 감사합니다 혹시 불편한 거 있으시면 알려주세용~
그리고 삭제 이후 UI 업데이트와 관련해서 한번 고민해봤으면 좋겠습니다
그리고 추가적으로 정렬과 관련해서 어떤 문제가 있는지 공유해주실 수 있나요?

2024-08-07 12:42 UTC, chaeseungyun commented on src/pages/Store/StoreDetailPage/Review/components/SelectButton/SelectButton.tsx
> +  };
아하 이 부분은 PortalProvider에는 queryClient가 존재하지 않기 때문에 portalManager를 사용한 컴포넌트에서는 useMutation을 사용할 수 없더라구요. 따라서 js는 렉시컬 스코프를 따르기 때문에 미리 선언하고 props로 전달했습니다

2024-08-07 12:48 UTC, chaeseungyun commented
현재 정렬과 관련해서 아래와 같은 문제점이 있습니다!

1. 클라이언트 내에서 정렬은 클라이언트가 가지고 있는 리스트만 정렬할 수 있다.
2. 따라서 두 번째 페이지를 가져올 때 첫 번째 페이지와 두 번째 페이지를 합치고 정렬을 진행하는데 이때 사용자가 원하는 순서를 보장할 수 없습니다.
3. 왜냐하면, 예를 들어 현재 최신순으로 정렬되어 있는데, 두 번째 페이지에 더 최신순의 데이터가 있다면 두 번째 페이지의 리뷰는 상단으로 올라갑니다. 그럼 새로 가져와진 데이터가 사용자에게 안보이는 현상이 생겨버립니다!

따라서 백엔드에게 정렬을 요청했고 곧 반영될 예정입니다.

리뷰를 업데이트하고(스크롤, 혹은 삭제 ,수정) 실제 리스트에 반영해야 하는데, 이때 setState를 사용해서 state를 업데이트하지 않으면 UI가 반영되지 않습니다.
그러면 데이터가 refetch 된 것을 감지하고 setState를 통해 리뷰를 업데이트해야 하는데, CRUD와 관련된 훅에 setState를 전달해야 하고 useEffect로 데이터를 관찰해야하는 불필요한 리소스가 있습니다. 이 부분은 백엔드에서 정렬을 진행해준다면 단순히 쿼리키를 무효화 시키는 것 만으로 UI가 업데이트 될 것으로 기대하고 있습니다!! API가 나오는대로 반영하겠습니다

2024-08-07 12:49 UTC, chaeseungyun commented on src/pages/Store/StoreDetailPage/Review/components/SelectButton/SelectButton.tsx
> +  };
새로고침 후 UI가 업데이트 되는 부분은 setState를 실행하지 않고 있기 때문입니다.
백엔드 api가 변경되는 대로 반영할 예정입니다

2024-08-08 05:07 UTC, chaeseungyun commented
업데이트된 API 반영 완료했습니다
코드가 훨씬 깔끔해졌군요

2024-08-08 05:48 UTC, daepan approved these changes
수고하셨습니다

2024-08-08 07:21 UTC, merged