시간표 PC 페이지 추가
BCSDLab/KOIN_WEB_RECODE pull request #40
Opened 2023-04-03 03:52 UTC by SimYunSup

## [#1 ] request

- 시간표 메인 페이지 PC 추가.
  - recoil 모듈로 비회원 일경우 구현.
  - tanstack query를 통해 회원일 경우를 구현.
  - Suspense로 감싸 서버 상태를 가져올 때 loading이라고 보여주기를 구현.

## Please check if the PR fulfills these requirements

- [x] It's submitted to `develop` branch, __not__ the `main` branch
- [x] The commit message follows our guidelines
- [x] There are no warning message when you run `yarn lint`
- [x] Docs updated for breaking changes

### Screenshot

![1](https://user-images.githubusercontent.com/47362439/229407337-6b56d8e7-5335-4ef2-a9bd-e2c4142d6f12.png)

2023-04-05 04:48 UTC, ChoiWonBeen requested changes
고생하셨습니다~ 코드가 꽤 길어서 오류가 수정되면 UI를 보면서 체크를 하게 될 것 같네요.
궁금한 점도 몇가지 올려두었고, 아래 오류사항 변경되면 다시 리뷰하겠습니다..!

2023-04-05 04:48 UTC, ChoiWonBeen commented on src/App.tsx
> +const useTokenState = () => useRecoilValue(tokenState);
tokenState가 정해지지 않아 에러가 발생합니다.

2023-04-05 04:48 UTC, ChoiWonBeen commented on src/utils/recoil/index.ts
> +  default: getCookie('AUTH_TOKEN_KEY'),
토큰의 기본값을 cookie로 초기화하는게 좋은 아이디어인 것 같네요

2023-04-05 04:48 UTC, ChoiWonBeen commented on src/utils/ts/apiClient.ts
> +export default class APIClient {
모듈의 export 선언부가 변경되어 이를 맞춰서 수정한 `timeTable, dept, auth`에는 에러가 발생하지 않지만, Merge과정에서 추가된 `bus, room, store`는 적용되지 않아 해당 코드들에 에러가 발생해서 빌드가 불가능합니다.

2023-04-05 04:48 UTC, ChoiWonBeen commented on src/api/timetable/index.ts
> +export const getTimeTableInfo = APIClient.of(TimetableInfo);
막 엄청 중요한것은 아니겠지만 `TimeTable`과 `Timetable`중 확실하게 하는게 좋을것같아요
파일이름들은 `Timetable`인데 몇몇 함수는 구분이 되지 않고 그러네요

2023-04-05 04:48 UTC, ChoiWonBeen commented on src/components/common/ErrorBoundary/index.tsx
> +export default class ErrorBoundary extends React.Component<Props, State> {
에러바운더리 컴포넌트를 직접 만들었네요? 만든거에 두가지 궁금증이 생겼는데..
1. 함수형이 아닌 class형으로 만든 이유가 있나요?
2. React에서 제공하는 `<ErrorBoundary />`를 사용하지 않는 이유가 있나요? fallback 컴포넌트에 해당 에러를 띄울 수 없었을지 궁금하네요

2023-04-05 04:48 UTC, ChoiWonBeen commented on src/index.tsx
> +      },
모든 쿼리 요청의 에러 발생 시 네트워크 연결을 확인해달라는 에러가 발생하게 되는 것일까요?
500대 에러가 아닌 상황에 대해서는 괜찮은지 궁금합니다..!

2023-04-05 04:48 UTC, ChoiWonBeen commented on src/interfaces/APIRequest.ts
> +export type HTTPMethod = typeof HTTP_METHOD[keyof typeof HTTP_METHOD];
해당 변수의 export 위치 변경도 확인해야 할 것 같습니다.

2023-04-06 10:49 UTC, SimYunSup commented on src/components/common/ErrorBoundary/index.tsx
> +export default class ErrorBoundary extends React.Component<Props, State> {
1. class형에서만 componentDidCatch을 사용할 수 있습니다.
2. 제공하지 않습니다.

2023-04-07 16:03 UTC, ChoiWonBeen commented on src/components/TimetablePage/DefaultPage/index.tsx
> +          <h3 className={styles['page__title--sub']}>나의 시간표</h3>
`font-weight: 800`이 빠진 것 같아요.

2023-04-07 16:37 UTC, ChoiWonBeen commented on src/components/TimetablePage/DefaultPage/index.tsx
> +              <React.Suspense fallback="loading...">
Bus쪽 코드에서는 `LoadingSpinner` svg파일을 활용해 fallback component를 구성했는데, 활용해보는건 어떨까요?
```ts
import { ReactComponent as LoadingSpinner } from 'assets/svg/loading-spinner.svg';
```
```suggestion
              <React.Suspense fallback={<LoadingSpinner />}>
```

2023-04-07 16:39 UTC, ChoiWonBeen commented on src/components/TimetablePage/LectureTable/index.tsx
> +                  </button>
`siba...`...ㅋㅋㅋㅋㅋㅋㅋㅋㅋ
혹시 내림차순 구현을 구상하다가 이렇게 된 걸까요.....ㅋㅋㅋ
일단 라벨은 지우고 내림차순 구현 가능 여부는 어떻게 될까요?

2023-04-07 16:45 UTC, ChoiWonBeen commented on src/components/TimetablePage/Timetable/index.tsx
> +export const TIMETABLE_ID = 'timetable-id';
같은 상수들이니 UPPER_CASE로 통일하는 쪽도 좋아보여요.
table의 셀 width값도 그렇고 은근히 상수 사용이 잦은 것 같으니 `static/`폴더에 분리해 모아두는것도 괜찮지 않을까 싶네요

2023-04-08 08:09 UTC, SimYunSup commented on src/index.tsx
> +      },
onError를 사용하지 않는 경우에 해당 onError가 작동하는 것입니다. 500대 에러가 아닌 상황을 가정하고 만든 것이 아니라 query hooks를 만들 때 onError를 만들지 않는 경우에 만든 것입니다.

2023-04-08 08:25 UTC, SimYunSup commented on src/components/TimetablePage/DefaultPage/index.tsx
> +              <React.Suspense fallback="loading...">
해당 부분에는 스피너보다는 스켈레톤이 어울릴 것 같아 이렇게 작성하게 되었습니다. 이후 구현을 목표로 두는 것이 좋을 것으로 보입니다.

2023-04-08 08:34 UTC, SimYunSup commented on src/components/TimetablePage/DefaultPage/index.tsx
> +        )}
이 패턴은 Button이라는 컴포넌트를 새로 넘겨도 되지만 react-windows의 방식을 갖고올 수 있겠다고 생각하여 갖고오게 되었습니다. 따로 컴포넌트를 두는 것도 좋지만 합치는게 더 보기 쉽다고 생각해서요.

2023-04-08 08:35 UTC, SimYunSup commented on src/components/TimetablePage/LectureTable/index.tsx
> +                  </button>
내림차순 구현은 시간이 좀 걸릴 것 같아 따로 이슈로 두겠습니다.

2023-04-09 12:23 UTC, daepan approved these changes
확실히 코드량이 많아서 보기 힘드네요. 코드에 궁금한 점 몇개만 적어봤습니다. 
한번 읽어주시고 댓글해주시면 감사하겠습니다.

2023-04-09 12:23 UTC, daepan commented on src/components/TimetablePage/DefaultPage/index.tsx
> +  const selectedLecture = useRecoilValue(selectedTempLectureSelector);
1. token을 recoil에 따로 저장하신 이유가 있을까요?
2. 시간표에서 recoilValue를 많이 사용하셨는데 어떤 이유에서 많이 사용하신지 궁금합니다

2023-04-09 12:23 UTC, daepan commented on src/components/TimetablePage/LectureTable/index.tsx
> +] as const;
상수는 따로 Static에 빼도 괜찮을 것 같습니다.

2023-04-09 13:10 UTC, SimYunSup commented on src/components/TimetablePage/DefaultPage/index.tsx
> +  const selectedLecture = useRecoilValue(selectedTempLectureSelector);
1. token을 recoil에 따로 저장한 이유는 다른 곳에서 재사용하기 좋게 하기 위해 recoil에 저장했습니다. 다른 방법이 있다면 제시해주세요.
2. 많이 사용한 이유는 props drilling을 피하기 위해 전역 저장소를 사용하기 위해 recoilValue를 사용했다고 볼 수 있습니다. `useRecoilValue`를 많이 사용한 이유를 물어보신거라면 setter를 사용하지 않았기 때문에 사용하였다고 볼 수 있습니다.

2023-05-24 04:45 UTC, ChoiWonBeen approved these changes

2023-05-24 05:17 UTC, merged