[주변상점] 리뷰 신고하기 기능 추가
BCSDLab/KOIN_WEB_RECODE pull request #402
Opened 2024-08-07 09:14 UTC by hoooooony

- Close #368 
  
## What is this PR? 🔍

- 기능 : 리뷰 신고하기 기능 추가
- issue : #368 

## Changes 📝

리뷰 신고하기 기능의 추가되었습니다.
ui와 동작 방식 확인해주세요.

## ScreenShot 📷

<img width="1047" alt="image" src="https://github.com/user-attachments/assets/8d5d9f90-7015-40b6-b7d0-b72e6dafaf9a">
<img width="485" alt="image" src="https://github.com/user-attachments/assets/5ed89ffd-78dd-4fdf-a3c4-dba4cbf8ba79">
<img width="399" alt="image" src="https://github.com/user-attachments/assets/2b827ea5-733a-4eb3-ba20-ff93b49c8950">
<img width="470" alt="image" src="https://github.com/user-attachments/assets/ad010038-b936-4724-9462-8e85323a272f">

## Test CheckList ✅

- [x]  선택 버튼으로 여러개 선택가능
- [x] 비로그인 시 로그인 유도 모달 
- [x] 신고하기 버튼 submit 후 이전 페이지 이동

## Precaution

## ✔️ Please check if the PR fulfills these requirements

- [ ] It's submitted to the correct branch, not the `develop` branch unconditionally?
- [ ] If on a hotfix branch, ensure it targets `main`?
- [ ] There are no warning message when you run `yarn lint`

2024-08-07 09:34 UTC, daepan requested changes
제가 신고하기 쪽 기획에서 좀 놓치는게 있어서 맞는건가 하는 생각으로 댓글 적어봤습니다.
읽어보시고 답변주시면 감사하겠습니다.

2024-08-07 09:34 UTC, daepan commented on src/pages/Store/StoreDetailPage/Review/components/ReviewReporting/query/useReviewReport.ts
> +      // queryClient.invalidateQueries('reviews');
이 주석은 뭔가요?

2024-08-07 09:34 UTC, daepan commented on src/pages/Store/StoreDetailPage/Review/components/ReviewReporting/query/getContent.ts
> +}
이거 굳이 함수형 쓰신 이유가 있을까요?
아래에도 동일한 형식의 getTitle이 있는데 REVIEW_CONTEXT라는 상수 하나 선언해서 notRelaevant 와 같은 문자열을 키값으로 cotent, title 을 들고 있게 하면 하나의 객체로 관리하면 나중에 따로 정적으로 생성해도 문제 없게 사용하지 않을까요?

2024-08-07 09:34 UTC, daepan commented on src/pages/Store/StoreDetailPage/Review/components/ReviewReporting/index.tsx
> +        </div>
상수로 선언하면 여기서도 활용 가능하겠네요

2024-08-07 09:34 UTC, daepan commented on src/static/category.ts
> +export type SubmenuTitle = '공지사항' | '버스/교통' | '식단' | '시간표' | '복덕방' | '주변상점' | '코인 for Business' | '리뷰 작성하기' | '리뷰 수정하기' | '리뷰 신고하기';
이거 추가되면 header에 들어가지 않나요? 헤더 통해서 들어가면 id 들어가나요?

2024-08-07 15:41 UTC, hoooooony commented on src/static/category.ts
> +export type SubmenuTitle = '공지사항' | '버스/교통' | '식단' | '시간표' | '복덕방' | '주변상점' | '코인 for Business' | '리뷰 작성하기' | '리뷰 수정하기' | '리뷰 신고하기';
헤더에는 나오지 않도록 매핑함수에 -2를 줘서 안 나오도록 하였습니다.

2024-08-07 15:44 UTC, hoooooony commented on src/pages/Store/StoreDetailPage/Review/components/ReviewReporting/query/getContent.ts
> +}
신고하기 요청시에 [{title:, content:}]구조에서 스트링으로 값을 하나씩 주려고 하다보니 따로 작성 했던 것 같습니다. 수정 보완해서 아래 코드도 수정해보겠습니다.

2024-08-07 15:46 UTC, hoooooony commented on src/pages/Store/StoreDetailPage/Review/components/ReviewReporting/index.tsx
> +        </div>
title,description을 REVIEW_CONTEXT.title, REVIEW_CONTEXT.content로 활용하는게 올바른 방법이라고 이해하면 될까요?

2024-08-08 00:04 UTC, MinGu-Jeong commented on src/pages/Store/StoreDetailPage/Review/components/ReviewReporting/ReviewReporting.module.scss
> +
클래스를 다 따로 정의하는게 아니라 `reporting`이라는 block을 만들고 각 element를 만들어서 사용할 수 있지 않을까요?

2024-08-08 00:06 UTC, MinGu-Jeong commented on src/pages/Store/StoreDetailPage/Review/components/ReviewReporting/index.tsx
> +  const params = useParams<{ shopid: string; reviewid: string }>();
shopid가 실제로 string인가요? id라서 number일줄 알았네요

2024-08-08 00:08 UTC, MinGu-Jeong commented on src/pages/Store/StoreDetailPage/Review/components/ReviewReporting/index.tsx
> +      textareaRef.current.style.height = `${textareaRef.current.scrollHeight - 10}px`;
이렇게 작성하면 아랫부분의 height만 적용되는거 아닌가요..?

2024-08-08 01:44 UTC, chaeseungyun commented on src/api/store/entity.ts
> +
`{
    title: string;
    content: string;
}[]` 과 차이가 있나요?

2024-08-08 01:44 UTC, chaeseungyun commented on src/pages/Store/StoreDetailPage/Review/components/ReviewReporting/index.tsx
> +  const params = useParams<{ shopid: string; reviewid: string }>();
useParams는 문자열을 반환합니다

2024-08-08 03:51 UTC, hoooooony commented on src/api/store/entity.ts
> +
차이는 없는걸로 알고 있습니다.

2024-08-08 03:52 UTC, hoooooony commented on src/pages/Store/StoreDetailPage/Review/components/ReviewReporting/index.tsx
> +      textareaRef.current.style.height = `${textareaRef.current.scrollHeight - 10}px`;
글을 작성하면 아래로만 길어지면 되는거 아닌가요?

2024-08-08 03:54 UTC, hoooooony commented on src/pages/Store/StoreDetailPage/Review/components/ReviewReporting/ReviewReporting.module.scss
> +
element라고 하면 --을 사용하는 부분을 말씀하신걸까요?
전 element는 진짜 말그대로 요소라고 생각해서 input, text, label 요렇게 사용하는게 맞다고 생각해서 위처럼 작성했던 것 같습니다.

2024-08-08 05:07 UTC, hoooooony commented on src/pages/Store/StoreDetailPage/Review/components/ReviewReporting/query/getContent.ts
> +}
수정했습니다1

2024-08-08 05:10 UTC, hoooooony commented on src/pages/Store/StoreDetailPage/Review/components/ReviewReporting/query/useReviewReport.ts
> +      // queryClient.invalidateQueries('reviews');
reviewReport로 쿼리키 추가했습니다.

2024-08-08 05:50 UTC, daepan commented on src/pages/Store/StoreDetailPage/Review/components/ReviewReporting/index.tsx
> +        </div>
뭐가 옳다 그르다는 아닙니다만, 저의 생각에서는 반복되는 구조이니 간단하게 반복문 처리해두며 앞으로의 유지보수에 용이하지 않을까라는 생각입니다.

2024-08-08 05:54 UTC, daepan requested changes
잘 수행해주셨는데 일부 제가 말했던 것과는 조금 이해가 엇나간 부분이 있었는데 subtitle에 굳이 추가된 이유가 궁금합니다

2024-08-08 05:54 UTC, daepan commented on src/static/category.ts
> +export type SubmenuTitle = '공지사항' | '버스/교통' | '식단' | '시간표' | '복덕방' | '주변상점' | '코인 for Business' | '리뷰 작성하기' | '리뷰 수정하기' | '리뷰 신고하기';
안나오게 하는데 이 코드에 이런 변화를 준 이유가 무엇인가요?

2024-08-08 05:54 UTC, daepan commented on src/pages/Store/StoreDetailPage/Review/components/ReviewReporting/index.tsx
> +        ))}
객체와 관련되어서 배열을 어떻게 처리할지 궁금했는데 잘 수행해주셨네요 앞으로 Reivew 내용이 추가된다면 객체만 수정하면 되겠네요

2024-08-08 05:59 UTC, hoooooony commented on src/static/category.ts
> +export type SubmenuTitle = '공지사항' | '버스/교통' | '식단' | '시간표' | '복덕방' | '주변상점' | '코인 for Business' | '리뷰 작성하기' | '리뷰 수정하기' | '리뷰 신고하기';
헤더에 리뷰 신고 제목이 나오도록하기 위해서 이렇게 작성하였습니다!

2024-08-08 06:19 UTC, daepan approved these changes
수고하셨습니다

2024-08-08 06:27 UTC, merged