[식단 페이지] 식단 페이지 제작
BCSDLab/KOIN_WEB_RECODE pull request #55
Opened 2023-06-25 09:02 UTC by SimYunSup

## [#31] request

- 식단 페이지 제작

## Please check if the PR fulfills these requirements

- [x] It's submitted to `develop` branch, __not__ the `main` branch
- [x] The commit message follows our guidelines
- [x] There are no warning message when you run `yarn lint`
- [x] Docs updated for breaking changes

### Screenshot
![스크린샷 2023-06-25 오후 6 01 30](https://github.com/BCSDLab/KOIN_WEB_RECODE/assets/47362439/53057415-0812-4d46-a207-826cc1c9825e)
![스크린샷 2023-06-25 오후 6 02 01](https://github.com/BCSDLab/KOIN_WEB_RECODE/assets/47362439/2c9fa1a4-da05-44f2-be05-cff9de1e1383)

2023-06-26 04:48 UTC, ChoiWonBeen requested changes
<img width="668" alt="image" src="https://github.com/BCSDLab/KOIN_WEB_RECODE/assets/50780281/bbbb2d8d-e093-4fd3-940c-63e510dd01ab">

UI가 너무 대놓고 다른 부분들이 많아서..
PC부분은 모바일과 동일하게 가져가도 괜찮을 것 같은데
구분선 표시나 2캠/능수관의 색상변환은 챙겨가는게 좋을 것 같네요

2023-06-26 04:48 UTC, ChoiWonBeen commented on src/pages/Cafeteria/CafeteriaPage/index.tsx
> +                  const currentTimeMenu = data ? Array.from(data).find(
해당 장소에 식단이 없다면 "미운영" 같은 표시를 추가하거나
아예 탭을 지우는 것도 괜찮을 것 같아요

2023-07-24 12:09 UTC, daepan approved these changes
수고하셨습니다.

2024-01-08 15:21 UTC, ChoiWonBeen approved these changes

2024-01-08 15:25 UTC, merged