[refacotor]: 주변 상점 업데이트 관련 로직 수정
BCSDLab/KOIN_WEB_RECODE pull request #56
Opened 2023-06-25 09:03 UTC by daepan

## [Copy here issue number] request

## Please check if the PR fulfills these requirements

- [ ] It's submitted to `develop` branch, __not__ the `main` branch
- [ ] The commit message follows our guidelines
- [ ] There are no warning message when you run `yarn lint`
- [ ] Docs updated for breaking changes

### Screenshot

2023-06-26 03:41 UTC, ChoiWonBeen requested changes

2023-06-26 03:41 UTC, ChoiWonBeen commented on src/pages/Store/StoreDetailPage/hooks/useStoreDetail.ts
> +    storeDetail: isStoreDetailError ? null : storeDetail,
에러?상황에대해서 이런저런 로직을 작성해둿는데 에러 발생이 기대되는 로직일까요? `undefined | Type` 으로 추론되면 안되는 이유가 있을까 궁금해서 여쭤봅니다

2023-06-26 03:41 UTC, ChoiWonBeen commented on src/pages/Store/StoreDetailPage/hooks/useStoreDetail.ts
> +const useStoreDetail = (params: string) => {
params라고만 작성하니 어떤 값이 인자로 들어올지 해석하기 어렵다는 생각이 드는데 id라면 id같이 작성하는건 어떨까요?

2023-06-26 03:41 UTC, ChoiWonBeen commented on src/pages/Store/StoreDetailPage/index.tsx
> +  const { storeMenus } = useStoreMenus(params.id ?? '');
이 페이지의 라우팅이 파라미터로 id가 있어야만 하므로 id가 있다고 단언하는건 어떨까요?
```suggestion
  const { storeDetail, storeDescription } = useStoreDetail(params.id!);
  const { storeMenus } = useStoreMenus(params.id!);
```

바꾼다면 동시에 Number형으로도 바꾸고 싶다는 욕구가 동시에 드네요 ㅋㅋ

2023-06-26 03:41 UTC, ChoiWonBeen commented on src/pages/Store/StoreDetailPage/index.tsx
> +                      <span>{ !!menu.option_prices && menu.option_prices[0].price.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ',') }</span>
option_price가 있을 때 렌더링되는 부분이니깐 불필요한 조건일 것 같아요

2023-06-26 03:41 UTC, ChoiWonBeen commented on src/pages/Store/StorePage/index.tsx
> +const isOpenStore = (open_time: string | null, close_time : string | null) => {
저어는 개인적으로 `isStoreOpen`파 입니다ㅋㅋ

2023-07-25 00:53 UTC, SimYunSup commented on src/pages/Store/StoreDetailPage/hooks/useStoreDetail.ts
> +    storeDetail: isStoreDetailError ? null : storeDetail,
두가지 궁금한 점이 있습니다.
1. 추적은 `isError`가 도와주는데 이를 반환하면 되는 것 아닌가요?
2. storeDetail에 storeDescription을 합쳐서 보내면 반환 값이 더 일반적으로 될 거 같은데 그렇게 하지 않은 이유는 무엇인가요?

2023-07-25 07:07 UTC, daepan commented on src/pages/Store/StoreDetailPage/hooks/useStoreDetail.ts
> +    storeDetail: isStoreDetailError ? null : storeDetail,
1. isError로 에러를 반환받는 것보다는 null을 통해서 페이지가 다운되는 현상을 방지하기 위해서라고 말씀드릴 수 있겠습니다. 혹시나 null인 경우에는 페이지 에러를 반환하는 페이지보다는 무언가 빈화면을 통해 최대한 앱이 지속되는 현상을 원해서입니다.
2. storeDescription은 단순히 제가 중간에 storeDetail.description 쓰는 것과 같이 ~~.~~. 형식을 선호하지 않아서 입니다.

2023-07-25 07:10 UTC, daepan commented on src/pages/Store/StoreDetailPage/hooks/useStoreDetail.ts
> +    storeDetail: isStoreDetailError ? null : storeDetail,
2번 추가 +) 그리고 설명문 과정에서 필터링하는 과정이 있어이를 코드 내부에 쓰는것도 지양하는 목적이 큽니다.

2023-07-25 07:20 UTC, SimYunSup commented on src/pages/Store/StoreDetailPage/hooks/useStoreDetail.ts
> +    storeDetail: isStoreDetailError ? null : storeDetail,
1. `isError로 분기처리하는 것`과 `null을 통해서 분기처리하는 것`
2. 단순하게 형식을 선호하지 않는 것은 알겠지만 훅으로 분리되어있는 상태에서 컴포넌트의 코드만 보고 `storeDescription`이 `storeDetail`에서 파생되었다라고 생각하기 어렵습니다. 그래서 저는 storeDetail에 모두 합쳐서 보내는 것을 권장드립니다.
3. `storeDetail?.phone`과 `storeDescription`이 공존하는 형식은 체이닝 형식을 선호하지 않아서라고 보기에 어렵습니다. 하나로 통일하는 것이 좋다고 생각합니다.

2024-01-08 15:26 UTC, ChoiWonBeen approved these changes

2024-01-08 15:26 UTC, merged