[비즈니스] 이벤트 배너 개편
BCSDLab/KOIN_WEB_RECODE pull request #570
Opened 2024-11-07 00:49 UTC by chaeseungyun

## Changes 📝

이벤트 배너의 UI가 변경됩니다.

pc 버전
1. 무조건 2개의 이벤트를 보여주도록 합니다.
2. 이벤트가 홀수개라면 코인 이벤트라는 기본 이미지를 추가해서 보여줍니다.
3. 스크롤 혹은 버튼을 클릭해서 이벤트를 넘겨볼 수 있습니다.

모바일 버전
1. 배너 하단에 페이지네이션이 추가됩니다.
2. 이벤트는 최대 10개만 볼 수 있습니다.
3. 스크롤 혹은 버튼을 클릭해서 이벤트를 넘겨볼 수 있습니다.

## ScreenShot 📷

![image](https://github.com/user-attachments/assets/941fba73-54ff-421e-bb99-0c75dabe08fb)
![image](https://github.com/user-attachments/assets/1dd12f7a-d68f-4e15-a2bf-ae203d6dca61)

## Precaution

## ✔️ Please check if the PR fulfills these requirements

- [ ] It's submitted to the correct branch, not the `develop` branch unconditionally?
- [ ] If on a hotfix branch, ensure it targets `main`?
- [ ] There are no warning message when you run `yarn lint`

2024-11-07 02:29 UTC, hyejun0228 reviewed
수고하셨습니다~! 👍
배너 방향 버튼을 누를 때 5번째..? 마다 몇페이지씩 넘어갑니다! 확인해주시면 좋을 것 같아요!

2024-11-07 02:29 UTC, hyejun0228 commented on src/pages/Store/StorePage/components/EventCarousel/index.tsx
> +import RightBracket from 'assets/svg/right-angle-bracket.svg';
이름을 통일해준다면 더 좋을 것 같습니다~!

2024-11-07 02:29 UTC, hyejun0228 commented on src/pages/Store/StorePage/components/EventCarousel/index.tsx
> +  const [canNextClick, setCanNextClick] = useState(false);
`useBooleanState` 를 사용해주신다면 더 좋을 것 같습니다!

2024-11-07 02:29 UTC, hyejun0228 commented on src/pages/Store/StorePage/components/EventCarousel/index.tsx
> +  }, [emblaApi]);
중복된 코드가 보이는 것 같습니다! 밑의 방식은 어떠신가요? 

```ts
const scrollTo = useCallback((direction: 'prev' | 'next') => {
  if (emblaApi) {
    direction === 'prev' ? emblaApi.scrollPrev() : emblaApi.scrollNext();
  }
}, [emblaApi]);

```

2024-11-07 02:29 UTC, hyejun0228 commented on src/pages/Store/StorePage/components/EventCarousel/index.tsx
> +          </button>
제가 느끼기에는 버튼의 범위가 좁은것같아요 버튼의 높이를 배너와 맞춰주는건 어떨까요??!

2024-11-13 18:43 UTC, SimYunSup requested changes

2024-11-13 18:43 UTC, SimYunSup commented on src/pages/Store/StorePage/components/EventCarousel/index.tsx
> +        !isMobile && canPrevClick && (
https://tkdodo.eu/blog/component-composition-is-great-btw

읽고 어떤 생각을 통해서 만들었는지 소개해주세요.

2024-11-13 18:43 UTC, SimYunSup commented on src/pages/Store/StorePage/components/EventCarousel/index.tsx
> +    </EventCarouselWrapper>
`Wrapper`와 `Carousel`이 분리된 이유를 설명해주세요.

2024-11-13 18:43 UTC, SimYunSup commented on src/pages/Store/StorePage/components/EventCarousel/index.tsx
> +    emblaApi.on('slidesInView', updateIndex);
embla 예시중에서 이런 예시를 보지 못해서 그런데, 어떤 이유에서 `slideInView`에 구독했는지 알 수 있을까요?

2024-11-14 00:23 UTC, chaeseungyun commented on src/pages/Store/StorePage/components/EventCarousel/index.tsx
> +    emblaApi.on('slidesInView', updateIndex);
autoplay 플러그인을 통해 스크롤 될때마다 현재 몇 번째 페이지인지 알기 위해 사용했습니다

2024-11-14 00:24 UTC, chaeseungyun commented on src/pages/Store/StorePage/components/EventCarousel/index.tsx
> +    </EventCarouselWrapper>
Wrapper에 페이지네이션을 하는 부분을 따로 분리했습니다
(다음 버튼, 이전 버튼)

2024-11-14 03:04 UTC, SimYunSup commented on src/pages/Store/StorePage/components/EventCarousel/index.tsx
> +    </EventCarouselWrapper>
단순히 "관심사의 분리"로 설명하지 마시고, 어떤 코그가 관심사가 같다고 생각하여 어떻게 분리하였는지 알려주세요.

2024-11-14 03:17 UTC, SimYunSup commented on src/pages/Store/StorePage/components/EventCarousel/index.tsx
> +    emblaApi.on('slidesInView', updateIndex);
`select`이벤트 대신 `slidesInView` 이벤트를 사용하신 이유은 무엇인가요?

2024-11-14 04:26 UTC, chaeseungyun commented on src/pages/Store/StorePage/components/EventCarousel/index.tsx
> +        !isMobile && canPrevClick && (
조기반환 이라는 것을 고려하지 않았습니다. 제가 사용하던 방식이 아니라 이런 방식이 떠오르지 않았어요.
컴포넌트를 작성할 때 한 개의 jsx만 반환한다라는 고정관념이 있었습니다. 따라서 위와 같이 작성했어요

공유해주신 글 덕분에 좋은 시야를 얻은 것 같습니다

2024-11-14 04:43 UTC, chaeseungyun commented on src/pages/Store/StorePage/components/EventCarousel/index.tsx
> +    emblaApi.on('slidesInView', updateIndex);
select 이벤트는 autoplay 플러그인에 의해 자동 스크롤 되는 것을 감지하지 못했습니다
그래서 slideInView 라고 하는 이벤트를 사용했습니다

2024-11-14 05:27 UTC, chaeseungyun commented on src/pages/Store/StorePage/components/EventCarousel/index.tsx
> +        !isMobile && canPrevClick && (
6bee8eb219f84d677ebac66cce2b4eadb5786572

공유해주신 아티클을 읽고 리팩토링 해봤습니다.

1. 캐러셀 관련 비즈니스 로직은 훅을 사용해서 분리했습니다.
2. 재사용 가능한 코드는 따로 컴포넌트를 만들어서 가독성을 향상 시켰습니다
3. pc, 모바일에 따라 요구사항이 조금씩 달라서 이벤트 캐러셀 자체의 레이아웃은 크게 건드리지 못했습니다

2024-11-14 05:29 UTC, chaeseungyun commented on src/pages/Store/StorePage/components/EventCarousel/index.tsx
> +    </EventCarouselWrapper>
wrapper는 페이지네이션 로직과 뷰를 담당하고
carosel은 이름 그대로 캐러셀 뷰를 담당한다고 생각했습니다.

따라서 위와 같이 분리하며 뷰와 로직이 분리되었다고 느껴서 작성했습니다. 그러나 다시 코드를 보니 저의 의도는 전혀 드러나지 않았더라구요

비즈니스 로직은 훅을 통해 분리했고, 재사용 가능한 뷰는 컴포넌트를 따로 만들어서 사용했습니다
early return으로 가독성을 조금 향상 시켜봤습니다

2024-11-14 05:33 UTC, SimYunSup commented on src/pages/Store/StorePage/components/EventCarousel/index.tsx
> +    emblaApi.on('slidesInView', updateIndex);
https://codesandbox.io/p/sandbox/embla-carousel-autoplay-react-forked-svdg92

안되는 코드와, 왜 안됐는지 다시 생각해보세요.

2024-11-14 05:54 UTC, SimYunSup commented on src/pages/Store/StorePage/components/EventCarousel/index.tsx
> +}
1. `key`가 필요한가요?
2. 값을 정규화하지 않고 그대로 넘겨주고 해당 컴포넌트에서 데이터를 수정하는 이유가 있을까요?

2024-11-14 05:54 UTC, SimYunSup commented on src/pages/Store/StorePage/components/EventCarousel/index.tsx
> +  const targetList = carouselList.length > 10 ? carouselList?.slice(0, 10) : carouselList;
필요한 코드인가요?

2024-11-14 06:04 UTC, chaeseungyun commented on src/pages/Store/StorePage/components/EventCarousel/index.tsx
> +  const targetList = carouselList.length > 10 ? carouselList?.slice(0, 10) : carouselList;
이벤트의 개수는 최대 10개만 보여준다라는 요구사항이 있었습니다.
백엔드에서는 개수 제한 없이 주기 때문에 slice를 통해 최대 10개로 제한했습니다.

2024-11-14 06:08 UTC, chaeseungyun commented on src/pages/Store/StorePage/components/EventCarousel/index.tsx
> +}
1. key는 Card를 호출할 때 할당해야 할 것 같습니다. 수정하겠습니다.
2. 사용하는 쪽에서 필요한대로 바꿔서 사용하는게 맞다라고 생각했습니다. 그냥 보여주는 것에 집중한다면 윤섭님 말대로 정규화된 값을 받아야겠네요! 수정하겠습니다

2024-11-14 08:38 UTC, SimYunSup commented on src/pages/Store/StorePage/components/EventCarousel/index.tsx
> +  const targetList = carouselList.length > 10 ? carouselList?.slice(0, 10) : carouselList;
`length`가 4인 배열을 `.slice(0, 10)`하면 `length`가 10이 되나요?

2024-11-14 08:39 UTC, SimYunSup approved these changes

2024-11-14 10:50 UTC, chaeseungyun commented on src/pages/Store/StorePage/components/EventCarousel/index.tsx
> +  const targetList = carouselList.length > 10 ? carouselList?.slice(0, 10) : carouselList;
아.. 오류가 날 것으로 생각했습니다
찾아봤어야 했는데.. 지적 감사합니다

2024-11-14 11:05 UTC, merged