[비즈니스] 리뷰하기 툴팁 기능 추가
BCSDLab/KOIN_WEB_RECODE pull request #576
Opened 2024-11-13 12:12 UTC by daepan

- Close #ISSUE_NUMBER
  
## What is this PR? 🔍

- 기능 : 
- issue : #

## Changes 📝

- 변경점
  - PC checkbox를 제거하고 모바일에 사용하는 체크 박스로 변경했어요 모바일 작업자 분이랑 스탭을 맞추기 위해 일단 네이밍을 그대로 해뒀습니다.
  - 리뷰하기를 페이지에서 유지하는게 아닌 메인페이지에서 클릭할때 리뷰하기 체크박스를 기본으로 설정해두었습니다. 그대로 할 경우 parameter로 인해 강제 리렌더링이 너무 자주발생하게 되고 새로고침시 사용자가 의도하지 않은 결과를 나올 수 있기에 첫 진입시에만 사용하였습니다.
  - 검색을 누를떄 shopV2의 storeName을 함께 넣어두거나 새로고침시 유지되도록 코드를 변경했습니다. 

## ScreenShot 📷

![image](https://github.com/user-attachments/assets/7f272cd5-ccbe-4633-ac08-100602a02a94)

## Test CheckList ✅

- [ ] test 1
- [ ] test 2
- [ ] test 3

## Precaution

## ✔️ Please check if the PR fulfills these requirements

- [ ] It's submitted to the correct branch, not the `develop` branch unconditionally?
- [ ] If on a hotfix branch, ensure it targets `main`?
- [ ] There are no warning message when you run `yarn lint`

2024-11-13 12:23 UTC, junghaesung79 reviewed
궁금한 점 코멘트 달아두었습니다! 고생하셨어요~

2024-11-13 12:23 UTC, junghaesung79 commented on src/pages/Store/StorePage/StorePage.module.scss
>        margin-right: 0;
이게 어떤 요소인지 여쭤봐도 될까요?

2024-11-13 12:23 UTC, junghaesung79 commented on src/pages/Store/StorePage/index.tsx
> +  };
혹시 localStorage에 아직 값이 저장되지 않았을 때를 상정한 `=== null`인가요? undefined? null?

2024-11-13 18:51 UTC, SimYunSup requested changes

2024-11-13 18:51 UTC, SimYunSup commented on src/pages/Store/StorePage/index.tsx
> +            isTooltipOpen && (
`tooltip`과 `Stacking Context`는 어떤 관계가 있고, 어떻게 하는 것이 최선의 방법일까요?

2024-11-13 18:51 UTC, SimYunSup commented on src/pages/Store/StorePage/index.tsx
> +              </div>
svg로 보이는데, CSS로 처리할 수 있는 부분입니다. 어떻게 해야하는지 검색해보세요.

2024-11-13 18:51 UTC, SimYunSup commented on src/pages/Store/StorePage/StorePage.module.scss
>        margin-right: 0;
추가할 때마다 바꿔야한다면, `:nth-child`를 사용하지 않도록 바꿔보세요.

2024-11-14 01:36 UTC, daepan commented on src/pages/Store/StorePage/StorePage.module.scss
>        margin-right: 0;
CSS 특정 요소가 부모 요소 내에서 몇 번째 자식인지에 따라 스타일을 적용할 수 있도록 해주는 가상 클래스입니다 요소의 위치나 순서에 따라서 적용할 수 있는 방식이라 다양하게 활용할 수 있는 문법입니다.

2024-11-14 01:50 UTC, daepan commented on src/pages/Store/StorePage/index.tsx
> +  };
localStorage.getItem()은 해당 키가 존재하지 않을 때 **null**을 반환하기에 위와 같은 로직을 작성했습니다.

2024-11-14 02:06 UTC, daepan commented on src/pages/Store/StorePage/index.tsx
> +            isTooltipOpen && (
tooltip은 보통 특정 요소 위에 떠 있는 형태로 나타나야 하므로, 적절한 stacking context와 z-index 설정이 필요하다고 생각하고 이 설정에는 2가지 방법이 있다고 생각합니다.
1 . tooltip이 특정 요소나 페이지의 모든 요소 위에 보여야 한다면, tooltip을 최상위 레이어로 분리하여 stacking context를 설정하거나
ex. z-index: 999
2 . tooltip의 상위 컨테이너에 position: relative나 position: absolute를 적용하여 stacking context를 생성하고, tooltip에 상대적인 위치와 z-index를 적용하는 방식으로, tooltip이 독립적인 레이어로 존재하게 되어 불필요한 영향을 줄일 수 있게 하는 방법이 있다고 생각합니다.

저는 이번 방식에 tooltip이 최상단에 위치해 동작이나 이동에 제한은 주어서는 안된다고 생각해서 2번 방식을 통해 부모 컴포넌트에서 relative와 absoulute를 통해 조절하는 방식을 채택했습니다.

2024-11-14 02:09 UTC, junghaesung79 commented on src/pages/Store/StorePage/StorePage.module.scss
>        margin-right: 0;
아아 제 질문은 여기에 나온 4번째 요소가 화면에서 어떤 요소인지를 묻는 것이었습니다! 실행하지 않고 코드만 보고 있어서 이런 질문을 했습니다!

2024-11-14 02:10 UTC, daepan commented on src/pages/Store/StorePage/index.tsx
> +              </div>
몇가지 방법이 있긴 한걸로 확인은 했는데 svg 보다는 css로 한다면 용량이나 리소스 반응형들에서 이득이 있을 수 있겠네요
하지만 CSS로 구현하다가 레거시 브라우저에 대한 대응력이 떨어질 수 있지 않을까요? svg는 큰 무리 없이 동작만 시킬 수 있을 것 같은데 이 부분에 대해서는 어떻게 생각하시는지 궁금합니다.

2024-11-14 02:10 UTC, daepan commented on src/pages/Store/StorePage/StorePage.module.scss
>        margin-right: 0;
last-child 같은 요소를 활용해보겠습니다.

2024-11-14 02:47 UTC, SimYunSup commented on src/pages/Store/StorePage/StorePage.module.scss
>        margin-right: 0;
선택자를 사용하지 말고 고쳐보세요.

2024-11-14 02:48 UTC, SimYunSup commented on src/pages/Store/StorePage/index.tsx
> +              </div>
검색하시고, 방법을 제시하시고, 어떤 방법의 어떤 기술이 레거시 브라우저 대응에 문제가 생기는지 알려주세요.

2024-11-14 03:03 UTC, SimYunSup commented on src/pages/Store/StorePage/index.tsx
> +            isTooltipOpen && (
1. tooltip이 최상단 레이어에 올라가면 어떤 동작과 어떤 방해를 받는지 알려주세요.
2. 2번이 최선인 방법이라고 생각하셨는데, 다른 툴팁 라이브러리는 어떤 방식을 채택하였는지, 왜 그런 선택을 했는지 알려주세요.

2024-11-14 04:09 UTC, daepan commented on src/pages/Store/StorePage/index.tsx
> +              </div>
만드는 방법으로는 말풍선 만드는 CSS를 작성해보는 사이트가 있더군요 [해당 사이트](https://projects.verou.me/bubbly/)를 참고해서 만들수도 있겠네요
레거시 웹 발생할만한 예시를 찾아봤는데 CSS가 안될 정도면 svg도 안되는 정도라더군요 위의 사이트에서 만들어보고 해당 코드를 가져와보는것이 의도하신 내용일까요?

2024-11-14 04:13 UTC, daepan commented on src/pages/Store/StorePage/StorePage.module.scss
>        margin-right: 0;
선택자 없이 간다면 2가지 방법이 떠오르긴 했습니다
1. gap 속성을 통해 이전에 margin 방식을 철회하는 것으로 진행
2. className cn 조건문을 통해 마지막 요소에 대한 조건부 처리
저는 gap 쪽을 통해 싹다 해놓는게 좋아보이는데 2번 방식에 대해서는 어떤가요?
이 2개 말고 다른 좋은 방식이 있을까요?

2024-11-14 04:14 UTC, daepan commented on src/pages/Store/StorePage/StorePage.module.scss
>        margin-right: 0;
상점 상단체 CheckBox 필터에 대한 코드입니다.

2024-11-14 04:16 UTC, daepan commented on src/pages/Store/StorePage/StorePage.module.scss
>        margin-right: 0;
<img width="1245" alt="image" src="https://github.com/user-attachments/assets/0e1e0682-7856-4c76-856f-bef3b3d06c97">

2024-11-14 05:04 UTC, daepan commented on src/pages/Store/StorePage/index.tsx
> +            isTooltipOpen && (
1. 최상단 레이어를 두고 움직이면 absolute 위치 문제로 다른 요소 클릭에 문제가 있을수도 있다고 생각했습니다. 특히 상단에 위치할 경우 absolute 위치 잡기가 매우 어렵기에 때문에 checkbox 부모 컴포넌트 밑으로 내려서 구현하였습니다.
2. 제가 구현한 것은 tooltip의 부모 요소가 특정 컨테이너에 한정되어 해당 컨테이너의 stacking context 내에서 위치를 지정하는 방식입니다. 이 방식은 툴팁이 부모 요소에 종속적이므로, 부모 요소의 z-index에 영향을 받을 수 있다는 단점이 있는 반면, react-tooltip은 화면의 전체 좌표를 기준으로 tooltip을 관리하므로 부모 요소의 stacking context 영향을 받지 않고, 최상단 레이어에서 독립적으로 동작한다고 합니다.

2024-11-14 05:09 UTC, daepan commented on src/pages/Store/StorePage/index.tsx
> +            isTooltipOpen && (
구현 방식의 경우에는 부모 요소의 stacking context에 영향을 받지 않고 화면의 전체 좌표를 기준으로 최적의 위치에 표시되도록 하기 위해 @floating-ui/dom 라이브러리의 computePosition 함수와 동적 위치 계산 및 업데이트를 사용합니다.
```js
import { computePosition } from '@floating-ui/dom';

computePosition(anchorElement, tooltipElement, {
  placement: 'top', // 원하는 기본 위치 지정
  middleware: [offset(10)], // 필요한 경우, 오프셋 적용
}).then(({ x, y }) => {
  tooltipElement.style.left = `${x}px`;
  tooltipElement.style.top = `${y}px`;
});
```
참고자료: https://github.com/ReactTooltip/react-tooltip/blob/master/src/utils/compute-tooltip-position.ts

2024-11-14 05:11 UTC, SimYunSup commented on src/pages/Store/StorePage/StorePage.module.scss
>        margin-right: 0;
본인이 생각하는 장단점을 설명해주시고, 선택해서 적용하시면 됩니다.

2024-11-14 05:13 UTC, SimYunSup commented on src/pages/Store/StorePage/index.tsx
> +              </div>
말씀하신대로 `::after` pesudo class는 오래전부터 지원해왔습니다. 포함한 svg 파일같이 간단한 모양을 요소에서 표현하는 방법 또한 여러가지가 있습니다. 한번 찾아보시고, 적용해보세요.

2024-11-14 05:29 UTC, daepan commented on src/pages/Store/StorePage/index.tsx
> +              </div>
clip-path를 통해 구현하는 방법도 있고 transform 함수로 구현하는 경우도 있더군요.
다양하게 활용할 수 있군요 위 3가지 방법 중에 골라보고 선택 배경은 나중에 문서로 공유해보겠습니다.

2024-11-14 05:31 UTC, daepan commented on src/pages/Store/StorePage/StorePage.module.scss
>        margin-right: 0;
개인적으로 반복요소라 className까지 필요없고 css로 간단하게 처리할 수 있는 문제라고 생각되는 군요 gap으로 한번 처리해보겠습니다.

2024-11-14 05:41 UTC, SimYunSup commented on src/pages/Store/StorePage/index.tsx
> +            isTooltipOpen && (
`최상단 레이어에 올리면 absolute 위치 설정이 어렵다`와 `다른 요소의 클릭에 문제가 생긴다`에 대한 근거가 부족합니다. 제시하신 `@floating-ui/dom`의 코드를 보시면 알겠지만, 코드의 양이 방대하지 않습니다.

두번째로는 최상단 레이어에서 다른 요소의 클릭 문제는 `z-index` 관리로 단순히 해결 가능한데, 만약 부모 요소의 레이어에 얹히게 된다면 그 상위 레이어나 부모 요소의 레이어의 CSS까지 고려해야 하는 상황이 생기는데, 이러면 후자가 더 문제 있을 가능성이 높아지는 것 아닌가요?

2024-11-14 05:55 UTC, daepan commented on src/pages/Store/StorePage/index.tsx
> +            isTooltipOpen && (
1번 부분에 대한 것은 제가 이전 최상단 absolute를 조절하기 어려웠던 경험에서 예상하지 못한 화면의 크기나 다양한 문제에 대해서 조절하기 어렵다고 생각했습니다. 그리고 당연히 제가 원하는 위치에 UI를 두지 못한다면 클릭 요소에 지장을 줄 수 있다고 생각했습니다.

제가 후자로 분석한 이유는 제가 작성했던 div이기에 위치 에러를 잘 고려하고 div 내부에서 position 컨트롤하기 쉬울 것 같다고 생각했었습니다.
`의존이 있기에 의존을 기준으로 맞추면 쉬울 것이다.`라는 생각에서 제가 후자를 더 좋게 평가했던 이유였습니다.

하지만 react-tooltip에서는 이를 해결하기 위해 floating-ui/dom 을 통해 위치를 잘 평가하고 있다면 말씀하셨던 상위 레이어를 고려하지 않아도 된다는 장점이 있다는 점을 이해했습니다.
물론 현재 페이지 내에서는 위의 방식이 먹힐지는 모르지만, 앞으로 툴팁 기능이 더욱 추가된다면 react-tooltip의 방식을 우리 도메인에 맞게 도입할 필요가 있다고 생각이 듭니다.

2024-11-14 09:44 UTC, daepan commented on src/pages/Store/StorePage/StorePage.module.scss
>        margin-right: 0;
[8735ab6](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/576/commits/8735ab6153e7e751f9d134eb505797f9196cdfe6)
gap으로 처리하려고 헀는데 이게 먹히지 않더군요.. 요소가 분할되어 있고, div가 잘 묶여있지 않아 UI가 일그러지더군요.
className으로 index 와 checkBox 길이로 마지막 요소에 대한 조건문을 판별하여 margin-right: 0가 되도록 처리하였습니다.

2024-11-14 09:45 UTC, SimYunSup commented on src/pages/Store/StorePage/index.tsx
> +            isTooltipOpen && (
`overlay` 패턴들은 최상단에서 주의하도록 보여줘야 하므로 일정 조건을 만족하지 않으면 부모의 `stacking context`에 종속되는 것은 임시방편이 될 확률이 높습니다. 부모 요소가 최상단에 있는게 보장되어있는 경우(딱히 겹침을 관리하지 않아도 됨), `overflow: hidden;`을 사용하지 않는 것이 보장되어 있는 경우(사용하게 되면 안 보임)이 아니라면 이후 레이어가 겹치게 되면 모든 겹치는 레이어에 대해 보고 고쳐야 합니다. 현재 기능에서 캐러셸이 바로 밑에 있는데, 만약 캐러셸의 레이어가 현재 위치보다 상위 레이어에 있었다면, 캐러셸의 `z-index`도 함께 관리해야 할 상황이 발생할 수 있습니다. 이러한 경우, 캐러셸과 tooltip의 레이어가 겹칠 가능성이 높아지는데, 이를 방지할 레이어 관리를 생각해두셨나요?

`tooltip` 기능이 추가되게 되면 고려해야 할 부분이 아니라, 요구사항에 따라 구현해야 할 부분입니다.

2024-11-14 10:10 UTC, SimYunSup approved these changes

2024-11-14 10:47 UTC, merged