[시간표] 모달 닫힘 관련 이슈 & 직접 추가 24:30까지 추가 가능했던 이슈
BCSDLab/KOIN_WEB_RECODE pull request #587
Opened 2024-11-23 14:48 UTC by Gwak-Seungju

- Close #586 
  
## What is this PR? 🔍

- 기능 : 이슈 해결
- issue : #586 

## Changes 📝

- 직접 추가 페이지에서 24:30분까지 추가 가능했던 것을 방지하기 위해 endtime을 30분으로 선택했을 시 endhour를 23시까지만 선택가능하도록 수정했습니다.
- 시간표 페이지에서 사용하고 있는 모달에서 바깥을 클릭 시 닫히지 않았던 부분들을 모두 수정했습니다.
- 모달이 열린 상태로 뒤로가기 클릭 시 모달이 그대로 열려 있는 이슈를 해결했습니다.
- 함수 호출 위치 리팩토링

## ✔️ Please check if the PR fulfills these requirements

- [ ] It's submitted to the correct branch, not the `develop` branch unconditionally?
- [ ] If on a hotfix branch, ensure it targets `main`?
- [ ] There are no warning message when you run `yarn lint`

2024-11-24 16:25 UTC, daepan requested changes
수고하셨습니다. 상수 선언에 대한 궁금증 하나 남겨둘게요!

2024-11-24 16:25 UTC, daepan commented on src/pages/TimetablePage/components/SemesterList/DeleteSemesterModal/index.tsx
>            <span className={styles.container__title}>학기를 삭제하시겠습니까?</span>
여기서 따로 훅을 사용하지 않은 이유는 state 관리 때문이군요
나중에 State를 관리할 수 있는 방법을 생각해야겠군요...

2024-11-25 04:32 UTC, Yejin0070 reviewed
수고하셨습니다!!

2024-11-25 14:09 UTC, Gwak-Seungju commented on src/pages/TimetablePage/components/SemesterList/AddSemesterModal/index.tsx
> +
매년 업데이트하여 정적으로 사용할 경우에는 상수로 빼도 될 것 같네요! 변수로 선언했던 이유는... 상수로 선언할 생각을 못했던 것 같습니다...!

2024-11-29 15:07 UTC, daepan approved these changes
잘 수정해주시고 넣어주세요~

2024-11-29 15:21 UTC, Gwak-Seungju commented on src/pages/TimetablePage/components/SemesterList/AddSemesterModal/index.tsx
> +
`getFullYear` 사용을 생각하지 못했네요..! 감사합니다! 수정했습니다 77bdbc40dc7e40e88aad714f5a028d0265153fee

2024-11-29 15:21 UTC, merged