Feat/#575/update lecture
BCSDLab/KOIN_WEB_RECODE pull request #601
Opened 2024-12-03 18:29 UTC by Yejin0070

- Close #575 
  
## What is this PR? 🔍

- 기능 : 강의 수정 기능 추가
- issue : #575 

## Changes 📝

1. 강의 수정 버튼 svg 추가 및 삭제 버튼 svg 교체
2. 강의 수정 페이지로 이동
3. 클릭한 강의 정보 불러오기
4. 정규과목 강의 수정 시 UI 수정
5. EditLectureInfo API Class 추가
6. 비로그인 시 로직 처리

## ScreenShot 📷
### [비로그인 상태에서 강의 수정 버튼 클릭 시 경고 토스트 출력]
![스크린샷 2024-12-04 032208](https://github.com/user-attachments/assets/a8a95e8c-dc65-4b94-b1f7-6d47dcc1593e)
### [강의 수정 버튼]
![스크린샷 2024-12-04 032229](https://github.com/user-attachments/assets/839830c2-3f1e-48b1-9828-6a9c9832ed7b)
### [커스텀 강의 수정 시 포맷]
![스크린샷 2024-12-04 032238](https://github.com/user-attachments/assets/5744ecac-bcf1-4c9a-a807-07a4a7c747ac)
### [정규 강의 수정 시 포맷]
![스크린샷 2024-12-04 032248](https://github.com/user-attachments/assets/a3abd847-0947-4134-afa9-6f27c3f1bb3f)
### [강의 수정 완료 될 시 완료 토스트 출력]
![스크린샷 2024-12-04 032255](https://github.com/user-attachments/assets/53662767-88a5-44c6-ac6e-32841093edd1)
### [강의 수정 사항 반영]
![스크린샷 2024-12-04 032320](https://github.com/user-attachments/assets/dc62cbb5-62a7-46bd-9a78-6c5b71c3ad88)

## ✔️ Please check if the PR fulfills these requirements

- [x] It's submitted to the correct branch, not the `develop` branch unconditionally?
- [x] If on a hotfix branch, ensure it targets `main`?
- [x] There are no warning message when you run `yarn lint`

2024-12-04 00:44 UTC, Gwak-Seungju requested changes
생각보다 구현하기 어려운 기능이었던 것 같은데 잘 해준 것 같아요! 수고하셨습니다!!
다만, 아직 100% 완료했다고 보긴 힘들 것 같아요.
1. 정규 강의 수정 시 시간 수정이 불가능한데 시간&장소 컴포넌트 삭제가 가능한 점
2. 분반이 있는 강의 수정 시 시간표 내 회색 표시된(미리보기) 강의에는 분반이 없어서 자연스럽지 않음 점
3. 강의 수정 완료 후 다음 행동에 대한 명세가 없어서 그대로 냅두셨지만, 수정하기 전에 정규 과목 탭에서 직접 추가 탭으로 이동한 것이기 때문에 수정 완료하면 다시 정규 과목 탭으로 이동하는 것은 어떨까요? 이 부분은 PM님, 디자이너 분과 상의하고 피그마에 명세하도록 하는 게 좋을 것 같아요!
4. 강의 수정이 시간표 강의 `hover`시 수정 버튼을 통해서도 가능하지만 **'시간표에 추가한 과목' 리스트**에서 목록 내 강의 hover시 수정 버튼을 통해서도 가능합니다! 피그마에 있는 디자인을 참고하시면 좋을 것 같아요!

2024-12-04 00:44 UTC, Gwak-Seungju commented on src/pages/TimetablePage/components/CustomLecture/index.tsx
> +
`isDuplicatedTime`은 제가 선언한 변수인데요, 제가 의도한 바는 `timeSpaceComponent` **내에서** 중복된 시간이 있을 시 `false`를 나타내는 것이었습니다. 근데 예진님이 새롭게 선언한 부분은 약간 다른 의도인 것 같아요. 
제가 의도한 부분을 알아차리기 어렵게 만든 부분이 있었던 것 같네요..!

2024-12-04 00:44 UTC, Gwak-Seungju commented on src/pages/TimetablePage/components/CustomLecture/index.tsx
> +
아래에서 선언한 `alreadySelectedLecture`와 로직이 비슷해 보이는데 `isDuplicatedTime`의 기존 로직을 없애면서 따로 만든 이유가 있을까요?

2024-12-04 00:44 UTC, Gwak-Seungju commented on src/pages/TimetablePage/components/CustomLecture/index.tsx
> +  const lecture = selectedLecture as MyLectureInfo | null;
여기에서 선언한 `lecture`를 아래에서 많이 사용하는 듯한데, 아래에서 `lecture`를 보면 무엇은 나타내는지 잘 모르겠어요 ㅠㅠ. 따라서 `selectedLecutre`처럼 변수만 보고 어떤 것을 나타내는지 알 수 있게 변수명을 지어주세요 !!

2024-12-04 00:44 UTC, Gwak-Seungju commented on src/pages/TimetablePage/components/CustomLecture/index.tsx
> +        lecture_id: lecture?.lecture_id,
조건문에 `lecture`의 유무를 판단하기 때문에 `lecture `뒤 `?`는 빼도 상관없을 것 같아요 !

2024-12-04 00:44 UTC, Gwak-Seungju commented on src/pages/TimetablePage/components/CustomLecture/index.tsx
> +
`useEffect `안에 있는 로직은 어떤 로직을 나타내는 것일까요? 저는 정규 강의의 경우에 분할된 강의 시간을 `class_infos`에 맞게 분할하는 것으로 이해했습니다! 근데 이것을 `useEffect`로 표현한 이유가 있을까요?

2024-12-04 00:44 UTC, Gwak-Seungju commented on src/pages/TimetablePage/components/CustomLecture/index.tsx
> +            [styles['inputbox__name--disabled']]: lecture?.lecture_id !== null && (!!lecture),
`lecture?.lecture_id !== null && (!!lecture)`
위 `boolean`이 중복돼서 많이 사용되는 것 같아요! 따라서 가독성도 챙길 겸 변수로 선언하면 좋을 것 같아요!

2024-12-04 01:01 UTC, Yejin0070 commented
> 생각보다 구현하기 어려운 기능이었던 것 같은데 잘 해준 것 같아요! 수고하셨습니다!! 다만, 아직 100% 완료했다고 보긴 힘들 것 같아요.
> 
> 1. 정규 강의 수정 시 시간 수정이 불가능한데 시간&장소 컴포넌트 삭제가 가능한 점
> 2. 분반이 있는 강의 수정 시 시간표 내 회색 표시된(미리보기) 강의에는 분반이 없어서 자연스럽지 않음 점
> 3. 강의 수정 완료 후 다음 행동에 대한 명세가 없어서 그대로 냅두셨지만, 수정하기 전에 정규 과목 탭에서 직접 추가 탭으로 이동한 것이기 때문에 수정 완료하면 다시 정규 과목 탭으로 이동하는 것은 어떨까요? 이 부분은 PM님, 디자이너 분과 상의하고 피그마에 명세하도록 하는 게 좋을 것 같아요!
> 4. 강의 수정이 시간표 강의 `hover`시 수정 버튼을 통해서도 가능하지만 **'시간표에 추가한 과목' 리스트**에서 목록 내 강의 hover시 수정 버튼을 통해서도 가능합니다! 피그마에 있는 디자인을 참고하시면 좋을 것 같아요!

2024-12-04 01:14 UTC, Yejin0070 commented on src/pages/TimetablePage/components/CustomLecture/index.tsx
> +  const lecture = selectedLecture as MyLectureInfo | null;
수정하였습니다!

6e79606e2fb3fd1a51cd8e12e9133431f059a902

2024-12-04 01:18 UTC, Yejin0070 commented on src/pages/TimetablePage/components/CustomLecture/index.tsx
> +        lecture_id: lecture?.lecture_id,
수정하였습니다!

b189b5b4912fccef6c13d9bde76f574f90222fc9

2024-12-04 01:33 UTC, Yejin0070 commented on src/pages/TimetablePage/components/CustomLecture/index.tsx
> +}
아하! 넵 수정하였습니다 :)

7ed24784afa5afa93cfc1667d964ec9852b6097f

2024-12-04 01:54 UTC, Yejin0070 commented on src/pages/TimetablePage/components/CustomLecture/index.tsx
> +
제가 이해하기로 기존 isDuplicatedTime 로직은 시간표를 추가하는 핸들러 함수에서 중복 여부를 확인하기 위한 로직으로 이해하였습니다. 제가 이를 새롭게 선언한 이유는 강의 수정 로직에서는 중복 검사가 기존 커스텀 강의 추가 시 중복 검사와는 조금 차이가 있어서 입니다! 강의 수정 시에는 선택된 강의를 제외하고 중복 검사를 해야 하기 때문에 위와 같이 작성하였습니다.

말씀하신 부분에 대해서는 더 고민해보고, 기존 로직과 현재 로직을 일관되게 통합할 방법이 있는지 검토해 보겠습니다!

2024-12-04 02:12 UTC, Yejin0070 commented
> 생각보다 구현하기 어려운 기능이었던 것 같은데 잘 해준 것 같아요! 수고하셨습니다!! 다만, 아직 100% 완료했다고 보긴 힘들 것 같아요.
> 
> 1. 정규 강의 수정 시 시간 수정이 불가능한데 시간&장소 컴포넌트 삭제가 가능한 점
> 2. 분반이 있는 강의 수정 시 시간표 내 회색 표시된(미리보기) 강의에는 분반이 없어서 자연스럽지 않음 점
> 3. 강의 수정 완료 후 다음 행동에 대한 명세가 없어서 그대로 냅두셨지만, 수정하기 전에 정규 과목 탭에서 직접 추가 탭으로 이동한 것이기 때문에 수정 완료하면 다시 정규 과목 탭으로 이동하는 것은 어떨까요? 이 부분은 PM님, 디자이너 분과 상의하고 피그마에 명세하도록 하는 게 좋을 것 같아요!
> 4. 강의 수정이 시간표 강의 `hover`시 수정 버튼을 통해서도 가능하지만 **'시간표에 추가한 과목' 리스트**에서 목록 내 강의 hover시 수정 버튼을 통해서도 가능합니다! 피그마에 있는 디자인을 참고하시면 좋을 것 같아요!

1. 이 부분은 따로 삭제 불가능하도록 수정하겠습니다!
2. 명세가 없어서 의견이 다를 수 있지만 우선 저의 의도를 말씀드리자면, 제가 생각하기에 정규 과목 수정 시 분반 수정이 어렵고 강의 정보를 수정함과 동시에 미리보기와 기존 강의 내용이 달라져 결국엔 부자연스럽게 보인다고 생각합니다. 이에 대해서 정규 과목 수정 시 분반을 함께 출력하여 조금 더 자연스럽게 출력할 것인지 아님 미리보기를 없앨지 등에 대한 다양한 방향이 있을 것 같았고, 명세가 나온 후에 이 부분을 수정하는 것이 나을 것 같아 이 부분은 대처하지 않았습니다. 그래도 분반 출력 부분은 한 번 더 고민해보겠습니다!
3. 이 부분 또한 PM님과 디자이너 분과 명세에 대해 논의해보겠습니다!
4. 헙.. 이 강의 수정 부분 디자인은 아직 피그마에서 완료된 디자인이 아니라고 나와서 미처 자세히 확인하지 못한 것 같습니다! 검토하겠습니다!

2024-12-12 10:47 UTC, D0Dam requested changes
수고하셨습니다!
hook이 얽히고 얽히 구조가 옛날부터 있었던 것 같긴 하지만, 우선 hook들의 비슷한 기능들이 얽히면서 같은 공용훅이 재선언되고, 인자로 넘겨지고 재선언하고가 과하게 심해진 것 같아요.. 팀 내에서도 같이 이야기해보고 훅들이 일관된 기능을 가지고 공용훅 인자의 재활 같은 부분을 가능하면 제거해보면 좋을 것 같습니다!
모든 내용을 코드에 반영할 필요는 없겠지만 그래도 한 번 고민해서 수정해보시고 다시 request 부탁드립니다!

2024-12-12 10:47 UTC, D0Dam commented on src/pages/TimetablePage/components/Timetable/index.tsx
> +                      </div>
1. `<button />` 안 사용한 이유가 있었을까요?
2. lectureIndex를 객체에 담아서 넘긴 이유가 있나요?
3. onClick안에 inline function으로 선언한 이유가 있나요?

제 생각에 button event가 반환하는 event객체를 잘 활용하면 값을 넘기지 않아도 이걸 처리할 수 있을 것 같네요!(안될수도 있음)

2024-12-12 10:47 UTC, D0Dam commented on src/pages/TimetablePage/components/Timetable/index.tsx
> +}
1. lectureIndex를 props로 보는게 맞을까요?
2. 사용한 위치를 보니 한번 사용하는 것 같은데 의미있는 분리일까요?
3. lectureIndex의 타입값이 추론되지는 않았나요?

2024-12-12 10:47 UTC, D0Dam commented on src/pages/TimetablePage/components/Timetable/index.tsx
> +  };
1. 이렇게 하는 것과는 어떤 차이가 있을까요?
```
  const handleEditLectureClick = ({
    lectureIndex,
  }: EditLectureProps) => {
    if (!token) {
      return toast.error('강의 수정은 로그인 후 이용할 수 있습니다.');
    }

    return navigate(`/timetable/modify/direct/${frameId}?lectureIndex=${lectureIndex}`);
  };
```

2. lectureIndex는 parameter에서 값을 가져오는데 frameId는 그렇지 않네요. 순수함수 개념을 생각해보고 순수함수가 적용되는게 맞을지 이대로 두는것이 좋을지 한번 생각해볼까요?

3. (선택) token이 없을 경우의 에러 처리가 toast 출력이 전부이면 ux가 좋지는 않을 것 같네요.. 내부적으로 이미 만들어진 token 없을때의 방어로직이 구현이 안되어 있을까요? 없다면 구현해보고 로직을 공유해서 앞으로 token이 없는 상황에서 다들 쓸 수 있도록 하면 따따봉일것 같아요~!

2024-12-12 10:47 UTC, D0Dam commented on src/pages/TimetablePage/components/Timetable/index.tsx
> +                        onClick={() => handleRemoveLectureClick(id!)}
id가 null이 아니라는 것을 보장해줄 수 있는건가요?

2024-12-13 05:35 UTC, Yejin0070 commented on src/api/timetable/entity.ts
> +export type EditLectureInfoResponse = TimetableLectureInfoResponse;
제가 기존 인터페이스를 다시 재정의 하고자 한 의도는, 제가 이 인터페이스를 사용하여 구현하고자 하는 코드의 맥락이 기존의 사용과는 달라서 네이밍을 다르게 해줘야 할 것이라고 생각하였기 때문입니다. 타입을 재정의 하였기 때문에, 위에서 언급하신 클래스를 다시 정의하였던 것이었습니다. 하지만 이 부분은 잘못되었다는 것을 인지하였고 해당 부분들은 수정하겠습니다.

다만 질문이 한 가지 있다면 위에서 말씀하신 구조 표현을 위해 썼기 때문에 동사형보다는 명사형 사용이 좋을 것 같다 하셨는데, interface 네이밍 또한 명사형으로 수정이 필요해 보입니다. 그렇다면 기존 코드들에서도 수정이 필요해 보이는 곳이 있는데, 리팩토링하면서 같이 수정을 하는게 좋을까요?

2024-12-13 05:47 UTC, Yejin0070 commented on src/api/timetable/APIDetail.ts
> +
수정하였습니다!

e919f1d47ba016e28d3defdf00cb03732e228e29

2024-12-13 05:48 UTC, Yejin0070 commented on src/api/timetable/entity.ts
> +export type EditLectureInfoResponse = TimetableLectureInfoResponse;
해당 부분 코드는 삭제하였습니다!

e919f1d47ba016e28d3defdf00cb03732e228e29

2024-12-13 06:10 UTC, Yejin0070 commented on src/pages/TimetablePage/components/CustomLecture/index.tsx
> +
이 안의 로직은 (!Lecture -> !selectedEditLecture) 검사를 통해서 강의 수정 모드인지 검사를 한 후, 커스텀 강의 추가가 아닌 수정이 맞다면 수정하고자 하는 강의(selectedEditLecture)의 강의 정보를 불러와 설정하는 로직입니다.
useEffect는 선택된 강의(selectedEditLecture)의 변경될 때 강의 정보를 UI에 반영해야 하므로 useEffect를 사용했습니다.

2024-12-13 07:20 UTC, Yejin0070 commented on src/pages/TimetablePage/ModifyTimetablePage/index.tsx
> +  const frameId = Number(id);
현재 id는 string 또는 undefined 인 상태입니다.

만약 id가 null일 경우, Number(id)는 0을 반환하고 undefined이면 NaN을 반환합니다. 

코드 수정하겠습니다 :)

2024-12-13 07:49 UTC, Yejin0070 commented on src/pages/TimetablePage/components/Timetable/index.tsx
> +                      </div>
기존 강의 삭제 버튼 구조와 거의 동일하게 추가하여 본래의 의도가 정확하지 않을 수 있지만, 질문해주신 것에 대한 저의 생각은 다음과 같습니다.

1. 기존 코드 구조와의 일관성을 위해 div 태그를 사용하였지만, 이에 대해서 고민해본 결과 버튼은 button태그를 사용하는 것이 더 나은 방향일 것 이라 판단하였습니다. 이 부분에 대해서는 일관성을 위해 다른 코드도 검토해보는 것이 좋을 것 같아 추후 리팩토링 단계에서 수정하겠습니다.
2. 기존에 lectureIndex 뿐만 아니라 추가적인 데이터를 함께 넣기 위해 객체를 사용했었습니다. 이후 로직이 변경되면서 lectureIndex 하나만 넘기는 형태로 수정하였고 이에 대한 수정이 완전하지 못했던 것 같습니다. 수정하겠습니다!
3. lectureIndex가 명시적으로 전달되어야 하므로 inline function을 사용하는 것이 더 직관적일 것이라고 생각하였습니다.

2024-12-13 08:58 UTC, Yejin0070 commented on src/pages/TimetablePage/components/Timetable/index.tsx
> +  };
1. 본래의 코드는 return과 toast.error를 별도 작성하였고 !token이 참일경우 반환값이 항상 undefined입니다. 이 경우 이 핸들러 함수를 호출하는 부분에서 결과를 활용할 수 없고, 만약 return toast.error로 작성한다면 해당 결과를 처리할 수 있을 것 같습니다. 
2. 현재 코드는 frameId와 token을 외부에서 받아오고 있고, 이 때문에 손수 함수라고 볼 수 없습니다. side effect(상태 변경, 화면 출력 등)를 고려해보았을 때, 순수함수로 작성하는 방향이 좋을 것 같습니다.
3. 넵 저도 이 부분에 대해서 고민을 해보았습니다. 현재 비로그인시 출력에 대한 에러 처리는 다른 페이지의 toast 출력 로직을 참고하였으며, 강의 수정 기능 자체의 명세를 논의해본 후 추가 구현해보겠습니다!

2024-12-13 09:05 UTC, Yejin0070 commented on src/pages/TimetablePage/components/Timetable/index.tsx
> +      ?? customTempLecture?.class_infos?.map((schedule) => schedule.class_time).flat();
flatmap에서도 찾아보겠습니다!

현재 코드를 flatmap 사용으로 바꾸면 다음과 같이 쓸 수 있을 것 같습니다.

```suggestion
      ?? customTempLecture?.class_infos?.flatMap((schedule) => schedule.class_time);
```

2024-12-15 02:33 UTC, Yejin0070 commented on src/pages/TimetablePage/components/Timetable/index.tsx
> +                        onClick={() => handleRemoveLectureClick(id!)}
id!로 단언한 이유는 인터페이스 정의에서 id가 반드시 number 타입임이 명시되어 있으며, 코드 흐름상 id가 undefined가 될 가능성이 없다고 판단했기 때문입니다.  

현재 handleRemoveLectureClick 함수는 id: number 타입을 매개변수로 받으며, 이 함수가 호출되는 모든 경로에서 id는 LectureInfo 또는 MyLectureInfo 에서 가져오는 값이기 때문에 number임이 보장됩니다.

2024-12-15 02:44 UTC, Yejin0070 commented on src/pages/TimetablePage/hooks/useEditTimetableLecture.ts
> +export default function useEditTimetableLecture(authorization: string) {
말씀하신 부분에 동의합니다. 
다만, 현재 이 코드는 프로젝트 내 다른 훅들과의 구조적 일관성과 변수명을 맞추기 위해 작성되었습니다. 변수명 authorization 역시 기존 코드 스타일을 따랐지만, 말씀하신 대로 변경하면 의도를 더 명확히 전달할 수 있을 것 같습니다.

추후 이 부분들에 대해서는 리팩토링 과정에서 다른 훅들과 함께 반영하겠습니다 :)

2024-12-15 02:48 UTC, Yejin0070 commented on src/pages/TimetablePage/hooks/useEditTimetableLecture.ts
> +import { TIMETABLE_INFO_LIST } from './useTimetableInfoList';
이 부분도 추후 리팩토링 시 TIMETABLE_INFO_LIST와 같은 상수나 로직을 별도의 유틸리티 파일로 분리하여 훅 간의 직접적인 의존성을 제거하거나, hook이 독립적으로 동작할 수 있도록 개선해보겠습니다.

2024-12-15 02:57 UTC, Yejin0070 commented on src/pages/TimetablePage/hooks/useTimetableInfoList.ts
> +function useTimetableInfoList({ authorization, timetableFrameId }: UseTimetableInfoListProps) {
1. 매개변수가 많아질 경우 코드의 확장성과 가독성을 높일 수 있다고 판단하여 이렇게 작성..하였습니다..
2. 넵. 수정하겠습니다!

2024-12-15 03:02 UTC, Yejin0070 commented on src/pages/TimetablePage/hooks/useTimetableInfoList.ts
> +}
undefined를 union으로 엮어 명시해준 이유는 해당 값이 존재하지만 undefined일 수 있다는 의도를 나타내기 위함입니다. 옵셔널 체이닝을 사용하는 것은 property가 존재하지 않을 수도 있음을 의미하고, 이를 사용하지 않은 이유는 반드시 해당 property가 존재함을 나타내기 위함입니다.

2024-12-15 03:03 UTC, Yejin0070 commented on src/pages/TimetablePage/hooks/useTimetableInfoList.ts
> +function queryFunction({ authorization, timetableFrameId }: QueryFunction) {
넵 수정하겠습니다!

2024-12-15 03:12 UTC, Yejin0070 commented on src/pages/TimetablePage/hooks/useTimetableInfoList.ts
> +}
1. 말씀하신대로 함수화 한 이유는 API 호출 로직을 분리하여 가독성을 높이기 위해서였습니다.
2. 넵 queryFunction을 제거하고 queryFn 내부에서 조건부 로직을 직접 처리하도록 수정하겠습니다!

2024-12-15 03:35 UTC, Yejin0070 commented on src/pages/TimetablePage/hooks/useMyLectures.ts
> +  const myLectures = token ? myLecturesFromServer : myLecturesFromLocalStorageValue;
넵 수정하겠습니다!

2024-12-15 03:37 UTC, Yejin0070 commented on src/pages/TimetablePage/hooks/useTimetableMutation.ts
> +import { TIMETABLE_INFO_LIST } from './useTimetableInfoList';
이 부분도 위 답변한 것과 같이 추후 리팩토링 시 TIMETABLE_INFO_LIST와 같은 상수나 로직을 별도의 유틸리티 파일로 분리해보겠습니다!

2024-12-15 11:22 UTC, Yejin0070 commented on src/pages/TimetablePage/hooks/useTimetableMutation.ts
> +  };
넵 수정하였습니다!

fed10576bd30d538aad18f3c795ac1c105e9d75b

2024-12-15 18:21 UTC, Gwak-Seungju requested changes
> > 생각보다 구현하기 어려운 기능이었던 것 같은데 잘 해준 것 같아요! 수고하셨습니다!! 다만, 아직 100% 완료했다고 보긴 힘들 것 같아요.
> > 
> > 1. 정규 강의 수정 시 시간 수정이 불가능한데 시간&장소 컴포넌트 삭제가 가능한 점
> > 2. 분반이 있는 강의 수정 시 시간표 내 회색 표시된(미리보기) 강의에는 분반이 없어서 자연스럽지 않음 점
> > 3. 강의 수정 완료 후 다음 행동에 대한 명세가 없어서 그대로 냅두셨지만, 수정하기 전에 정규 과목 탭에서 직접 추가 탭으로 이동한 것이기 때문에 수정 완료하면 다시 정규 과목 탭으로 이동하는 것은 어떨까요? 이 부분은 PM님, 디자이너 분과 상의하고 피그마에 명세하도록 하는 게 좋을 것 같아요!
> > 4. 강의 수정이 시간표 강의 hover시 수정 버튼을 통해서도 가능하지만 '시간표에 추가한 과목' 리스트에서 목록 내 강의 hover시 수정 버튼을 통해서도 가능합니다! 피그마에 있는 디자인을 참고하시면 좋을 것 같아요!
> 
> 1. 이 부분은 따로 삭제 불가능하도록 수정하겠습니다!
> 2. 명세가 없어서 의견이 다를 수 있지만 우선 저의 의도를 말씀드리자면, 제가 생각하기에 정규 과목 수정 시 분반 수정이 어렵고 강의 정보를 수정함과 동시에 미리보기와 기존 강의 내용이 달라져 결국엔 부자연스럽게 보인다고 생각합니다. 이에 대해서 정규 과목 수정 시 분반을 함께 출력하여 조금 더 자연스럽게 출력할 것인지 아님 미리보기를 없앨지 등에 대한 다양한 방향이 있을 것 같았고, 명세가 나온 후에 이 부분을 수정하는 것이 나을 것 같아 이 부분은 대처하지 않았습니다. 그래도 분반 출력 부분은 한 번 더 고민해보겠습니다!
> 3. 이 부분 또한 PM님과 디자이너 분과 명세에 대해 논의해보겠습니다!
> 4. 이 부분에 대해서 PR 선공지를 못한 것 같습니다..! PR Post에 적어두고 디자인팀에게 확인해본 후 추가하겠습니다!

위에서 말씀하신 부분은 반영을 못하신 것 같아요! 이 부분과 `timeSpaceComponent`끼리 시간이 겹치는 경우의 처리 로직만 반영하면 될 것 같습니다!

2024-12-16 03:44 UTC, Yejin0070 commented
> > > 생각보다 구현하기 어려운 기능이었던 것 같은데 잘 해준 것 같아요! 수고하셨습니다!! 다만, 아직 100% 완료했다고 보긴 힘들 것 같아요.
> > > 
> > > 1. 정규 강의 수정 시 시간 수정이 불가능한데 시간&장소 컴포넌트 삭제가 가능한 점
> > > 2. 분반이 있는 강의 수정 시 시간표 내 회색 표시된(미리보기) 강의에는 분반이 없어서 자연스럽지 않음 점
> > > 3. 강의 수정 완료 후 다음 행동에 대한 명세가 없어서 그대로 냅두셨지만, 수정하기 전에 정규 과목 탭에서 직접 추가 탭으로 이동한 것이기 때문에 수정 완료하면 다시 정규 과목 탭으로 이동하는 것은 어떨까요? 이 부분은 PM님, 디자이너 분과 상의하고 피그마에 명세하도록 하는 게 좋을 것 같아요!
> > > 4. 강의 수정이 시간표 강의 hover시 수정 버튼을 통해서도 가능하지만 '시간표에 추가한 과목' 리스트에서 목록 내 강의 hover시 수정 버튼을 통해서도 가능합니다! 피그마에 있는 디자인을 참고하시면 좋을 것 같아요!
> > 
> > 
> > 
> > 1. 이 부분은 따로 삭제 불가능하도록 수정하겠습니다!
> > 2. 명세가 없어서 의견이 다를 수 있지만 우선 저의 의도를 말씀드리자면, 제가 생각하기에 정규 과목 수정 시 분반 수정이 어렵고 강의 정보를 수정함과 동시에 미리보기와 기존 강의 내용이 달라져 결국엔 부자연스럽게 보인다고 생각합니다. 이에 대해서 정규 과목 수정 시 분반을 함께 출력하여 조금 더 자연스럽게 출력할 것인지 아님 미리보기를 없앨지 등에 대한 다양한 방향이 있을 것 같았고, 명세가 나온 후에 이 부분을 수정하는 것이 나을 것 같아 이 부분은 대처하지 않았습니다. 그래도 분반 출력 부분은 한 번 더 고민해보겠습니다!
> > 3. 이 부분 또한 PM님과 디자이너 분과 명세에 대해 논의해보겠습니다!
> > 4. 이 부분에 대해서 PR 선공지를 못한 것 같습니다..! PR Post에 적어두고 디자인팀에게 확인해본 후 추가하겠습니다!
> 
> 위에서 말씀하신 부분은 반영을 못하신 것 같아요! 이 부분과 `timeSpaceComponent`끼리 시간이 겹치는 경우의 처리 로직만 반영하면 될 것 같습니다!

1. 정규 강의 수정 시 시간&장소 컴포넌트 삭제 비활성화
28c9c4b2b0ac73f89a2661d0cff2158e8cea26d5

3. timeSpaceComponent 중복 처리 로직 반영
8a1ead1e6ed4760842121dc8bd1a0e666b1556a8

2024-12-16 09:24 UTC, D0Dam approved these changes
대면 리뷰로 대신했습니다! 수고하셨습니다!

2024-12-17 05:44 UTC, Gwak-Seungju approved these changes
수고하셨습니다!

2024-12-17 07:11 UTC, merged