Feature/#5
BCSDLab/KOIN_WEB_RECODE pull request #7
Opened 2022-08-21 11:30 UTC by daepan

## [#5] 로그인 환경 및 인증 부분 추가

로그인페이지 화면 작성.
로그인 되었을 시, 로그인 버튼 누르면 로그인 창을 이동하지 않고 메인으로 돌아옴
자동로그인 클릭 시 이벤트 작성
axios wrapper 세팅
로그인 로직 작성
- token은 쿠키로 저장
- 자동로그인 미 체크시에는 세션쿠키로 저장
- 자동로그인 체크 시에는 3일의 유효기간을 갖는 쿠키로 저장(token 자체의 유효기간이 3일)

## Please check if the PR fulfills these requirements

- [ ] 로그인 로직에서 피드백 혹은 이런식으로 변경하면 좋을 것 같다라는 의견이 있다면 주시면 감사하겠습니다.
- [ ] 로그인 UI가 잘 작동하는지 확인해주세요.
- [ ] lint에서 에러가 나는 경우가 있다면 피드백주세요

### Screenshot

기본 페이지
![image](https://user-images.githubusercontent.com/50792467/185788773-d2ce7800-0cfc-4553-91cf-369409a77bfe.png)

자동로그인 체크 시
![image](https://user-images.githubusercontent.com/50792467/185788802-400e6600-e384-4f9d-b0ab-e3d4efdc52f4.png)

2022-08-23 08:15 UTC, SimYunSup requested changes
기반 설정은 처음이라 어려웠을텐데 퀄리티 있게 하느라 고생하셨습니다.

2022-08-23 08:15 UTC, SimYunSup commented on src/pages/Auth/LoginPage/index.tsx
> +          <span className={styles.autologin__label__oncheck} />
`element__element__target`은 BEM표기법에 맞지 않습니다. 분리해주세요.

2022-08-23 08:15 UTC, SimYunSup commented on src/pages/Auth/LoginPage/index.tsx
> +import useLogin from '../../../utils/hooks/useLogin';
절대경로를 사용하실거면 통일해서 사용해주세요.

2022-08-23 08:15 UTC, SimYunSup commented on src/pages/Auth/LoginPage/index.tsx
> +          <span className={styles.autologin__label__oncheck} />
해당 태그는 스크린 리더에서 쓸모 없으므로 `aria-hidden`을 참으로 만들어주세요.

2022-08-23 08:15 UTC, SimYunSup commented on src/pages/Auth/index.tsx
> +          <img className={styles.template__logo__img} src="https://static.koreatech.in/assets/img/logo_primary.png" alt="logo" />
`element__element__target`은 BEM표기법에 맞지 않습니다. 분리해주세요.

2022-08-23 15:11 UTC, ChoiWonBeen requested changes
확인해보고 수정해주세요

Layout 분리에 대한 고민은 함께 해볼 필요가 있어보이네요 🧐 🤔

2022-08-23 15:11 UTC, ChoiWonBeen commented on src/pages/Auth/index.tsx
> +function AuthPage() {
AuthPage가 LoginPage와 다른 뎁스에 들어있어 폴더로 구분짓는게 좋아보입니다.
Auth/AuthPage
Auth/LoginPage

그런데 AuthPage의 역할이 Layout에 가깝다고 보는데 같은 Page 디렉토리에서 관리되는게 맞나? 라는 생각도 드네요. 
과연 LoginPage와 AuthPage의 역할이 같나? 라고 생각하면 조금 거리가 있어보이죠.

Layout으로의 분리가 과한 것 같긴 하지만서도 둘은 달라보여서 고민할 필요는 있어보여요.

2022-08-23 15:11 UTC, ChoiWonBeen commented on src/utils/ts/cookie.ts
> +  const parts = value.split(`; ${name}=`);
name에 해당하는 쿠키가 아니고 다른 쿠키가 들어있으면 name을 분리하지 못하고 남은 모든 쿠키를 가져오는 문제가 발생합니다. 
로직을 잘 보고 수정해주세요.

2022-08-24 08:01 UTC, daepan commented on src/pages/Auth/index.tsx
> +function AuthPage() {
AuthPage의 경우 뎁스를 준 이유는 AuthPage, 즉 로그인 화면에 대한 페이지가 2개가 있는데 둘 다 모두 AuthPage에서의 로고 이미지가 공통으로 들어가게 됩니다, 그리고 Outlet이란 기능을 통해 밑에 auth/로그인 , auth/회원가입 으로 표현되기에 AuthPage/LoginPage 라고 생각하여 뎁스를 주었습니다. 
만약 말씀하신 것처럼 Auth/AuthPage, Auth/LoginPage로 둔다면 Auth에 두가지 페이지가 따로 있는 것처럼 보이게 될 것 같은데, 저는 지금 형태가 AuthPage와 LoginPage, SignUpPage(예시) 상하위를 나눠줄 수 있는 지금 형태가 더 나을 거라고 생각했습니다.

2022-08-24 08:02 UTC, daepan commented on src/utils/hooks/useLogin.ts
> +      queryClient.invalidateQueries('postLogin');
Recoil 세팅에 대해 학습해두겠습니다. 혹시 좋은 자료 있으면 공유부탁드립니다

2022-08-24 08:28 UTC, daepan commented on src/pages/Auth/LoginPage/index.tsx
> +  }, [isAutoLoginFlag]);
useCallback을 통해 다른 컴포넌트의 변화가 이루어지는 경우에 대해서 방지하려고 사용 했습니다.
저번에 ref 사용으로 유지할 이유가 없어져 useCallback을 굳이 사용할 필요는 없는 것 같습니다.
(추가로 console을 주고 테스트를 해보니 큰 변화나 성능향상에 도움이 되는지 확인하지 못하였습니다.)
그리고 밑에 내용이 정확히 이해되지 않았는데 함수+setState가 useCallback+setState보다 시너지가 더 좋다는 뜻인가요? 
시너지가 좋다면 어떤 부분이 향상되는 건가요?

2022-08-24 12:35 UTC, daepan commented on src/pages/Auth/LoginPage/LoginPage.module.scss
> +.styledinput {
form-input 과 같은 하이픈을 사용하게 되면 [해당 lint오류](https://typescript-eslint.io/rules/space-infix-ops) 가 작동합니다. 
해당 부분에 대해서 lint 제거에 대해서는 어떻게 생각하시나요?

2022-08-24 12:36 UTC, daepan commented on src/pages/Auth/LoginPage/LoginPage.module.scss
> +.styledinput {
그리고 input에 관련된 것도 예전에 이야기 했었는데 고작 페이지 2개에서 밖에 안쓰는건데 굳이 따로 파일을 더 만드는게 과연 충분한 소요인가에 대해 이야기한 적 있었습니다.
CSS 내용을 서로 공유할 수 있게 하는 방법을 한번 고민해보겠습니다

2022-08-24 12:42 UTC, daepan commented on src/pages/Auth/LoginPage/index.tsx
> +    emailLocalPartRegex.test(userId.value);
해당 부분  alert로 처리해두고 차후 현재 코인에 있는 오류메세지 이벤트 작업을 생성에 대한 issue 및 주석 작성하겠습니다

2022-08-24 12:42 UTC, daepan commented on src/api/auth/login.ts
> +}
저번에 테스트한다고 추가했던 부분이 올라갔습니다. 제거해두겠습니다

2022-08-24 14:41 UTC, ChoiWonBeen commented on src/pages/Auth/LoginPage/LoginPage.module.scss
> +.styledinput {
엄밀히 말하면 3개페이지기도 하고, (로그인/회원가입/비밀번호찾기) 두개뿐이라 하더라도
해당 인풋이 가질 라벨, **RegExp valid/invalid action**, 하단 설명 텍스트까지 묶어서 컴포넌트화 시킬 수 있을거라 더 좋을거같아요. 추후에 확장되어 딜리버리가 추가된다면, 그때도 사용될 가능성도 있구요.

2022-08-24 14:48 UTC, ChoiWonBeen commented on src/pages/Auth/index.tsx
> +function AuthPage() {
layout/ 으로의 분리가 조심스러운건, Auth말고도 레이아웃이 사용되는 페이지들이 있을까? 라는 점 때문이예요.
식당이나 복덕방도 같은 뎁스에서 여러 페이지가 있으니 layout구조의 사용 가능성이 조금은 있어서 고민해봐야 할 것 같아요

2022-08-24 14:49 UTC, ChoiWonBeen commented on src/pages/Auth/LoginPage/LoginPage.module.scss
> +.styledinput {
린트 제거는 찬성합니다~ bem구조로는 어쩔 수 없을거같아요.

2022-08-24 14:52 UTC, ChoiWonBeen commented on src/pages/Auth/LoginPage/index.tsx
> +          <span className={styles.autologin__label__oncheck} />
```suggestion
          <span role="checkbox" aria-checked={isAutoLoginFlag} className={styles.autologin__label__oncheck} />
```
접근성 향상을 위해 실제 checkbox 역할을 하는 span 태그에 속성을 추가해주어야 할 것 같네요.

2022-08-25 01:08 UTC, daepan commented on src/api/apiClient.ts
> +import axios, { AxiosError, AxiosResponse } from 'axios';
interfaces에 있는 APIError, APIResponse, APIRequest의 경우 api 폴더들에서도 공유됩니다.
어떤식으로 분리하면 좋을까요?

2022-08-25 01:15 UTC, daepan commented on src/pages/Auth/LoginPage/index.tsx
> +          <span className={styles.autologin__label__oncheck} />
해당 부분에서는 [해당 lint 오류](jsx-a11y/control-has-associated-label)가 발생합니다. 이 부분은 제가 정확히 어떤 것이 옳은지 잘 모르겠습니다. 접근성향상이라고 한다는 것이 저 코드 추가로 인해 정확히 어떤 부분이 향상되는 건가요 기능상에서 지금 현재 더 개선되는 점이 있는지 궁금합니다

2022-08-25 01:31 UTC, daepan commented on src/pages/Auth/LoginPage/LoginPage.module.scss
> +.styledinput {
lint 제거 이후 현재 타입스크립트에러로 인해 작성되면
아마 ` className={styles['form-input']}` 식으로 작성되는데 코드 개연성이 살짝 안맞아보이는데 괜찮을까요??

2022-08-25 02:29 UTC, daepan commented on src/App.tsx
> +  const token = getCookie('AUTH_TOKEN_KEY');
해당 부분의 경우 로그인 시 페이지를 리로드 하는 방식으로도 수정이 가능하지만, token 저장에 대해서 stateless에서 쿠키에 임시 저장을 해두고 사용의 경우에는 Recoil을 통해 유지하는 것으로 작성해보겠습니다

2022-08-25 06:02 UTC, SimYunSup commented on src/api/apiClient.ts
> +import axios, { AxiosError, AxiosResponse } from 'axios';
APICilent는 utils에, interface 파일은 interface폴더에 분리해주세요.

2022-08-25 06:04 UTC, SimYunSup commented on src/pages/Auth/LoginPage/index.tsx
> +  }, [isAutoLoginFlag]);
```suggestion
  const onToggleAutoLoginFlag = React.useCallback(() => {
    setIsAutoLoginFlag(flag => !flag);
  }, []);
```
위와 같이 사용하는 것이 시너지가 난다는 뜻이고, 시너지가 난다면 함수를 한번만 선언한다는 장점이 있겠지요.

2022-08-25 06:07 UTC, SimYunSup commented on src/pages/Auth/LoginPage/index.tsx
> +    emailLocalPartRegex.test(userId.value);
alert처리해둔다는게 어떻게 바꾸는 것인가요? 코인 로그인에는 코인 return값에 대한 오류 매세지 토스트 밖에 없습니다. 그 점 주의해서 이슈 작성해주세요.

2022-08-25 06:11 UTC, daepan commented on src/App.tsx
> +      <Route path="login/*" element={token ? <Navigate replace to="/" /> : <AuthPage />}>
login => auth로  변경하였습니다. 
auth로 한 이유는 AuthPage가 최상단 이기에 해당 이름으로 변경하였습니다.[2e4ccb4](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/7/commits/2e4ccb4873cba279565f136468d59f8071e55966)
추가적으로 메인에서 로그인 클릭시에 관한 route도 변경하였습니다
[c0746da](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/7/commits/c0746da99d0c3da9bc2ce3f1737ad6a7fe00d5df)

2022-08-25 06:13 UTC, daepan commented on src/api/apiClient.ts
> +  }
필요없는 제거 하였고 추가적으로 enum으로 되어있던  HTTPMethod의 경우 Union으로 변경하였습니다.
[1d00475](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/7/commits/1d00475beaf894f0aba8a58fe18f015b00be0e4b)

2022-08-25 06:13 UTC, daepan commented on src/api/auth/login.ts
> +}
[ad8eae1](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/7/commits/ad8eae1095609954b098cb8846bbb697f0164def)

2022-08-25 06:14 UTC, daepan commented on src/pages/Auth/LoginPage/index.tsx
> +import useLogin from '../../../utils/hooks/useLogin';
앞으로도 계속 절대경로를 이용하는게 좋을까요? 절대경로를 사용해야만 하는 경우를 저희끼리 정해두면 좋을 것 같습니다.
[9fba85c](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/7/commits/9fba85c110a778a645db24c36d300401e019b891)

2022-08-25 06:15 UTC, SimYunSup commented on src/pages/Auth/LoginPage/LoginPage.module.scss
> +.styledinput {
BEM 표기법과 CSS Module을 혼용한 이상 해당 방식으로 코드를 적는것은 어쩔 수 없습니다.
그리고 어떻게 저 lint 오류가 발생하는지 모르겠네요. 린트 제거가 불필요해보이는데 저 린트 에러가 어느 코드 부분에서 뜨는지 댓글로 적어주실 수 있나요?
그리고 코드 개연성이 안 맞는다는 뜻이 무슨 뜻인지 모르겠네요. 자세히 설명해주시겠어요?

2022-08-25 06:15 UTC, daepan commented on src/pages/Auth/LoginPage/index.tsx
> +          <span className={styles.autologin__label__oncheck} />
밑에 스타일도 겸해서 해당 요소 추가 완료하였습니다
[a3fbc74](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/7/commits/a3fbc74d64a36e5617dbeb78eacaf73bc58f3ee4)

2022-08-25 06:16 UTC, daepan commented on src/pages/Auth/LoginPage/index.tsx
> +          <span className={styles.autologin__label__oncheck} />
일단 className 스타일의 경우에는 수정되었습니다. 한번 확인 부탁드립니다.
[a3fbc74](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/7/commits/a3fbc74d64a36e5617dbeb78eacaf73bc58f3ee4)
[1725017](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/7/commits/17250177443da5f7120a05a19b9f37ddbca01d18)
[8abd4a1](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/7/commits/8abd4a16436763e49e3e04c9aa2ccf51b10cd8cd)

2022-08-25 06:25 UTC, SimYunSup commented on src/pages/Auth/LoginPage/index.tsx
> +          <span className={styles.autologin__label__oncheck} />
[해당 input checkbox에서 내장된 의미를 담당하고 있으므로 따로 aria-checked를 주지 않아도 됩니다.](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-checked) 그래서 쓸모없는 span태그를 aria-hidden으로 인식하지 않는 방향으로 제안하였습니다.
해당 제안은 필요없는 제안으로 보입니다.
해당 태그는 input태그를 없애고 따로 span태그만 활용할 경우 필요한 태그입니다.

2022-08-25 06:27 UTC, daepan commented on src/pages/Auth/LoginPage/LoginPage.module.scss
> +.styledinput {
lint 오류가 아닌 타입오류로 나옵니다.
`<label className={styles.auto-login__label} htmlFor="autoLoginCheckBox">` 이런식의 코드를 작성한다면
```
산술 연산의 왼쪽은 'any', 'number', 'bigint' 또는 열거형 형식이어야 합니다
Operator '-' must be spaced.eslint[@typescript-eslint/space-infix-ops](https://typescript-eslint.io/rules/space-infix-ops)
'number' 형식은 'string' 형식에 할당할 수 없습니다.ts(2322)
index.d.ts(1853, 9): 필요한 형식은 여기에서 'DetailedHTMLProps<LabelHTMLAttributes<HTMLLabelElement>, HTMLLabelElement>' 형식에 선언된 'className' 속성에서 가져옵니다.
```
3개의 오류가 발생합니다.

=====
코드 개연성이라고 한것은 제가 윤섭님 코드에서 ['~~'] 이런식의 스타일을 작성할때는 className 함수를 사용하는 경우에만 사용하는 것만 같기도 하고 또한 상위나 하위 느낌이 아닌 단순 클래스 이름을 평자로 적을 수 있음에도 하이픈을 쓰기 위해 해당 처리를 하는 것이 뭔가 통일성 없어보이지 않나라는 코드 미관이 저해되지 않을까 생각했습니다.

2022-08-25 06:30 UTC, daepan commented on src/pages/Auth/LoginPage/index.tsx
> +    emailLocalPartRegex.test(userId.value);
alert 처리 라고 말한 것은 현재 로그인 실패에 대한 이벤트를 현재 작성하기 어려우니 alert()를 통해 로그인 실패를 표시해두겠다는 내용입니다.
그리고 나중에는 오류메세지 토스트를 작성하거나 혹은 그와 유사한 에러이벤트를 구사할 수 있도록 주석과 issue를 생성해두겠습니다

2022-08-25 06:36 UTC, ChoiWonBeen commented on src/pages/Auth/LoginPage/index.tsx
> +          <span className={styles.autologin__label__oncheck} />
checkbox ui인 span과 input이 공존해서 복잡해져서 헷갈렸네요.
input의 display를 유지하며 이를 개선한 PR(#8) 올렸으니 확인해주세요~

2022-08-25 06:40 UTC, daepan commented on src/pages/Auth/LoginPage/index.tsx
> +          <span className={styles.autologin__label__oncheck} />
nice assist

2022-08-25 11:19 UTC, SimYunSup requested changes
바뀐 부분에 대해서 추가로 리뷰해드렸습니다.

2022-08-25 11:19 UTC, SimYunSup commented on src/api/apiClient.ts
> +export type UnionHttpMethod<T> = T[keyof T];
```suggestion
export const HTTP_METHOD = {};
export type HTTPMethod = typeof HTTP_METHOD[keyof typeof HTTP_METHOD];
```
다음과 같이 바꿔주세요. 불필요한 제네릭 사용입니다.

2022-08-25 11:19 UTC, SimYunSup commented on src/utils/hooks/useLogin.ts
> +import { LoginResponse } from 'api/auth/entity';
useLogin은 다른 파일에서 사용하지 않는데 왜 파일을 분리하였나요?
파일 내 hooks로 분리하라고 말씀드렸는데요.

2022-08-25 11:19 UTC, SimYunSup commented on src/pages/Auth/LoginPage/index.tsx
> +  const [isAutoLoginFlag, setIsAutoLoginFlag] = React.useState(false);
hooks를 사용 목적에 따라 "모두" 분리해주세요.

2022-08-25 11:41 UTC, SimYunSup commented on src/pages/Auth/LoginPage/LoginPage.module.scss
> +.styledinput {
-가 들어간 맴버 변수 or 메소드를 사용하려면 무조건 대괄호 표기법으로 접근해야합니다.
말했다시피 BEM표기법과 CSS Modules를 혼용한 이상 대괄호 표기법으로 접근하는 것은 어쩔 수 없고, BEM 표기법을 확인해보시면 알겠지만 상태를 사용하려면 무조건 class를 두개 이상 써야 합니다. 그로 인해 cn에 들어있는 변수가 대괄호 표기법으로 접근해야 해서 착각하신 것으로 보입니다. 대괄호 표기법과 cn과는 전혀 상관이 없습니다.
코드 미관이 저해된다는 것은 너무 주관적인 생각입니다. 코드 모양이 이쁘려고 코드를 짜는 것은 아니잖아요?
그리고 대괄호 표기법을 지양해야 하는 경우는 해당 객체가 문서화(타입 매핑)이 되어있을 경우 자동완성과 타입 매핑을 위해서 지양하는 것이라고 생각합니다. 하지만 CSS Modules은 타입 매핑이 안 되어있으므로 상관이 없다고 생각하구요.

2022-08-25 11:45 UTC, SimYunSup commented on src/pages/Auth/LoginPage/index.tsx
> +import useLogin from '../../../utils/hooks/useLogin';
ESLint 세팅을 강화하겠습니다. 이슈로 달아놓을게요.

2022-08-25 16:38 UTC, daepan commented on src/App.tsx
> +  const [token, setToken] = useRecoilState<string>(tokenState);
제거하였습니다!
[507b35a](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/7/commits/507b35ac76f2e3afcb96f2aedde3901af269e482)

2022-08-25 16:38 UTC, daepan commented on src/api/apiClient.ts
> +export type UnionHttpMethod<T> = T[keyof T];
제네릭 제거와 해당 관련 변수 수정하였습니다
[0251961](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/7/commits/025196143f1455e8e757c00eba11cc1d72357576)

2022-08-25 16:39 UTC, daepan commented on src/utils/hooks/useLogin.ts
> +import { LoginResponse } from 'api/auth/entity';
훅으로 분리하라는 말에 집중해버려서 파일 내라는 내용을 잘 듣지 못한 것 같습니다. 현재 파일내에서 훅으로 기능을 분리해두었습니다. 혹시라도 더 분리해야되거나 부족한 점 있으면 말씀해주세요
[93b00f4](https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/7/commits/93b00f439230e06bede57279f4a075cefde2c63f)

2022-08-25 16:59 UTC, SimYunSup requested changes
추가로 바꾸면 좋을것들을 생각해서 리뷰해드렸습니다.

2022-08-25 16:59 UTC, SimYunSup commented on src/api/apiClient.ts
> +};
`as const`를 빼면 `string`으로 추론됩니다.

2022-08-25 16:59 UTC, SimYunSup commented on src/pages/Auth/LoginPage/LoginPage.module.scss
> +  &__finduser {
```suggestion
  &__link {
    text-decoration: none;
    color:#858585;
    padding-right:19px;
    padding-left: 14px;
    cursor: pointer;
    & + & {
      border-left: 1px #d2dae2 solid;
    }
```
방식으로 바꿀 수 있습니다. 각각의 이름을 따로 붙이지 않아도 되죠.

2022-08-25 16:59 UTC, SimYunSup commented on src/utils/ts/cookie.ts
> +  return false;
`false`가 아닌 `undefined`로 해주시길 바랍니다.

2022-08-25 16:59 UTC, SimYunSup commented on src/App.tsx
> +  const [token, setToken] = useRecoilState(tokenState);
해당 부분도 hooks로 분리하면 좋겠죠?

2022-08-25 17:10 UTC, SimYunSup commented on src/pages/Auth/LoginPage/index.tsx
> +const useAutoLoginFlag = () => {
해당 hook은 `useBooleanState` 사용으로 바꿔주세요.

2022-08-28 11:08 UTC, SimYunSup approved these changes
고생하셨습니다. 다음 이슈 생성 후 진행하시길 바랍니다.

2022-08-28 11:27 UTC, ChoiWonBeen approved these changes

2022-08-28 14:48 UTC, merged