[#81] 시간표 마지막 업데이트 날짜 보여주기 기능 추가
BCSDLab/KOIN_WEB_RECODE pull request #89
Opened 2024-03-20 11:55 UTC by Gwak-Seungju

## What is this PR? 🔍

- 기능 : 강좌 목록 마지막 업데이트 날짜 보여주기 기능
- issue : #81  

## Changes 📝

시간표 페이지에 강좌 목록이 마지막으로 업데이트 된 날짜를 보여줍니다.
## ScreenShot 📷

![image](https://github.com/BCSDLab/KOIN_WEB_RECODE/assets/74342515/44aa0d66-1bd1-45c8-be79-9e19de248399)

## Test CheckList ✅

## Precaution

## Please check if the PR fulfills these requirements

- [ ] It's submitted to `develop` branch, __not__ the `main` branch
- [ ] The commit message follows our guidelines
- [ ] There are no warning message when you run `yarn lint`
- [ ] Docs updated for breaking changes

2024-03-20 12:07 UTC, hanagertrudeKim requested changes
첫 PR 축하드립니다 👍 
api 요청도 잘 진행된 것 같네요. 고생하셨습니다 :)

2024-03-20 12:07 UTC, hanagertrudeKim commented on src/api/timetable/APIDetail.ts
> +
지금은 요청값을 'last_update' 만 활용하더라도, 나중에 버전 관련한 응답을 활용할 때를 대비해서 클래스 네임을 확장성 있게 가져가는 것도 좋을 것 같아요~
요청 api 와 비슷하게 `Version~` 으로 가져보는 것도 좋을 것 같네요

2024-03-20 12:07 UTC, hanagertrudeKim commented on src/api/timetable/entity.ts
> +};
timetable에서만 쓰이는 값일까요? 나중에 다른 도메인에서 이 인터페이스가 쓰일 경우는 없을까요?

2024-03-20 12:07 UTC, hanagertrudeKim commented on src/components/TimetablePage/DefaultPage/DefaultPage.module.scss
> +
👍 👍

2024-03-20 12:07 UTC, hanagertrudeKim commented on src/components/TimetablePage/DefaultPage/index.tsx
> +      {(updatedDate as unknown as TimetableVersionInfo).updated_at.substring(0, 11).replaceAll('-', '. ').replace('T', '.')}
`as` 키워드를 사용하여 타입 단언을 한 이유가 있을까요?

2024-03-20 12:09 UTC, ChoiWonBeen commented on src/components/TimetablePage/DefaultPage/index.tsx
> +      {(updatedDate as unknown as TimetableVersionInfo).updated_at.substring(0, 11).replaceAll('-', '. ').replace('T', '.')}
`updatedDate`가 `TimetableVersionInfo` 로 추론되게끔 잡아줄 역할이 필요해보여요~!

2024-03-20 12:09 UTC, ChoiWonBeen commented on src/api/timetable/entity.ts
> +}
그 역할은 아마 여기서 해줄 수 있을 것 같네요

현재 이 Response는 배열 구조를 반환하는거예요.
api의 response가 
```ts
response = [
  TimetableVersionInfo객체,
  TimetableVersionInfo객체
]
```
처럼 올 때 쓰는거지여

아마 이걸 원하는 방식으로 바꾸려면, 요걸 수정하면 data의 타입이 잡혀줄거예요~
```suggestion
export interface LastUpdatedDateResponse extends APIResponse {
  id: string;
  version: string;
  type: string;
  created_at: string;
  updated_at: string;
}
```

2024-03-20 12:09 UTC, ChoiWonBeen commented on src/api/timetable/entity.ts
> +}
이렇게 바꾸고나면 `data: updatedDate` 의 타입을 확인했을때 원하는 타입과 가까워졌을거예요

2024-03-20 12:51 UTC, ChoiWonBeen commented on src/components/TimetablePage/DefaultPage/index.tsx
> +            <LastUpdatedDate />
사소하지만 `마지막 업데이트 날짜:` 글자까지 같이 컴포넌트에 묶이는게 깔끔하지 않을까 싶어용
 div도 같이 옮겨도 좋아보이구요~

이유는 띄어쓰기나, 글꼴 수정에 용이할 것 같아서예요

2024-03-20 13:13 UTC, daepan requested changes
리뷰 남겨둔 부분 답변부탁드립니다~

2024-03-20 13:13 UTC, daepan commented on src/components/TimetablePage/DefaultPage/hooks/useLastUpdatedDate.ts
> +      suspense: true,
훅과 관련된 기능에서 suspense를 활용하지 않았는데 true로 두고 있는 것 있습니다. 기능을 추가하거나 제거하면 좋을 것 같습니다.

2024-03-20 13:13 UTC, daepan commented on src/components/TimetablePage/DefaultPage/index.tsx
> +      {(updatedDate as unknown as TimetableVersionInfo).updated_at.substring(0, 11).replaceAll('-', '. ').replace('T', '.')}
이렇게 일정 표기 기능들에서 string에 대한 메서드로 substring, replace 시키던 거는 조금 레거시 부분이 되어 있는 것 같습니다.  (이전에 Moment 이런거 추가하자 했었는데 라이브 의존성 뭐시기 하면서 거절당했었네요)
서버에서 나오는 ~~At 일정들의 패턴을 분석해서 한번에 YYYY-MM-DD 식의 호출로 문자열을 반환해주는 함수를 만들어보면 어떨까요?

2024-03-20 13:13 UTC, daepan commented on src/pages/Auth/ModifyInfoPage/index.tsx
> +    console.log(currentValue);
요거 console 제가 이전에 제거하지 않은 부분 같네요. 제거해주시면 감사하겠습니다

2024-03-20 13:13 UTC, daepan commented on src/components/TimetablePage/DefaultPage/hooks/useLastUpdatedDate.ts
> +    ({ queryKey }) => timetable.getLastUpdatedDate(queryKey[0] ?? 'timetable'),
'timetable' ?? 'timetable' 처럼 읽히는데 해당 방식의 조건문을 채택한 이유가 있을까요?

2024-03-21 01:44 UTC, kimeodml reviewed
첫 pr 축하드려요~! 고생하셨습니다!

2024-03-21 01:44 UTC, kimeodml commented on src/api/timetable/entity.ts
> +};
아래와 같이 type의 타입을 좁혀도 될 것 같아요.
```suggestion
export type VersionType = 'android' | 'timetable' | 'shuttle_bus_timetable' | 'express_bus_timetable' | 'city_bus_timetable';

export type TimetableVersionInfo = {
  id: string;
  version: string;
  type: VersionType ;
  created_at: string;
  updated_at: string;
};
```

2024-03-21 03:27 UTC, hoooooony commented on src/components/TimetablePage/DefaultPage/index.tsx
> +            마지막 업데이트 날짜:
제기 이번에 올린 PR에서 UpdateInfo를 공용 컴포넌트로 사용했는데,
이걸 활용하면 좋을 것 같아요. 궁금하거나 수정이 필요한 부분있으면 DM 주세요🙏

2024-03-21 06:11 UTC, Gwak-Seungju commented on src/pages/Auth/ModifyInfoPage/index.tsx
> +    console.log(currentValue);
넵 제거했습니다. 감사합니다!

2024-03-21 09:16 UTC, Gwak-Seungju commented on src/api/timetable/APIDetail.ts
> +
그렇네요! 수정했습니다!
2b25648bd304c82f473dd766d10a681207121496

2024-03-21 09:17 UTC, Gwak-Seungju commented on src/api/timetable/entity.ts
> +};
좋은 것 같습니다!! 반영했습니다!
c3c0e69840e42a5f7cc82c9afe787100f6874332

2024-03-21 09:19 UTC, Gwak-Seungju commented on src/api/timetable/entity.ts
> +}
확실히 이렇게 하니까 updatedDate 타입에 어떤 게 있는지 쉽게 확인이 가능하네요!! 반영했습니다!
c3c0e69840e42a5f7cc82c9afe787100f6874332

2024-03-21 10:05 UTC, Gwak-Seungju commented on src/components/TimetablePage/DefaultPage/index.tsx
> +            <LastUpdatedDate />
'마지막 업데이트 날짜:  ' 이렇게 써도 띄어쓰기가 반영이 안되어서 살짝 당황했는데, eslint 때문에 안되는 걸까요..? css로만 띄어쓰기를 할 수 있는 건지도 궁금합니다..! 일단 margin으로 띄어쓰기처럼 구현은 했습니다.
0ce6f1a1b2199e71e3cc272c46db3083f32003b0

2024-03-21 10:34 UTC, Gwak-Seungju commented on src/components/TimetablePage/DefaultPage/hooks/useLastUpdatedDate.ts
> +      suspense: true,
'suspense: true'를 없애면 'updated_at'을 찾을 수 없다고 합니다. 따라서 suspense 사용을 추가했습니다.
85b568d2f659a9b668c78c9e96b69c2748d488a6

2024-03-21 10:36 UTC, Gwak-Seungju commented on src/components/TimetablePage/DefaultPage/index.tsx
> +      {(updatedDate as unknown as TimetableVersionInfo).updated_at.substring(0, 11).replaceAll('-', '. ').replace('T', '.')}
반영했습니다..! 감사합니다! 말씀하신 부분이 이렇게 반영하는 게 맞는지 싶습니다..!
0ce6f1a1b2199e71e3cc272c46db3083f32003b0

2024-03-21 10:38 UTC, Gwak-Seungju commented on src/components/TimetablePage/DefaultPage/hooks/useLastUpdatedDate.ts
> +    ({ queryKey }) => timetable.getLastUpdatedDate(queryKey[0] ?? 'timetable'),
가독성 측면에서 저렇게 기입했었던 것 같습니다! 하지만, 전혀 필요가 없는 코드 같네요! 수정했습니다!!
392e239a17ec063359d8e8266f5b57a1d77def62

2024-03-22 16:30 UTC, Gwak-Seungju commented on src/components/TimetablePage/DefaultPage/index.tsx
> +      {(updatedDate as unknown as TimetableVersionInfo).updated_at.substring(0, 11).replaceAll('-', '. ').replace('T', '.')}
기존 다른 컴포넌트에서 사용한 코드를 참고하여 작성했기 때문에 타입 단언을 이용한 큰 이유는 없습니다! timetable이란 타입의 버전만 받아오므로 타입 정보가 확실하여 타입 단언을 사용해도 된다고 생각했습니다!

2024-03-23 04:50 UTC, Gwak-Seungju commented on src/components/TimetablePage/DefaultPage/index.tsx
> +            마지막 업데이트 날짜:
넵! 감사합니다! 좋은 공용 컴포넌트인 것 같습니다. 제가 사용한 로직과 달라 변경될 사항이 많아질 것 같아서 따로 사용해 보겠습니다..! 감사합니다!

2024-03-25 09:26 UTC, hanagertrudeKim approved these changes
첫 PR 수고하셨습니다~ :) 
마무리 이슈 하나만 확인해주시고, 확인되면 바로 머지해도 좋을 것 같아요

2024-03-25 09:26 UTC, hanagertrudeKim commented on src/components/TimetablePage/DefaultPage/index.tsx
> +            <React.Suspense fallback="loading...">
이번 시간표 이슈로 이미 나온 내용인데 fallback 으로 로딩 svg를 대체하면 좋을 것 같아요 (위에도 동일하게 적용하면 좋겠네요)

2024-03-25 11:43 UTC, daepan approved these changes
수고하셨습니다.

2024-03-25 16:06 UTC, merged